### ISSUE TITLE
Remove the pipes and add a spring to dd

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1002]
![image](https://github.com/user-attachments/assets/4fc7b172-3fc4-4ba1-8c09-ad50d3b042f2)

**Comment by EmeraldLoc** [comment]
I already thought about this, I like the pipe more imo, feels like it adds more places you are mostly required to run to, whereas with a spring it'd cause a bunch of circling. Also, imagine reacting to your own message, L
