### ISSUE TITLE
New level - The Castle Tower

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1003]
Dont really see anything wrong with it
![image](https://github.com/user-attachments/assets/0a73fb04-460f-448e-a5f3-078749710933)

**Comment by Bear64DX** [comment]
*Endless Staircase...*

**Comment by TheMan6900** [comment]
just lock the doors

**Comment by Bear64DX** [comment]
> just lock the doors

:fire:

**Comment by EmeraldLoc** [comment]
Valid

**Comment by EmeraldLoc** [comment]
Thanks bear
