### ISSUE TITLE
Level Edition - Windy Wing Cap Well

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1005]
Invisible walls covering the outside (block api)
![image](https://github.com/user-attachments/assets/9eba6e43-f470-42a3-a4da-1490cb375ab8)

**Comment by EmeraldLoc** [comment]
what's windy wing cap well

**Comment by TheMan6900** [comment]
> what's windy wing cap well

a star road level.

**Comment by EmeraldLoc** [comment]
Oh, that level's fine as it is

**Comment by Bear64DX** [comment]
> Oh, that level's fine as it is

hmm
