### ISSUE TITLE
Vote Cancelling

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#101]
Credit to Bear for the idea.

You'd basically be able to cancel your vote mid-voting via pressing the B button  
Along with this when voting on a map, a popup right under your chosen map saying, "You can cancel your vote by pressing B" would appear. Teaching or simply reminded players of this feature.

**Comment by EmeraldLoc** [comment]
I've been suggested this way too many times, should just add it.

**Comment by TheMan6900** [comment]
You think? lol

**Comment by EmeraldLoc** [comment]
Added, it was 1 line btw lol.
