### ISSUE TITLE
Make The Stage Fall Apart Gradually In B3

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1010]
Would make the stage feel more climactic, and just would be cooler.

**Comment by EmeraldLoc** [comment]
Yea I was thinking of this, would def be a cool idea!

**Comment by Bear64DX** [comment]
wait didnt i suggest this before- i cant recall lol. Peak idea tho

**Comment by EmeraldLoc** [comment]
Done
