### ISSUE TITLE
Colored pipes past purple get rendered as an [ERROR]

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#1012]
2 workarounds for this are:
- Adding more pipe color slots
- Just make the colors loop after purple
![image](https://github.com/user-attachments/assets/d2edf743-6854-4276-82fc-b652647b7b33)

**Comment by TheMan6900** [comment]
def do the first option (first I meant first), colored pipes are supposed to help players know what pipe set, leads to where.

**Comment by EmeraldLoc** [comment]
For now im gonna have it loop. This was actually known about, however I didn't think anyone would be crazy enough to add as many pipes as I have.

**Comment by Bear64DX** [comment]
> For now im gonna have it loop. This was actually known about, however I didn't think anyone would be crazy enough to add as many pipes as I have.

Just wait till I show you the peakest level in existence with the most pipes in existence :))))))

**Comment by EmeraldLoc** [comment]
Resolved
