### ISSUE TITLE
Auto Hide Hud doesnt work while playing solo

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1014]
dont know why

**Comment by EmeraldLoc** [comment]
Because a game isn't started?

**Comment by TheMan6900** [comment]
why should that be a factor though

**Comment by EmeraldLoc** [comment]
If a round isn't started, what's the point of hiding the hud?

**Comment by TheMan6900** [comment]
so I can test it

**Comment by EmeraldLoc** [comment]
Test hiding the hud?!!?!?!? Brother start a game if you want to do that, it doesn't need testing.
