### ISSUE TITLE
Make the camera angle on spawn adjustable

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1015]
would be a nice api edition espically since one of my levels would benefit from it (or needs it)

**Comment by EmeraldLoc** [comment]
Use `levelInit` with a function that does this, this is very much so an edge case, and isn't really needed at all. I'm unsure of how to do this, however using `levelInit` it's def possible

**Comment by TheMan6900** [comment]
how do you do that?

**Comment by EmeraldLoc** [comment]
> I'm unsure of how to do this
