### ISSUE TITLE
Modifier Help

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#102]
Credits to Bear for the idea,

A category in the help section that would explain how modifiers work.

**Comment by EmeraldLoc** [comment]
So much writingggggg

**Comment by TheMan6900** [comment]
Lazy

**Comment by EmeraldLoc** [comment]
Ok, go write them yourself.

**Comment by TheMan6900** [comment]
No

**Comment by TheMan6900** [comment]
ADD !! !!

**Comment by EmeraldLoc** [comment]
Added
