### ISSUE TITLE
New api - Force Hazards

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1025]
This would force hazards to be on. would be kinda cool for one of the levels Im making

**Comment by Bear64DX** [comment]
i dont have a good feeling abt this, that just me?

**Comment by TheMan6900** [comment]
Would be cool to have stuff to avoid in levels, while playing. (since some levels in my port would just be funner with hazards on)

**Comment by TheMan6900** [comment]
(this could also be "forced setting")

**Comment by EmeraldLoc** [comment]
The only thing I would fine a little bit acceptable is forcing hazards off, forcing them on is a definite no no. Even forcing them off isn't great.
