### ISSUE TITLE
Levelloop doesnt get cancel, once going out of a level

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1028]
was testing out the set_fog_intensity(0) thing you told me, than I exited, the level I was using it in and every stage was fogless so.

**Comment by EmeraldLoc** [comment]
So you're starting a new level using the start menu?

If so, this isn't really a fault with Tag, you just need to reset the fog intensity once you exit a level. The solution for this is me making another API entry that allows for a api call when a level is about to be changed
