### ISSUE TITLE
Whats wrong with the other star road castle levels

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1035]
Im just curious, they seem pretty good.

**Comment by EmeraldLoc** [comment]
Don’t know what levels you’re referring to.

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/462b55ca-36f1-4995-926c-d2205429e4af)

**Comment by EmeraldLoc** [comment]
Oh, castle levels. They’re too small

**Comment by TheMan6900** [comment]
not much different from the upper castle level in vanilla

**Comment by TheMan6900** [comment]
or atleast the bottom one is.

**Comment by EmeraldLoc** [comment]
Bottom ones been added I think?

**Comment by TheMan6900** [comment]
oh wait I mean the bottom one on the picture, not the sewer level.

**Comment by TheMan6900** [comment]
I can pr that for ya if you want
