### ISSUE TITLE
werid error

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1036]
![image](https://github.com/user-attachments/assets/88490354-4ddb-4ceb-9832-e6dbea876b4e)

**Comment by EmeraldLoc** [comment]
2.4 or 2.4.1?

**Comment by TheMan6900** [comment]
2.4

**Comment by EmeraldLoc** [comment]
What were you doing when this occurred? I know this a month ago so you prob don't remember lol

**Comment by TheMan6900** [comment]
pretty sure I just simply joined the lobby

**Comment by EmeraldLoc** [comment]
Ok then I believe I fixed an issue like this. If it pops up in 2.4.1 lmk
