### ISSUE TITLE
Player Spectate Mode QOL

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1038]
![image](https://github.com/user-attachments/assets/40ee34c9-51f1-4bac-a3d7-a3ebf1be6a4a)
 (the player names would be a lot smaller ofc)

**Comment by EmeraldLoc** [comment]
Eh

**Comment by Bear64DX** [comment]
Man... this is PEAK.

**Comment by TheMan6900** [comment]
fr
