### ISSUE TITLE
Make dive slides instantly spawn a shell

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1039]
dive slides are interactions with the ground so. (just make shells not cancel dives, would make them feel a lot more natural to perform)

**Comment by EmeraldLoc** [comment]
There’s a cooldown, no

**Comment by TheMan6900** [comment]
why is there even a cooldown?

**Comment by EmeraldLoc** [comment]
Cuz I think it feels better, nothing really else to say there
