### ISSUE TITLE
Stats Hover

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#104]
When hovering over a players name a sidebar (completely separate from the Ui) would appear displaying that players general stats.

**Comment by EmeraldLoc** [comment]
Where are you hovering?

**Comment by TheMan6900** [comment]
Wdym, I literally said that in the thing.

**Comment by EmeraldLoc** [comment]
The stats menu? Im gonna be technical, look, you said when hovering over a players name, location not specified, sure you said it would show stats, but would this show in the players settings menu?

**Comment by TheMan6900** [comment]
No

**Comment by EmeraldLoc** [comment]
It's 2 buttons away, you can mash a and get there in 0.1 seconds.

**Comment by TheMan6900** [comment]
ok fair enough, it sounded more useful in my head
