### ISSUE TITLE
Make doors not open if there incased in a block

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1042]
![image](https://github.com/user-attachments/assets/9ca33e0e-b023-4f66-ab84-778482e7d570)

**Comment by Bear64DX** [comment]
This is actually great for those who only want specific doors disabled.

**Comment by EmeraldLoc** [comment]
Firstly, no. Ok now for what you actually want.

The goal you are wanting I take it is to disable only a specific door. There may be a way for me to accomplish this, however it can be tricky. I’ll look into this.

**Comment by Bear64DX** [comment]
> is to disable only a specific door.

That's basically what I want lol. But tbh i don't see why we can't just use this solution, since it sounds the easiest imo.

**Comment by EmeraldLoc** [comment]
It's not a real solution, it feels a lot more like a workaround. (plays average 9 year old tutorial music) (add bandicam watermark) (crusty mic + notepad++ + mumbling) "Hey guys, in this SM64 Tag Tutorial, we're gonna be learning how to disable doors! So to get started, first..." (20 second pause as they try to remember what to do) "Sorry about that, uh, so you're going to want to go to the door and uh, once you get there" (insert 10 second pause) "create a block at the doors position so it covers the door" (sick editing cut plays) "alright everyone, thank you so much for watching. Be sure to like and subscribe, I'm so close to 10 subscribers, we're at 6 right now, think we can make it by the end of the year?" (stutters) "Oh and uh, and uh, uh, be sure to hit the notificat..." (mom yells) "ion, uh, yea" (rushes) "hit motisficatin and subriscib n like bye :D" (play epic outro).

**Comment by Bear64DX** [comment]
> It's not a real solution, it feels a lot more like a workaround. (plays average 9 year old tutorial music) (add bandicam watermark) (crusty mic + notepad++ + mumbling) "Hey guys, in this SM64 Tag Tutorial, we're gonna be learning how to disable doors! So to get started, first..." (20 second pause as they try to remember what to do) "Sorry about that, uh, so you're going to want to go to the door and uh, once you get there" (insert 10 second pause) "create a block at the doors position so it covers the door" (sick editing cut plays) "alright everyone, thank you so much for watching. Be sure to like and subscribe, I'm so close to 10 subscribers, we're at 6 right now, think we can make it by the end of the year?" (stutters) "Oh and uh, and uh, uh, be sure to hit the notificat..." (mom yells) "ion, uh, yea" (rushes) "hit motisficatin and subriscib n like bye :D" (play epic outro).

real
