### ISSUE TITLE
Screen Transitions From Voting Screen To Level Spawn

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1044]
Maybe a fade to black, followed by a fade back, would just make the transitions looks nicer

**Comment by EmeraldLoc** [comment]
it looks fine

**Comment by TheMan6900** [comment]
I mean like the fade out animation, when exiting a level, I dont really know how to examine this.

**Comment by EmeraldLoc** [comment]
> it looks fine
