### ISSUE TITLE
Single Tagger Disconnect Failsafe

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1048]
If the last tagger disconnected a message saying "X Disconnected X is now the *Tagger Role*" would display and that X would be the next tagger, this would be really useful for modes like terminator.

**Comment by EmeraldLoc** [comment]
Huh

**Comment by TheMan6900** [comment]
lets say a terminator disconnects, another player would be determinded as the termiantor to fill in for that terminators absence, thats basically how this would work.

**Comment by EmeraldLoc** [comment]
no
