### ISSUE TITLE
Tagger Ring Trail falsely given?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1050]
![image](https://github.com/user-attachments/assets/737b5b89-cad2-4caf-8bd7-7a2ff66612b3)
![image](https://github.com/user-attachments/assets/e46afd07-8de7-4046-bf2b-2dc1ee806523)
(done with "TheN64Guy")

**Comment by EmeraldLoc** [comment]
Does your trail also happen to be the tagger ring trail? Have a feeling this is the same bug as the title issue

**Comment by EmeraldLoc** [comment]
Holy I figured out the problem. Fresh eyes help so much lol, should be resolved.

If you want to reproduce it, there should be an easy way. Host a game, have 2 players join. Have the first player have a tag on it, say, the romhack title, set the second player to have no title, and do it in that order. Have the first player disconnect, then the second player. Then have the second player reconnect, and boom.
