### ISSUE TITLE
A full on Shop system

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1052]
Something kirbuddy suggested awhile ago.

Youd be able to purchase stuff, from the shop with currency (obviously)
This currency could be obtained by winning matches.

**Comment by EmeraldLoc** [comment]
Perfect idea. I can begin implementing micro-transactions immediately, hahahaha.

Yea this would be cool.

**Comment by Bear64DX** [comment]
> Perfect idea. I can begin implementing micro-transactions immediately, hahahaha.

tag = fell off confirmed????

**Comment by TheMan6900** [comment]
how would you even implement micro-transactions 💀

**Comment by Bear64DX** [comment]
> who would you even implement micro-transactions 💀

fr

**Comment by TheMan6900** [comment]
Another idea I had for the shop system is to have limited time, items/rewards that you can only get during seasonal events.

**Comment by EmeraldLoc** [comment]
> who would you even implement micro-transactions 💀

Im afraid this is being taken too seriously. I am HEAVILY against micro transactions, they suck, ruin games, and are made for babies.

> Another idea I had for the shop system is to have limited time, items/rewards that you can only get during seasonal events.

Eh, I like the idea of all items existing at once. I like what Geometry Dash does.

**Comment by TheMan6900** [comment]
I personally would like if tag adopted a shop system similar to how "untitled tag game" and probably some other games (I couldnt think of any else) where all its different items/rewards are split into sections (also no Im not bringing it up because its tag related I just like its shop)
![image](https://github.com/user-attachments/assets/fe3d9b9a-dc5a-42d7-a8ff-f6b478b9e008)
ignore the fready faze bear skin :skull:

**Comment by Bear64DX** [comment]
> I personally would like if tag adopted a shop system similar to how "untitled tag game" and probably some other games (I couldnt think of any else) where all its different items/rewards are split into sections (also no Im not bring up it because its tag related I just like its shop) ![image](https://private-user-images.githubusercontent.com/168046906/356435512-fe3d9b9a-dc5a-42d7-a8ff-f6b478b9e008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjg5MDEsIm5iZiI6MTcyMzE2ODYwMSwicGF0aCI6Ii8xNjgwNDY5MDYvMzU2NDM1NTEyLWZlM2Q5YjlhLWRjNWEtNDJkNy1hOGZmLWY2YjQ3OGI5ZTAwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMTU2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDhiYmZhZjQ1MjdjMDJjNzg2ZTk4NTk0Nzk0MWYzMGUzMGE2ZmRmNjgxZGYxODgyNTMzNTIyNzU3YTg1Mjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bbka5H5dgpCDJqUNXAjnfNoUEENgbrOcO196sQ0qvLc) ignore the fready faze bear skin 💀

brainrot shop 💀

**Comment by EmeraldLoc** [comment]
Roblox, such an L.

Anyways, being fr, I'd have it categorized yea, not like that with big cards, cuz I hate those, but I'd have it organized.

**Comment by Bear64DX** [comment]
> Roblox, such an L.

real

**Comment by TheMan6900** [comment]
> Roblox, such an L.

I like Roblox.....

**Comment by EmeraldLoc** [comment]
And some people think Hotel Mario is good

Doesn't mean its a good opinion

(being honest now, idc what you play, just don't really like Roblox lol)

**Comment by Bear64DX** [comment]
> (being honest now, idc what you play, just don't really like Roblox lol)

This is honestly the best answer tbh

**Comment by TheMan6900** [comment]
> And some people think Hotel Mario is good
> 
> Doesn't mean its a good opinion
> 
> (being honest now, idc what you play, just don't really like Roblox lol)

wasnt being that serious lol

**Comment by TheMan6900** [comment]
(oh yeah I also would like if the sections were also split up into pages, just like how it also does)

**Comment by EmeraldLoc** [comment]
Pages suck, grids and scrolling is the best combo!

**Comment by TheMan6900** [comment]
well Iike pages more personally

**Comment by TheMan6900** [comment]
(oh yeah bundles would also be cool)

**Comment by EmeraldLoc** [comment]
Bundles are for babies who can't get all the coins. Get good.

**Comment by TheMan6900** [comment]
> Bundles are for babies who can't get all the coins. Get good.

:skull:

**Comment by TheMan6900** [comment]
oh yeah Id also like a trading system to go along with it- *explosion gif*

**Comment by Bear64DX** [comment]
> oh yeah Id also like a trading system to go along with it- _explosion gif_

yo tm trade my lil bro ur romhack porter title right now.

**Comment by EmeraldLoc** [comment]
So you can get free stuff? Yea no, only items with a value of 1500 toins, and both items have to be of that value!

**Comment by TheMan6900** [comment]
> > oh yeah Id also like a trading system to go along with it- _explosion gif_
> 
> yo tm trade my lil bro ur romhack porter title right now.

Ok! *gets scam*

**Comment by EmeraldLoc** [comment]
(jk yea good idea)

**Comment by TheMan6900** [comment]
wait what should the currency be called

**Comment by EmeraldLoc** [comment]
Robux

**Comment by Bear64DX** [comment]
Tagbux

**Comment by TheMan6900** [comment]
Tag Coins

**Comment by EmeraldLoc** [comment]
I didn't know this was possible, but somehow you both made a worse name than "toins"

**Comment by EmeraldLoc** [comment]
just gonna call it a dollar or something lol

**Comment by Bear64DX** [comment]
> I didn't know this was possible, but somehow you both made a worse name than "toins"

you suggested "robux" 💀

**Comment by TheMan6900** [comment]
wait what if the currency used this image but coinified
![image](https://github.com/user-attachments/assets/9e85d69d-2c2c-4fbb-9b96-809148da2301)

**Comment by Bear64DX** [comment]
The tag logo lol

**Comment by EmeraldLoc** [comment]
> wait what if the currency used this image but coinified ![image](https://private-user-images.githubusercontent.com/168046906/356439245-9e85d69d-2c2c-4fbb-9b96-809148da2301.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzAzMzcsIm5iZiI6MTcyMzE3MDAzNywicGF0aCI6Ii8xNjgwNDY5MDYvMzU2NDM5MjQ1LTllODVkNjlkLTJjMmMtNGZiYi05Yjk2LTgwOTE0OGRhMjMwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMjIwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjFmZjBhNjdkOGUzNWJkODgwY2I2MmI1MDUwNjE5NTc1ZTg4ZDQ5YzZiMzEyMzRjOTBmZWEyM2YwODk5MzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EV6XR40X6bMw4vBJYWTWmIH2hEugcw_2VjeNSETjvxk)

🤮 



> > I didn't know this was possible, but somehow you both made a worse name than "toins"
> 
> you suggested "robux" 💀

arguably better

Hold up I got a fire name... "Bittag"

**Comment by TheMan6900** [comment]
nah that would be a peak image

**Comment by TheMan6900** [comment]
(also the image could just be a red and blue coin)

**Comment by EmeraldLoc** [comment]
lemme cook rq

**Comment by TheMan6900** [comment]
> lemme cook rq

could we see what you cook when your done 😃

**Comment by Bear64DX** [comment]
Nah, name it "Tagoins" 🔥

**Comment by EmeraldLoc** [comment]
![Tag Iteration 2](https://github.com/user-attachments/assets/5a16c709-9442-4d52-b2a2-bc965c609b2d)
![Tagbit iteration 1](https://github.com/user-attachments/assets/9f0c2aca-f547-457a-978d-e4da90da6131)

These are very early stage, both of these prob won't be final. Curious on which design you prefer.

**Comment by TheMan6900** [comment]
top looking pretty slick ngl

**Comment by Bear64DX** [comment]
I kinda like the bottom one, the top one doesn't look like a T lol.

**Comment by TheMan6900** [comment]
bottom one is more versatile than the top one (more can be done with its design)

**Comment by TheMan6900** [comment]
id personally go with the bottom one

**Comment by EmeraldLoc** [comment]
![Tag Iteration 3](https://github.com/user-attachments/assets/c77e8923-e41b-40c0-b0e6-8cec7d601b20)

**Comment by EmeraldLoc** [comment]
![Tag Iteration 4](https://github.com/user-attachments/assets/97e13fac-a51e-47e4-9047-d2ca4d7e0a28)

**Comment by Bear64DX** [comment]
> ![Tag Iteration 4](https://private-user-images.githubusercontent.com/86802223/356443777-97e13fac-a51e-47e4-9047-d2ca4d7e0a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzIwNzksIm5iZiI6MTcyMzE3MTc3OSwicGF0aCI6Ii84NjgwMjIyMy8zNTY0NDM3NzctOTdlMTNmYWMtYTUxZS00N2U0LTkwNDctZDJjYTRkN2UwYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAyNDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YTBmN2QwNDc2NGJlNTAxNDJiOTA1MzhhZTUwNmVlNTI4YTRiNGZiNDA0MzczYzcyOWU3OWQ3MDkzNmVmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qoUxw-1PvvgRptqzV9pnLKnKpVSD98942wsiMaaU4PE)

tesla logo aa- 😭 💀

**Comment by EmeraldLoc** [comment]
Out of the 4 here, what is your favorite?

**Comment by Bear64DX** [comment]
> ![Tag Iteration 4](https://private-user-images.githubusercontent.com/86802223/356443777-97e13fac-a51e-47e4-9047-d2ca4d7e0a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzIwNzksIm5iZiI6MTcyMzE3MTc3OSwicGF0aCI6Ii84NjgwMjIyMy8zNTY0NDM3NzctOTdlMTNmYWMtYTUxZS00N2U0LTkwNDctZDJjYTRkN2UwYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAyNDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YTBmN2QwNDc2NGJlNTAxNDJiOTA1MzhhZTUwNmVlNTI4YTRiNGZiNDA0MzczYzcyOWU3OWQ3MDkzNmVmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qoUxw-1PvvgRptqzV9pnLKnKpVSD98942wsiMaaU4PE)

Tbh this is my fav ngl

**Comment by EmeraldLoc** [comment]
> > ![Tag Iteration 4](https://private-user-images.githubusercontent.com/86802223/356443777-97e13fac-a51e-47e4-9047-d2ca4d7e0a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzIwNzksIm5iZiI6MTcyMzE3MTc3OSwicGF0aCI6Ii84NjgwMjIyMy8zNTY0NDM3NzctOTdlMTNmYWMtYTUxZS00N2U0LTkwNDctZDJjYTRkN2UwYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAyNDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YTBmN2QwNDc2NGJlNTAxNDJiOTA1MzhhZTUwNmVlNTI4YTRiNGZiNDA0MzczYzcyOWU3OWQ3MDkzNmVmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qoUxw-1PvvgRptqzV9pnLKnKpVSD98942wsiMaaU4PE)
> 
> tesla logo aa- 😭 💀

That was actually my inspiration, stunned you saw that LOL, it's pretty much a meaner looking Tesla logo

**Comment by TheMan6900** [comment]
werid inspriation but ok

**Comment by EmeraldLoc** [comment]
wdym? Tesla's logo looks awesome, and its a T, so something like it could be awesome for this!

**Comment by Bear64DX** [comment]
> wdym? Tesla's logo looks awesome, and its a T, so something like it could be awesome for this!

Tbf emerald ain't wrong, I kinda like the Tesla logo

**Comment by Bear64DX** [comment]
> > > ![Tag Iteration 4](https://private-user-images.githubusercontent.com/86802223/356443777-97e13fac-a51e-47e4-9047-d2ca4d7e0a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzIwNzksIm5iZiI6MTcyMzE3MTc3OSwicGF0aCI6Ii84NjgwMjIyMy8zNTY0NDM3NzctOTdlMTNmYWMtYTUxZS00N2U0LTkwNDctZDJjYTRkN2UwYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAyNDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YTBmN2QwNDc2NGJlNTAxNDJiOTA1MzhhZTUwNmVlNTI4YTRiNGZiNDA0MzczYzcyOWU3OWQ3MDkzNmVmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qoUxw-1PvvgRptqzV9pnLKnKpVSD98942wsiMaaU4PE)
> > 
> > 
> > tesla logo aa- 😭 💀
> 
> That was actually my inspiration, stunned you saw that LOL, it's pretty much a meaner looking Tesla logo

NAH LOL

**Comment by TheMan6900** [comment]
> wdym? Tesla's logo looks awesome, and its a T, so something like it could be awesome for this!

just thought it was a lil random lol

**Comment by Bear64DX** [comment]
> > wdym? Tesla's logo looks awesome, and its a T, so something like it could be awesome for this!
> 
> just thought it was a lil random lol

i mean you're not wrong lol

**Comment by TheMan6900** [comment]
still looks dope though

**Comment by Bear64DX** [comment]
> still looks dope though

fr

**Comment by EmeraldLoc** [comment]
Yea I think I like that. Curious on if I should change the tag logo as well, just because idk how much I like it.

**Comment by TheMan6900** [comment]
> Yea I think I like that. Curious on if I should change the tag logo as well, just because idk how much I like it.

The tag logo is so peak, dont

**Comment by Bear64DX** [comment]
> Yea I think I like that. Curious on if I should change the tag logo as well, just because idk how much I like it.

Nah I'm ALL for a tag logo redesign 🔥

**Comment by TheMan6900** [comment]
the tag logo we have now perfectly demonstrates what you do in tag also

**Comment by Bear64DX** [comment]
For the logo redesign, you should have a Mario chase a Toad. It'd be peak.

**Comment by Bear64DX** [comment]
> the tag logo we have now perfectly demonstrates what you do in tag also

Honestly fair point tbh.

**Comment by Bear64DX** [comment]
> the tag logo we have now perfectly demonstrates what you do in tag also

(Except in Sardines...)

**Comment by TheMan6900** [comment]
> Yea I think I like that. Curious on if I should change the tag logo as well, just because idk how much I like it.

Just make the art better

**Comment by EmeraldLoc** [comment]
> Just make the art better

💥 🤯

**Comment by TheMan6900** [comment]
you know what would be cool, if there was an api element called "difficult" which when applied to a level, would double the currency youd get from it for winning on it, theres also some other stuff you could probably do with it.

**Comment by Bear64DX** [comment]
> you know what would be cool, if there was an api element called "difficult" which when applied to a level, would double the currency youd get from it for winning on it, theres also some other stuff you could probably do with it.

people are gonna set it to 9999999-

**Comment by EmeraldLoc** [comment]
> you know what would be cool, if there was an api element called "difficult" which when applied to a level, would double the currency youd get from it for winning on it, theres also some other stuff you could probably do with it.

What? Ima be honest, that's the dumbest suggestion I've gotten all day.

**Comment by TheMan6900** [comment]
> > you know what would be cool, if there was an api element called "difficult" which when applied to a level, would double the currency youd get from it for winning on it, theres also some other stuff you could probably do with it.
> 
> What? Ima be honest, that's the dumbest suggestion I've gotten all day.

💀

**Comment by Bear64DX** [comment]
> > you know what would be cool, if there was an api element called "difficult" which when applied to a level, would double the currency youd get from it for winning on it, theres also some other stuff you could probably do with it.
> 
> What? Ima be honest, that's the dumbest suggestion I've gotten all day.

LOL

**Comment by TheMan6900** [comment]
wait emerald are you cooking the shop rn?

**Comment by EmeraldLoc** [comment]
no

**Comment by TheMan6900** [comment]
oh yeah it would be cool if there was a daily shop kinda system like this:
![image](https://github.com/user-attachments/assets/aa9df6b6-1c5c-4018-a76d-19fd551715bb)
where it cycles between random items, day by day.

**Comment by TheMan6900** [comment]
> oh yeah it would be cool if there was a daily shop kinda system like this: ![image](https://private-user-images.githubusercontent.com/168046906/356885385-aa9df6b6-1c5c-4018-a76d-19fd551715bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzIxODUsIm5iZiI6MTcyMzY3MTg4NSwicGF0aCI6Ii8xNjgwNDY5MDYvMzU2ODg1Mzg1LWFhOWRmNmI2LTFjNWMtNDAxOC1hNzZkLTE5ZmQ1NTE3MTViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQyMTQ0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTA1YTkxM2Q0NGQzYjU4NTU0OTcyZDllNDZlNDZkNzgxYjFiNGJkOWNkOWQ0MTliNjkxNGVmOTFlMTk2NDU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._dxsvh-aA-vt66eKB0QTmGhP8kRaSAT7F3Lcf8Ofzq0) where it cycles between random items, day by day.

Oh yeah, it would also also be, nice if trails/titles/whatever other reward gets added, gets shown in its icon like this

**Comment by EmeraldLoc** [comment]
It would have to be an open shop, with every item in the shop at once. Wouldn't want to do it any other way, since technically a user can change the clock on their computer, allowing them to access all items, since lua can't communicate with the internet.

**Comment by TheMan6900** [comment]
lua internet communication when agent x!?!?!

**Comment by TheMan6900** [comment]
> Oh yeah, it would also also be, nice if trails/titles/whatever other reward gets added, gets shown in its icon like this

 (still would want this though)

**Comment by EmeraldLoc** [comment]
> (still would want this though)

I hate that asctetic,  would go for something else

> lua internet communication when agent x!?!?!

This could be a heavy security risk if modders could do this. While it could do some cool stuff, it could also be used for malicious intent, like logging all your messages, and isn't really a good idea.

**Comment by Bear64DX** [comment]
> > (still would want this though)
> 
> I hate that asctetic, would go for something else
> 
> > lua internet communication when agent x!?!?!
> 
> This could be a heavy security risk if modders could do this. While it could do some cool stuff, it could also be used for malicious intent, like logging all your messages, and isn't really a good idea.

Not to mention that idk if lua is even capable of doing smth like this (actually it prob is tbh, but idk if coop can)

**Comment by EmeraldLoc** [comment]
Oh internet connectivity could be implemented with relative ease, I could probably make a PR if I really wanted to, I just think its a bad idea.

**Comment by TheMan6900** [comment]
wait

**Comment by Bear64DX** [comment]
> Oh internet connectivity could be implemented with relative ease, I could probably make a PR if I really wanted to, I just think its a bad idea.

Would internet connectivity have to like, manipulate CoopNet or something?

**Comment by TheMan6900** [comment]
what if, internet capabilities were restricted to what you can do within coop's code, so it couldnt be abused for bad stuff

**Comment by EmeraldLoc** [comment]
> Would internet connectivity have to like, manipulate CoopNet or something?

No, it wouldn't be related to coopnet. You'd just add a networking library to lua and call it a day

> what if, internet capabilities were restricted to what you can do within coop's code, so it couldnt be abused for bad stuff

That statement makes 0 sense. Like what, restrict it to only allowing it to check if coop has an update, because other than coopnet that's all it does?

**Comment by Bear64DX** [comment]
> No, it wouldn't be related to coopnet. You'd just add a networking library to lua and call it a day

ok lua's way more cracked than i thought it was 💀

**Comment by TheMan6900** [comment]
I mean like, not able to do external stuff with lua.

**Comment by EmeraldLoc** [comment]
> I mean like, not able to do external stuff with lua

Huh, what does that mean? Are you saying don't allow external networking with Lua, because that's where we already are.

> ok lua's way more cracked than i thought it was 💀

Think of it as python but better

**Comment by Bear64DX** [comment]
> Think of it as python but better

That's a HUUUUGE stretch

**Comment by TheMan6900** [comment]
what I basically trying to get to is that networking stuff would be restrictive to that it couldnt do stuff, that can break a the game, but still versatile enough to do cool stuff with it (coop-specific library, maybe?)

**Comment by EmeraldLoc** [comment]
> what I basically trying to get to is that networking stuff would be restrictive to that it couldnt do stuff, that can break a the game

The only thing I could think of is making Lua only be allowed to read site data, but never write. Nonetheless modders could cause mods to read from sites every frame, which could use up the client's bandwidth and cause them to use more data than anticipated, if for whatever reason lua is deciding to fetch all of wikipedia. Also, networking requests would need to be ran asynchronous, which means lua would need coroutines support, which takes a lot of work to implement.

**Comment by TheMan6900** [comment]
wait hold up here me out

**Comment by TheMan6900** [comment]
Global variables: variables that are stored within the coopnet servers, which is linked between every version of a mod.

**Comment by TheMan6900** [comment]
(think of it as something like a online leaderboard)

**Comment by EmeraldLoc** [comment]
Why? And that costs money to store all that. The only reason I see this ever existing is for update checkers, and that's it

**Comment by TheMan6900** [comment]
> Why? And that costs money to store all that. The only reason I see this ever existing is for update checkers, and that's it

welp

**Comment by Bear64DX** [comment]
> Why? And that costs money to store all that. The only reason I see this ever existing is for update checkers, and that's it

And those were deprecated lol
