### ISSUE TITLE
Timer can become shorter than its supposed to be for some reason

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1061]
dont know why

**Comment by EmeraldLoc** [comment]
What timer? When the round is active, starting in timer, which one?

**Comment by TheMan6900** [comment]
round active

**Comment by EmeraldLoc** [comment]
Are you sure the gamemode timer isn't lower than the default?

**Comment by TheMan6900** [comment]
yep

**Comment by EmeraldLoc** [comment]
Are you hosting the lobby? It could be as simple as that value being desynced

**Comment by TheMan6900** [comment]
I was hosting the lobby

**Comment by TheMan6900** [comment]
> Are you hosting the lobby? It could be as simple as that value being desynced

even if it was desynced (which is might been), I still feel like it can be fixed since the oddball timer was

**Comment by TheMan6900** [comment]
This might be a thing similar to the oddball timer

**Comment by EmeraldLoc** [comment]
I don't know what the heck is happening here
