### ISSUE TITLE
Achievement - A Runner like no other!

### ISSUE THREAD

**Issue by SausRelicsSSJ2** [EmeraldLoc/tag#1062]
Win 400/500 (your choice tbh) times as a Runner.
Reward - Title: Escape Artist

**Comment by Bear64DX** [comment]
> Win 400/500 (your choice tbh) times as a Runner. Reward - Title: Escape Artist

Finally, an actually good achievement!

**Comment by TheMan6900** [comment]
> > Win 400/500 (your choice tbh) times as a Runner. Reward - Title: Escape Artist
> 
> Finally, an actually good achievement!

you saying that dodging for 100 coins isnt a good achievment!!!

**Comment by Bear64DX** [comment]
> you saying that dodging for 100 coins isnt a good achievment!!! 

 Why, would it be?

**Comment by TheMan6900** [comment]
because its a neat challenge

**Comment by Bear64DX** [comment]
> because its a neat challenge

True, but it just feels kinda "ehh" to me since it's not following the objective of Tag. This achievement Saus suggested actually has to do with tag, which is why I really like it.

**Comment by Bear64DX** [comment]
This has since been added @EmeraldLoc
