### ISSUE TITLE
Level - Bowser in the Dark World

### ISSUE THREAD

**Issue by SausRelicsSSJ2** [EmeraldLoc/tag#1064]
Just thought it'd be fun. 
Pipe would be added connecting the start of the level to the end
![Screenshot (408)](https://github.com/user-attachments/assets/520cab4b-b601-4996-b991-c62dd2e5ffd8)

**Comment by Bear64DX** [comment]
Honestly this sounds very cool. Tbh I really don't know what makes this stage "bad". I mean, if something as atrocious as Wiggler's Cave can get in, then I honestly can't see why this can't get in. Yeah I know, it's linear. But it's not as bad as cotmc, and I don't know if that should be the reason why this stage can't make it in. It being linear is one thing, but honestly, if WC can get in, and this can't, then I don't even know what to say. I almost feel like we need a definitive reason as to why WC can get in, but not this.

**Comment by EmeraldLoc** [comment]
Best to give it a try and see how it works. You can make a mod that adds bitdw with a start pipe and end pipe using the api, so you can host 2.4 publicly and give it a shot.

**Comment by Bear64DX** [comment]
> Best to give it a try and see how it works. You can make a mod that adds bitdw with a start pipe and end pipe using the api, so you can host 2.4 publicly and give it a shot.

Or option no. 2; I make a PR and force you to merge it.

**Comment by EmeraldLoc** [comment]
Oh yea activate windows saus :D

Feel like this stage would work really weird. With a high player count, it could be ok, but with a low count, it could get pretty annoying and repetitive. Should give it a go though

Also, before making issues, ensure you haven't already looked at an issue

**Comment by TheMan6900** [comment]
added

**Comment by TheMan6900** [comment]
added

**Comment by EmeraldLoc** [comment]
Added

**Comment by TheMan6900** [comment]
Hey could I add bits?

**Comment by EmeraldLoc** [comment]
That’s too big of a level with too many layers. Bitdw isn’t great by itself, that’ll be worse
