### ISSUE TITLE
Dpad Down exit the character select menu?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1065]
https://github.com/user-attachments/assets/5aeb2cf0-fd59-4fc3-bc1d-ef75ec0bcdde
(me exiting the menu here is just me pressing dpad down)

**Comment by EmeraldLoc** [comment]
Yea? This is a CS setting right?

**Comment by TheMan6900** [comment]
no?

**Comment by EmeraldLoc** [comment]
Dpad Down to exit CS is a setting in character select, you made an issue on it so I added compatibility for it, is that not working as intended?

**Comment by TheMan6900** [comment]
I think

**Comment by EmeraldLoc** [comment]
Ill test it out

**Comment by TheMan6900** [comment]
(this was all on 2.4.1)

**Comment by EmeraldLoc** [comment]
Resolved, also make 2.4.1 issues on the dev repo
