### ISSUE TITLE
New star road level - B2

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1067]
add a deathplane that blocks the lower section of the level, or make the lower section its own map, with the tunnels being blocked
![image](https://github.com/user-attachments/assets/877983ac-838d-4457-92e3-80ebf651018c)

**Comment by Bear64DX** [comment]
wait why do you keep suggesting levels that have already been declined (DDD main area, this level, etc). Also, Idk if the lower area needs to necessarily become its own map, it just kinda sounds unnecessary to me tbh

**Comment by EmeraldLoc** [comment]
> wait why do you keep suggesting levels that have already been declined

I have the same question. DDD main area sure with the block api now, this, just no.
