### ISSUE TITLE
Make the player respawn in a level, instead of getting kicked out of the level in solo (like it is in mutiplayer)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1070]
just feels weird how it doesnt (also causes some bugs)

**Comment by EmeraldLoc** [comment]
> also causes some bugs

What bugs?

Also no, most players aren't waiting in a singular level when waiting for players to join. Being able to run around is a good bit funner.

**Comment by TheMan6900** [comment]
> > also causes some bugs
> 
> What bugs?
> 
> Also no, most players aren't waiting in a singular level when waiting for players to join. Being able to run around is a good bit funner.

me when start menu.

**Comment by TheMan6900** [comment]
also its just a very werid inconsistency since warp nodes are not active while in solo, expect locked doors
