### ISSUE TITLE
Object error

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1074]
![image](https://github.com/user-attachments/assets/01e7452b-10e6-49ec-946d-52458c551dad)

**Comment by EmeraldLoc** [comment]
Not tag related

**Comment by Bear64DX** [comment]
Does this happen in the actual hack itself? Or does it happen when the hack's attached to Tag?

**Comment by TheMan6900** [comment]
attached

**Comment by EmeraldLoc** [comment]
The error is a problem with the romhack, not tag. Tag does nothing with scroll textures.

**Comment by Bear64DX** [comment]
Is there a chance that Tag manipulates the hack? I mean, the error I reported that had to do with pipes in GS don't happen with the hack. It only happened w/ Tag attached
