### ISSUE TITLE
Make losing your hat, nerf the speed you can run at

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1075]
would simply be a fun mechanic, thatd make kleptos (and the other enemies that take your hat) way more threatening. Would also just fit well since losing your hat nerfs the hits you can take in the base game.

**Comment by Bear64DX** [comment]
If this were to get added, maybe there could be a system, where you'd have to wait 3 rounds in order to get your hat back.

**Comment by EmeraldLoc** [comment]
added
