### ISSUE TITLE
Revamped Dialog 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1076]
Dialog from npcs, would appear as a chat bubble, that lingers above there head for sometime, before disappearing. the chat bubble would grow and shrink based on how far away you are from it (just like how nametags do)

![image](https://github.com/user-attachments/assets/2d8abc73-82f4-46be-8539-9e9f22ffb52d)

**Comment by Bear64DX** [comment]
is dialog that necessary 💀

**Comment by TheMan6900** [comment]
> is dialog that necessary 💀

its a cool detail

**Comment by TheMan6900** [comment]
and can probably be implemented much easier than the original system (also more functional)

**Comment by Bear64DX** [comment]
> its a cool detail

I mean you are right, but who's going to read them mid-match when they're either trying to pursue a tagger or chase a runner?

**Comment by Bear64DX** [comment]
Wait, are they automatic or do you have to manually read em?

**Comment by TheMan6900** [comment]
automatically

**Comment by Bear64DX** [comment]
> automatically

oooh ok ok

**Comment by TheMan6900** [comment]
the chat bubble can also be proximity based (which is probably the better option)

**Comment by EmeraldLoc** [comment]
no

**Comment by TheMan6900** [comment]
why?

**Comment by EmeraldLoc** [comment]
It'll obscure a player's view, and be more annoying than useful.

**Comment by Bear64DX** [comment]
> It'll obscure a player's view, and be more annoying than useful.

Plus it also feels kinda unnecessary if I'm being honest

**Comment by TheMan6900** [comment]
make them toggable than?

**Comment by Bear64DX** [comment]
> make them toggable than?

ehhh

**Comment by EmeraldLoc** [comment]
That's just building a feature very little people will use or appreciate, and.the guy building the feature won't even appreciate it.

**Comment by Bear64DX** [comment]
> That's just building a feature very little people will use or appreciate, and.the guy building the feature won't even appreciate it.

Oh hey, while we're talking, why is Auto Hide Hud enabled automatically? I've never met anybody who likes that feature lol

**Comment by TheMan6900** [comment]
I use it.

**Comment by Bear64DX** [comment]
> I use it.

😳

**Comment by EmeraldLoc** [comment]
> why is Auto Hide Hud enabled automatically? I've never met anybody who likes that feature lol

Ive met a lot of people who like the feature, and I myself like it, especially with timers always being visible and being able to open the playerlist to see everything, feels pretty natural in my opinion.

**Comment by Bear64DX** [comment]
> Ive met a lot of people who like the feature, and I myself like it, especially with timers always being visible and being able to open the playerlist to see everything, feels pretty natural in my opinion.

It definitely feels cool, the only problem is that you can't see the timer, which is a huge problem in some gamemodes like Hot Potato.

**Comment by EmeraldLoc** [comment]
> the only problem is that you can't see the timer

You have a setting off. You can always see the timer if you have always show timer on (on by default).

**Comment by Bear64DX** [comment]
Ohhh I see now. The timer just becomes transparent
