### ISSUE TITLE
Add a "!" to the end of the changelog titles

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1078]
This just makes the most sense to be applied to, with its be bold presence and color
![image](https://github.com/user-attachments/assets/b2d0d502-8517-4f85-a439-1a4af87fbbb5)

**Comment by EmeraldLoc** [comment]
no, its a title

**Comment by TheMan6900** [comment]
who cares, about grammar, it just looks cool.

**Comment by EmeraldLoc** [comment]
I heavily disagree

**Comment by TheMan6900** [comment]
> I heavily disagree

🤓

**Comment by Bear64DX** [comment]
> > I heavily disagree
> 
> 🤓

bro is tej tpye of gy hwo dosnt now hwo ot sepll

**Comment by TheMan6900** [comment]
> I heavily disagree

🤓  (revived)

**Comment by EmeraldLoc** [comment]
Image going so low you use a nerd emoji, L
