### ISSUE TITLE
 Random Inconsistency I noticed 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1079]
the "tag" and "freeze tag" helps, end with "Enjoy!" yet every other gamemode, just ends without it.
![image](https://github.com/user-attachments/assets/2c073548-a100-4ee2-ab24-10a65fbe0c83)

**Comment by EmeraldLoc** [comment]
Because every other gamemode you can't enjoy :D

**Comment by TheMan6900** [comment]
so every gamemode expect tag or freeze tag is mid!?
