### ISSUE TITLE
Make collecting 1ups, buff the speed you can run at

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1080]
similar to the hat suggestion, this would simply be a fun mechanic, thatd add a new factor to consider.

**Comment by EmeraldLoc** [comment]
no

**Comment by TheMan6900** [comment]
why?

**Comment by Bear64DX** [comment]
idk why but these suggestions feel like theyre tryna turn tag into a roblox simulator im ngl 💀

**Comment by TheMan6900** [comment]
> idk why but these suggestions feel like theyre tryna turn tag into a roblox simulator im ngl 💀

💀
