### ISSUE TITLE
Bullets get shot the opposite way of where your facing on a pole

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1084]
![image](https://github.com/user-attachments/assets/5b74a807-40e0-42ad-b7c7-54f1b0fd77b3)

**Comment by EmeraldLoc** [comment]
Huh? The bullet is going in the direction Mario's facing? Sure Mario may jump in the direction of his back, but his front is facing a certain dir.

**Comment by TheMan6900** [comment]
makes more sense for the bullet to shoot in the direction mario will jump in
