### ISSUE TITLE
freeze framing over quicksand, kills you

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1086]
and probably lava as well.

**Comment by EmeraldLoc** [comment]
Huh

**Comment by TheMan6900** [comment]
you downwarp, if your above lava or quicksand if your freeze framed

**Comment by EmeraldLoc** [comment]
Freeze framed? Huh?

**Comment by TheMan6900** [comment]
you know, the freeze frame at the end of a match

**Comment by EmeraldLoc** [comment]
Ah, easy fix

**Comment by EmeraldLoc** [comment]
resolved
