### ISSUE TITLE
Add water particle effects to walkable water

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1093]
nice detail.

**Comment by EmeraldLoc** [comment]
It does?

**Comment by TheMan6900** [comment]
https://github.com/user-attachments/assets/a9f76217-5188-4063-b5df-6b134a388772

**Comment by EmeraldLoc** [comment]
Can you try this in a different hack? Try modifying a vanilla level or something

**Comment by TheMan6900** [comment]
Pretty sure this happens on other levels

**Comment by EmeraldLoc** [comment]
Can you try this in a different hack? Try modifying a vanilla level or something

**Comment by TheMan6900** [comment]
Uh you said the exact same thing

**Comment by EmeraldLoc** [comment]
Yes, I did.

**Comment by TheMan6900** [comment]
Well I did, did you try any

**Comment by EmeraldLoc** [comment]
Well nvm then, using the word "pretty" made me think you're assuming something from a prior experience lol, sorry about that. I'll test it later.

**Comment by EmeraldLoc** [comment]
resolved
