### ISSUE TITLE
Reduce stuff like Leaderboard Screens Voting Screens and etc by (probably) 3 seconds

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1094]
I still dont see the need for all of them to take like 6 - 10 seconds each, I feel like players already understand the rankings and other stuff just by looking at it for like 2-3 seconds.

**Comment by EmeraldLoc** [comment]
Check for dupe issues

**Comment by TheMan6900** [comment]
I still really dont understand why it has to be as long as it is.

**Comment by EmeraldLoc** [comment]
Its subjective opinions, and I believe its fine as it is.

**Comment by TheMan6900** [comment]
> Its subjective opinions, and I believe its fine as it is.

well fair.

**Comment by TheMan6900** [comment]
well, I feel like the tranistion from the voting winner to actually playing on the stage, could be shorten, especially for the voting screen I dont need the winner's name to be displayed for like 4 seconds.

**Comment by EmeraldLoc** [comment]
Nah I definitely think the winner screen is good as it is, it allows people to get really mad without the next round starting really fast

**Comment by TheMan6900** [comment]
💀
