### ISSUE TITLE
Tag game finish

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#110]
For some reason on specific gamemodes, theres a chance of the match randomly ending, when someone tags someone else.

**Comment by TheMan6900** [comment]
all gamemodes, actually

**Comment by TheMan6900** [comment]
I just happens randomly when tagging someone else. this most common happens on regular tag, and freeze tag

**Comment by EmeraldLoc** [comment]
You have to have pretty bad internet for that then. You get 0.2 seconds to sync up, which should be plenty of time (remember, "bad" ping is in the ~150 range, and 200 ping is in the 0.2s, which is the failsafe I have)

**Comment by TheMan6900** [comment]
alright
