### ISSUE TITLE
The toggle sound effect gets cut off when unspectating

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1102]
title says it all.

**Comment by EmeraldLoc** [comment]
What toggle sfx?

**Comment by TheMan6900** [comment]
the selection one

**Comment by EmeraldLoc** [comment]
I take it you're in the player menu, and you're spectating, and you set the player's role to say, runner?

**Comment by TheMan6900** [comment]
no, just spectating and unspectating using the pause menu.

**Comment by EmeraldLoc** [comment]
Unfortunately can't resolve this. when a player warps, that cancels all sounds and completely resets stuff, so yea
