### ISSUE TITLE
Star Road Variant - Night-Sky Grounds

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1103]
you know the ending level in star road? yeah its basically that. This would be a special kinda level in that it wouldnt be a selectable level, but a level that has a chance to appear over the normal castle grounds stage. variants in general could also be a special kinda level within the level api.

**Comment by TheMan6900** [comment]
also if variants were to be selectable then heres how Id like them to look like

![image](https://github.com/user-attachments/assets/98628f0e-df4a-4f32-9251-50b1e4cd207b)

**Comment by EmeraldLoc** [comment]
Make an issue on level variants instead
