### ISSUE TITLE
Unsupported romhack message revamp

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1109]
would work and look very similar to the welcome text, saying that the this hack is unsupported and with an option to continue as normal or to redirect you to the romhack menu, to see the list of supported hacks.

**Comment by EmeraldLoc** [comment]
If a hack isn't found, the user shouldn't need to go to a romhack menu to confirm the obvious.

**Comment by TheMan6900** [comment]
isnt really obvious what hacks are supported
