### ISSUE TITLE
Make mutiple runners on oddball toggable

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#111]
the name really says it all.

**Comment by EmeraldLoc** [comment]
No. Use the modifier.

**Comment by EmeraldLoc** [comment]
The old gamemode never existed!!11!

**Comment by TheMan6900** [comment]
Adding this would quite literally just be the equivalent to coding the one runner modifier, without it taking up the modifier slot.
Having this be included would take basically no effort, and would just simply be nice.

**Comment by TheMan6900** [comment]
> The old gamemode never existed!!11!

The new gamemode is literally just a glorified tag

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
wait how would this even work?

**Comment by EmeraldLoc** [comment]
... just oddball with multiple runners?

Every player would have a oddball timer, that when they're a runner, goes down. When one of the players timers hit 0, the round ends, and the leaderboard shows.

**Comment by TheMan6900** [comment]
thats literally just tag-

**Comment by TheMan6900** [comment]
thats basically just tag.

**Comment by EmeraldLoc** [comment]
Ok, let's go down the bag of gamemodes pretty much being other gamemodes. The old oddball is pretty much tag with the 1 runner modifier. Hunt is just tags with lives. Hot Potato is just tag with multiple rounds, etc.

**Comment by TheMan6900** [comment]
> The old oddball is pretty much tag with the 1 runner modifier

Why make the gamemode, least designate then?

**Comment by TheMan6900** [comment]
Plus oddballs mechanics, only really work well with the context of it being one player, since with the constant switches, with players and their respective oddball times. The gamemode length varied alot. Something one runner tag couldnt do.

**Comment by TheMan6900** [comment]
Another point being that, having mutiple runners with oddball, really does removes all the skill in it.

**Comment by EmeraldLoc** [comment]
> Something one runner tag couldnt do.
erm ackytully it can

On a more real note, I'll probably end up reverting the change, since your last point reminded me that ties'll be a lot more common if that's added. Need to think about it a bit more. I'll keep the code that made this work though incase you get a dupe runner bug. May as well make the code work :).

Also, ik it doesn't really matter, but I just have to say, you're the one who suggested this lol.

**Comment by TheMan6900** [comment]
lel

**Comment by TheMan6900** [comment]
> it goes in a beta test

HOST THE BETA TEST!!!
