### ISSUE TITLE
If a setting (like water or hazards) is overridden, have it's option greyed/disabled

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1114]
Would simply make sense, and would relieve some confusion on why a level isnt watering. (this would also just simply be a little tag next to an option saying that its forced on or off for a level)

**Comment by EmeraldLoc** [comment]
No because it still applies to other levels

**Comment by TheMan6900** [comment]
wdym?

**Comment by EmeraldLoc** [comment]
Just because one level has it on doesn't mean the user should be restricted from editing other levels that don't have an override. It could be misleading.

**Comment by TheMan6900** [comment]
oh

**Comment by TheMan6900** [comment]
well I still feel like itd be nice to have a thing somewhere, saying if a certain setting is forced for a level.

**Comment by EmeraldLoc** [comment]
Something like that shouldn't be blatantly obvious in a level, if it is, something else is wrong.
