### ISSUE TITLE
Special Yoshi Behavior

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1116]
If you were to interact with yoshi, youd be granted the special triple jump. Would be a cool "detail" since that what happens when talking to yoshi in the base game.

**Comment by EmeraldLoc** [comment]
No, this was intentionally removed

**Comment by Bear64DX** [comment]
PEAK, but wouldn't this make more sense as a modifier or setting? Like, you unlock the setting by talking to Yoshi, and maybe get an achievement cause why not.

**Comment by Bear64DX** [comment]
> No, this was intentionally removed

worst timing ever 💀

**Comment by EmeraldLoc** [comment]
Not peak. Special triple jump sucks, and usually one troll goes ahead and unlocks it, and then it applies for everyone because of a coop bug, then you have to rehost to fix it. Its a clown show and is terrible, would be better as a modifier if anything.

**Comment by Bear64DX** [comment]
> Not peak. Special triple jump sucks, and usually one troll goes ahead and unlocks it, and then it applies for everyone because of a coop bug, then you have to rehost to fix it. Its a clown show and is terrible, would be better as a modifier if anything.

Ohh.... honestly I'm fine with it as a modifier.

**Comment by TheMan6900** [comment]
should I suggest it as a modifier?

**Comment by Bear64DX** [comment]
> Not peak. Special triple jump sucks, and usually one troll goes ahead and unlocks it, and then it applies for everyone because of a coop bug, then you have to rehost to fix it. Its a clown show and is terrible, would be better as a modifier if anything.

Wait, couldn't it just be the idea I suggested, but the bug was fixed on Coop's end? I mean, if the Special Triple Jump sucks, so it's the player's fault for picking it. I think the idea I suggested could be cool, but the bug would have to get fixed on Coop's end. Maybe im just yapping idk
