### ISSUE TITLE
water overlaps deathplane texture

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1121]
![image](https://github.com/user-attachments/assets/d677f9b4-b8bf-4b30-b8fe-1e1e9bd5e0f8)

**Comment by EmeraldLoc** [comment]
How is this a bug...

**Comment by TheMan6900** [comment]
it makes it sorta unclear, that the deathplane is even there

**Comment by TheMan6900** [comment]
also the deathplane is above the water in that picture, if thats what your confused about

**Comment by EmeraldLoc** [comment]
> also the deathplane is above the water in that picture, if thats what your confused about

Above, or equal?

**Comment by TheMan6900** [comment]
above

**Comment by EmeraldLoc** [comment]
Well reopening the issue is pretty redundant. Due to sm64's rendering, a transparent surface on water does not appear as expected, can't really do anything to fix this.
