### ISSUE TITLE
Surface Particles emit from a player if they double jump over a surface that emits... particles

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1123]
![image](https://github.com/user-attachments/assets/4584e147-bf27-4e61-8fcf-6e598eb61b5d)

**Comment by EmeraldLoc** [comment]
Can’t fix this because that’s the nature of the double jump action, also this is such a small detail like really

**Comment by TheMan6900** [comment]
A bug is a bug so.
