### ISSUE TITLE
Just make dying/leaving a level, make you respawn in the level (solo)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1124]
Its really inconsistent, with it spawning you in random places and even deathplanes/hazards, and just straight up doesnt work some times. Also the start menu exist which basically does its role soooooooo.

**Comment by TheMan6900** [comment]
(also some warps straight up do not work)

**Comment by TheMan6900** [comment]
this actually softlocked me like 3 times (both within solo and in the waiting state that proceeds every round)

**Comment by EmeraldLoc** [comment]
That's not a tag problem, that's a romhack problem

**Comment by TheMan6900** [comment]
ok???

**Comment by TheMan6900** [comment]
Could I try "implementing" this? This thing just really gets on my nerves when doing romhack stuff (and also normal tag stuff)
