### ISSUE TITLE
Shells spawn while dropping into a level, if you spam a level in the menu

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1126]
weird bug.

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
The "Ya" and "Wo" sounds effects are mario spawning in a shell, while dropping into the level



https://github.com/user-attachments/assets/ce0604f1-e16f-4eda-bfe5-4aefc99db444

**Comment by EmeraldLoc** [comment]
Is this just the sound it makes?

**Comment by TheMan6900** [comment]
no it also spawns the shell

**Comment by EmeraldLoc** [comment]
With the shell modifier on or? Is the shell visible when this happens?

**Comment by TheMan6900** [comment]
with the shell modifier yes, and the shell is visible

**Comment by EmeraldLoc** [comment]
Is the shell usable, or does it sit there?

**Comment by TheMan6900** [comment]
its usable immediately, it just spawns you and forces you on it, like it normally does grounded.

**Comment by EmeraldLoc** [comment]
Oh wait the shell modifiers on, I thought you said it was off, mb lol. Yea ok see the problem here easy fix.

**Comment by EmeraldLoc** [comment]
resolved
