### ISSUE TITLE
Make the double jump animation a single jump animation that spins (exactly like the gp jump from smo)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1127]
would look really cool, could also have a practical use of spiking things like players and objects above it, which would also be dope.

**Comment by TheMan6900** [comment]
(also this does not require any actual animating)

**Comment by EmeraldLoc** [comment]
Nah

**Comment by TheMan6900** [comment]
lame..........

**Comment by TheMan6900** [comment]
fr though, I uppercut/spike move like this would be dope
