### ISSUE TITLE
Fly Hud Bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#113]
Getting eliminated with the fly modifier or any modfier with special text like bomb and blaster, wont have the specatotor hud display while being out.

**Comment by EmeraldLoc** [comment]
...huh? You sure you don't have the hud hidden with X?

**Comment by TheMan6900** [comment]
nope

**Comment by EmeraldLoc** [comment]
> wont have the specatotor hud display while being out

What do you mean by this?

**Comment by TheMan6900** [comment]
You basically cant see any hud elements, like the person your specating's name, the specating thing itself, and the normal tag stuff

**Comment by EmeraldLoc** [comment]
Unable to recreate
