### ISSUE TITLE
Make npcs return from there interacted state, after awhile

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1130]
would just be a neat detail, and would be fun just casually interacting with them multiple times during a match.

**Comment by TheMan6900** [comment]
Can you atleast give a reason on why your shutting down a issue

**Comment by EmeraldLoc** [comment]
You are wanting me to make an npc fade in after you're done interacting with them, they shouldn't even fade out in the first  place, its a janky side effect of using HOOK_ON_DIALOG.

**Comment by TheMan6900** [comment]
oh weird
