### ISSUE TITLE
New modifier - Combat/Smash

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1132]
Uppercut: A + Y
Grab/Tether: B + X
Aerial Spike: B + Z
(all would be bindable)

could probably be more.

Basically smash, but modifier. Would be really cool and fun (also repurposed the double jump suggestion here since I think it works for this modifier better than double jump), youd also recover from knockback after a while of falling.

**Comment by EmeraldLoc** [comment]
A modifier shouldn't really be a whole moveset, which is what this leans towards.
