### ISSUE TITLE
100 coin star cutscene doesnt get cancelled 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1133]
its definitely annoying.

**Comment by TheMan6900** [comment]
Once again, this issue isn't a duplicate of any other issue.

**Comment by EmeraldLoc** [comment]
Oh what the hell stars used to spawn?!?!?!? Nvm then, I've missed the mark twice now lol. Anyways nah it's funny.

**Comment by TheMan6900** [comment]
This also causes some weird bugs.

**Comment by EmeraldLoc** [comment]
What are these bugs?

**Comment by TheMan6900** [comment]
softlocks.

**Comment by EmeraldLoc** [comment]
How would that softlock you? In what instance?

**Comment by TheMan6900** [comment]
Has happened to me like two times, dont really know how it does, but it does indeed do so.

**Comment by TheMan6900** [comment]
also just having something like this, that basically just slows you down, is incredibly annoying (like I said), and basically just screws you over with no fault of your own.

**Comment by EmeraldLoc** [comment]
> also just having something like this, that basically just slows you down, is incredibly annoying (like I said), and basically just screws you over with no fault of your own.

Skill issue loooooooooooooooool

Im too lazy to find a real fix for softlocks, ig ill add the line of code to remove it 😭

**Comment by TheMan6900** [comment]
you should probably open this issue and label it bug

**Comment by EmeraldLoc** [comment]
Yea I shoulda, resolved in local build
