### ISSUE TITLE
Allow death planes to be invisible

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1135]
This would basically just be a big black abyss that covers the map, would help add some clarity to a level's deathplane. Oh yeah this would be a toggle within the deathplane api or its own api.

**Comment by EmeraldLoc** [comment]
What? I could make it so you can remove the texture, do t know what you mean by void

**Comment by TheMan6900** [comment]
Hold up I'll show you what I mean

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/2ce523e2-1054-4e90-9f4f-897e257c419b)
 basically this as a deathplane texture

**Comment by EmeraldLoc** [comment]
Hahah funny Roblox pic. Nah. I’ll have an option to make the death plane invis instead

**Comment by TheMan6900** [comment]
awwwwwwwwwwww, it would be so fitting for some levels though :(

**Comment by TheMan6900** [comment]
> Hahah funny Roblox pic. Nah. I’ll have an option to make the death plane invis instead

Also Im surpirsed on how quickly you picked up that it was from roblox lol

**Comment by EmeraldLoc** [comment]
https://github.com/EmeraldLoc/tag/issues/1030
