### ISSUE TITLE
readd the koopa flag in bob

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1143]
its was fun handstanding with everyone in the server up there

**Comment by EmeraldLoc** [comment]
Can you do this? Just set bob's act to 6

**Comment by TheMan6900** [comment]
> Can you do this? Just set bob's act to 6

if its that simple than do it yourself 💀

**Comment by Bear64DX** [comment]
Wait, isn't BOB's act already set to 6? I could've sworn there was something like that in the code.

**Comment by EmeraldLoc** [comment]
Oh, well maybe you need to set it to 2, but then koopa the quick'll be there

**Comment by Bear64DX** [comment]
> Oh, well maybe you need to set it to 2, but then koopa the quick'll be there

I mean on the bright side, the slider theme is a fitting tag theme. Plus I assume it's possible to only remove KTQ right? Wait why do they even share the same bhv anyway? Like how does that even work?

**Comment by EmeraldLoc** [comment]
Im a dumbo, setting the act to 6 doesn't respawn the koopa flag, which means the act'll need to be set to 2, welp doesn't hurt. Resolved
