### ISSUE TITLE
weird title bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1149]
![image](https://github.com/user-attachments/assets/86a85fdd-7bd3-4fbb-be6a-7d076adc6fcc)

**Comment by TheMan6900** [comment]
it actually changes the hex code of the elimination message

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
The titles supposed to be white

**Comment by EmeraldLoc** [comment]
ohh I think I know, one second

**Comment by EmeraldLoc** [comment]
Resolved in a local build
