### ISSUE TITLE
mistranslations of hex codes

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1150]
![image](https://github.com/user-attachments/assets/813c449f-900f-48b9-ba28-a4908e59d65b)
(Yann's name)

**Comment by EmeraldLoc** [comment]
Couldn't tell you why, does this only happen with their name?

**Comment by TheMan6900** [comment]
This MIGHT only happen since his name has multiple hexs in it

**Comment by EmeraldLoc** [comment]
That shouldn't be the case

**Comment by TheMan6900** [comment]
Also no that isn't my name lol

**Comment by TheMan6900** [comment]
it might actually have to do with the 1st hex

**Comment by Bear64DX** [comment]
Could it have something to do with their palette color and not their hex? Their hex in the leaderboard isn't even close to their actual hex. There's no yellow in Yann's name.

**Comment by EmeraldLoc** [comment]
I take it this doesn't happen for any of y'all? In my code I can't see why this would happen, it may be something just in 2.4, and I've resolved it in 2.4.1, I'd have to check.

**Comment by EmeraldLoc** [comment]
Also, did this player have a title on? If so, what was the title if you can recall?

**Comment by TheMan6900** [comment]
nope he didnt have a title

**Comment by EmeraldLoc** [comment]
Yea, I don't know what was happening here, Im running `get_player_name` to get the players name, and there's no title, so `title` is an empty string, which in the return value is connected to the string that is returned from `get_player_name_without_title`, which returns the players name first retrieving the player text color string, then the name of the player, don't really see where the problem would be. Can you check in other places in the ui, like the stats menu and see colored names there?

**Comment by TheMan6900** [comment]
check the "1st" color hex, since his name was the exact same hex as the 1st symbol

**Comment by EmeraldLoc** [comment]
Oh yea I see that, that wouldn't be it though, his name literally has the hex stripped out of it for some reason.

**Comment by EmeraldLoc** [comment]
Strip hex is just being ran to check the string's width, which should work as intended, and its starting at the last most index, so this should work fine (and I have seen this work fine, so don't really know the issue there). You can see 0 characters are being removed since his entire name fits in, so this code isn't even being ran.

**Comment by TheMan6900** [comment]
weird...

**Comment by EmeraldLoc** [comment]
Is this the only person this has happened to, or?

**Comment by TheMan6900** [comment]
only the one

**Comment by TheMan6900** [comment]
wait a second he has the beginner title here
![image](https://github.com/user-attachments/assets/86a1f0bf-f3eb-4d4c-a44a-0d970956f2b2)

**Comment by EmeraldLoc** [comment]
Set your name to his (using chat message tab and copying the message) (but change the Yann part), and try to use a different title, or remove the title, and try removing the beginning hex code if neither of those solve the issue.

**Comment by TheMan6900** [comment]
uh how do you copy messages?

**Comment by TheMan6900** [comment]
or use the chat message tab

**Comment by EmeraldLoc** [comment]
Yea just use the chat message tab? You open up chat, and hit tab?

**Comment by TheMan6900** [comment]
oh alright

**Comment by EmeraldLoc** [comment]
Has any progress been made on this?

**Comment by TheMan6900** [comment]
havent found him since.

**Comment by EmeraldLoc** [comment]
Will close for now

**Comment by Bear64DX** [comment]
I got Yann's hex just in case yall wanna mess around.
\#00f\[]!\#fff\Yann\#f00\![]

**Comment by TheMan6900** [comment]
thanks!

**Comment by Bear64DX** [comment]
> thanks!

You're welcome!

**Comment by TheMan6900** [comment]
this could possibly be an issue with the "[]" in his name 
![image](https://github.com/user-attachments/assets/d1b62475-01cf-4221-a0b6-1c94b6b6fa0d)

**Comment by EmeraldLoc** [comment]
I doubt that, can you enter the chat box, hit tab a few times, and copy his name and try to sent it here? (it probably won't send due to unique unicode characters, but many as well try)

**Comment by Bear64DX** [comment]
> I doubt that, can you enter the chat box, hit tab a few times, and copy his name and try to sent it here? (it probably won't send due to unique unicode characters, but many as well try)

Already did.

> I got Yann's hex just in case yall wanna mess around.
#00f[�]!#fff\Yann#f00![�]

**Comment by EmeraldLoc** [comment]
The heck how did I not see that. Thanks

**Comment by EmeraldLoc** [comment]
The issue is 3 letter hex codes dont work properly with lua (it appears), so that'll be the issue. Tell the player to use 6 letter hex codes.

**Comment by TheMan6900** [comment]
> The issue is 3 letter hex codes dont work properly with lua (it appears), so that'll be the issue. Tell the player to use 6 letter hex codes.

Why cant 3 letter hex codes work with lua?

**Comment by TheMan6900** [comment]
uh, this person has no hexs in his name but its still happening?
![image](https://github.com/user-attachments/assets/20de84be-7107-4843-a24d-395b7548e036)
