### ISSUE TITLE
New level - Castle Basement

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1155]
I really dont see anything wrong with these levels.

**Comment by EmeraldLoc** [comment]
I could see the basement working, the main lobby is a no though,

**Comment by TheMan6900** [comment]
whats wrong with the lobby?

**Comment by EmeraldLoc** [comment]
Theres too many rooms and narrow doors to move around in, and generally the level is very small.

**Comment by TheMan6900** [comment]
Emerald, whats the level name for the castle basement (gonna pr it along with some other stuff)

**Comment by EmeraldLoc** [comment]
castle basement. What else would it be lol, thanks.

**Comment by TheMan6900** [comment]
uh it didnt work
![image](https://github.com/user-attachments/assets/a0542c73-4f6f-4d27-9729-c109fa68f354)

**Comment by TheMan6900** [comment]
its supposed to go inbetween these two levels, yet it doesnt show up
![image](https://github.com/user-attachments/assets/a5ecfab8-2620-49f6-a6c7-d4630a4d0d32)

**Comment by EmeraldLoc** [comment]
OH, I thought you meant the level name lol. Yea so its `LEVEL_CASTLE`, with an area of 1, 2, or 3, dont quite remember

**Comment by Bear64DX** [comment]
Area 3

**Comment by Bear64DX** [comment]
Hasn't this been added as well?
