### ISSUE TITLE
make pausing reveal auto hidden ui

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1159]
Would be useful for me and others who prefers using the pause menu for stuff like this.

**Comment by EmeraldLoc** [comment]
Open the playerlist, that's the intended way to do this.

**Comment by TheMan6900** [comment]
whats wrong with making the pause screen do this aswell?

**Comment by TheMan6900** [comment]
Could I add this?

**Comment by EmeraldLoc** [comment]
No this is a really dumb feature

**Comment by TheMan6900** [comment]
I find it way more confrontable to use, since I dont have to lay my thumb of the joystick to press a button.

**Comment by TheMan6900** [comment]
theres also just no reason for the pause menu to not just, reveal the hud automatically (would honestly make more sense than the player menu)

**Comment by EmeraldLoc** [comment]
I disagree with it, not much more to say.

**Comment by Bear64DX** [comment]
Wait what if this was just a toggleable feature?
