### ISSUE TITLE
Double Tag

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#116]
Credit to Bear,

You can tag multiple people with a single kick/punch.

**Comment by EmeraldLoc** [comment]
Can’t really fix this one

**Comment by TheMan6900** [comment]
Just flip a coin with a which player gets chosen to tag

**Comment by EmeraldLoc** [comment]
Better said than done. I already tried to fix this a long time ago, it resulted in an inferior system.

**Comment by TheMan6900** [comment]
what if the player most left got tagged

**Comment by EmeraldLoc** [comment]
Once again, easier said than done. The problem is that the state doesn’t sync quick enough. Adding a cooldown won’t work either.

**Comment by TheMan6900** [comment]
what if, when a double tag happened one out of the 2 people that got tag gets turned back into a runner

**Comment by EmeraldLoc** [comment]
Wow, great idea, wonder how I should detect it, hmmm

The only way I can fix this is by having each pvp attack go thru the server. I did this a long time ago, it caused more lag problems then it solved.

**Comment by TheMan6900** [comment]
wait wasnt a failsafe added that prevented this?

**Comment by EmeraldLoc** [comment]
no?

**Comment by EmeraldLoc** [comment]
Also idk why this is even opened, uh, yea

**Comment by TheMan6900** [comment]
> The only way I can fix this is by having each pvp attack go thru the server. I did this a long time ago, it caused more lag problems then it solved.

I feel like something like this could be implemented well, maybe similar to how payload does lag prevention by stopping server packets if too many of them are sent.

**Comment by EmeraldLoc** [comment]
> payload does lag prevention by stopping server packets if too many of them are sent.

That's not how that works at all... I already implemented this, sure all role desyncs were fixed, however some hits didn't register, others were laggy, and a whole lot of nasty stuff was going on, which is why it was reverted. Also even if I did "stop server packets," what packets am I stopping? Im gonna cause more lag by intentionally lagging the server.

**Comment by TheMan6900** [comment]
> > payload does lag prevention by stopping server packets if too many of them are sent.
> 
> That's not how that works at all... I already implemented this, sure all role desyncs were fixed, however some hits didn't register, others were laggy, and a whole lot of nasty stuff was going on, which is why it was reverted. Also even if I did "stop server packets," what packets am I stopping? Im gonna cause more lag by intentionally lagging the server.

cant something like this be fixed on coopdx's part?

**Comment by EmeraldLoc** [comment]
No

**Comment by TheMan6900** [comment]
Is it possible to set a very quick cooldown between tags so you cant double tag?

**Comment by EmeraldLoc** [comment]
a very quick cooldown needs to be quickly synced, so no
