### ISSUE TITLE
tag menu goes off the border

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1160]
![image](https://github.com/user-attachments/assets/a17be873-7df2-4aaf-b6f6-28ea4c60acd5)

**Comment by EmeraldLoc** [comment]
That's not close to enough info. What does that even mean? What entry is he talking about? Is he talking about text leaking?

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/c9b24d28-320b-409c-a435-6a9b88e5fd61)

**Comment by EmeraldLoc** [comment]
So the actual button goes out of the menu? Or the text of the option?

**Comment by EmeraldLoc** [comment]
Is it the entire options panel?

**Comment by TheMan6900** [comment]
pretty sure he means stuff like items in the start menu goes off screen, if you scroll down enough
![image](https://github.com/user-attachments/assets/51336f28-b152-4657-9ab9-3b50debc3456)

**Comment by Bear64DX** [comment]
ew, castle gallery

**Comment by EmeraldLoc** [comment]
Is he running the game in fullscreen or?

**Comment by TheMan6900** [comment]
pretty sure he isnt

**Comment by EmeraldLoc** [comment]
Well then this isn't something that can be fixed. He's running a game at a abnormal aspect ratio.
