### ISSUE TITLE
disable the start menu if a tournament has ended

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1161]
not sure if this breaks anything but if it does than do it.

**Comment by EmeraldLoc** [comment]
What? You should check first

**Comment by TheMan6900** [comment]
pretty sure this does happen so.

**Comment by EmeraldLoc** [comment]
Did you test it?

**Comment by EmeraldLoc** [comment]
The only thing that could happen is the tourney ending next round instead of that round, however tag would react properly and nothing would break (other than a round limit saying -1)

**Comment by TheMan6900** [comment]
I mean, still should be fixed though
