### ISSUE TITLE
"Your Performance" Under leaderboard rankings, on the leaderboard menu

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1164]
![image](https://github.com/user-attachments/assets/e63e65c7-b2d3-4567-8548-8ab447451d71)
this would basically show what your total tags/saves/time was during a match, useful for knowing what your gain was for a match if you didnt win a match and so arent on the leaderboard to see it.

**Comment by EmeraldLoc** [comment]
Unfortunately there isn't room for such a thing, as with high player counts this won't fit.
