### ISSUE TITLE
Make rounds not proceed if an active round is cancelled mid way through with a started level

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1165]
dont make rounds proceed unless the round is fully finished

**Comment by EmeraldLoc** [comment]
What

**Comment by TheMan6900** [comment]
if your on say round 3/5 and you proceed past that round by starting another level, itll proceed to round 4/5 even if that round wasnt finished.

**Comment by EmeraldLoc** [comment]
Oh for tourneys, ok, I see

**Comment by EmeraldLoc** [comment]
Wait huh, this happens? This should not happen, are you sure you aren't reading it wrong?

**Comment by TheMan6900** [comment]
> Wait huh, this happens? This should not happen, are you sure you aren't reading it wrong?

wdym?

**Comment by EmeraldLoc** [comment]
The round is incremented when the leaderboard is shown, not when a round ends

**Comment by TheMan6900** [comment]
oh well thats what I meant then.

**Comment by EmeraldLoc** [comment]
No the round has ended so it should count
