### ISSUE TITLE
highlight the number one player's score yellow on leaderboards

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1170]
would fit the other leaderboards

**Comment by EmeraldLoc** [comment]
huh

**Comment by TheMan6900** [comment]
Make leaderboards scores for 1st place players, yellow like they are for time.

**Comment by TheMan6900** [comment]
also for gamemode leaderboards

**Comment by EmeraldLoc** [comment]
Yellow is meant to represent a perfect score. Instead, if it uses the point system, and the points is greater than the point threshold, I will color the points yellow

**Comment by EmeraldLoc** [comment]
added
