### ISSUE TITLE
Players still appear frozen even if they disconnect

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1171]
a weird bug

**Comment by EmeraldLoc** [comment]
?

**Comment by Bear64DX** [comment]
I think he means if a player gets frozen via Freeze Tag then disconnects, they'll still appear in the server (The model, not the player itself)

**Comment by TheMan6900** [comment]
No I mean the freeze frame effect at the end of a match

**Comment by Bear64DX** [comment]
oh mb

**Comment by EmeraldLoc** [comment]
Yea because timestop, can't resolve this unless I go back to the old system (has its own bugs)

**Comment by Bear64DX** [comment]
why does it feel like timestops always so buggy (look at mh) 😭

**Comment by EmeraldLoc** [comment]
Timestop not removing players that are disconnected isn't a bug, think about it, time is stopped.

**Comment by Bear64DX** [comment]
> Timestop not removing players that are disconnected isn't a bug, think about it, time is stopped.

Fair point, but I'm pretty sure timestop bugged some things in mh, like the object disappearing thing is caused by it iirc
