### ISSUE TITLE
the 50 terminator wins achievement unlocks when you get 10 terminator wins

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1172]
![image](https://github.com/user-attachments/assets/55040c61-27eb-44a3-a29a-70f39929f8ac)
![image](https://github.com/user-attachments/assets/d68c019a-0443-4fd9-a6e2-d80e4696946e)

**Comment by EmeraldLoc** [comment]
resolved in local build

**Comment by EmeraldLoc** [comment]
Accidentally closed this as not planned, mb
