### ISSUE TITLE
Make the juggernaut eliminated when defeated instead of a tagger

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1173]
makes more sense since your killing them.

**Comment by EmeraldLoc** [comment]
I did not see this issue. Huh?

**Comment by TheMan6900** [comment]
You know, the vanish-wing cap state?

**Comment by EmeraldLoc** [comment]
Oh I see, I will not be implementing this because its an absurd amount of work for nearly zero gain, if someone else does sure
