### ISSUE TITLE
Decrease the i-frames given when getting pvp'd 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1178]
isnt really nesscary for them to be as long as they are and kinda just breaks the pace of the game, having to wait for the other's i-frames to run out.

**Comment by Bear64DX** [comment]
I feel like using the revamped I-Frames (vanilla ones) as seen in #533 would be a way better solution, since the vanilla ones are pretty short.

**Comment by EmeraldLoc** [comment]
What bear said
