### ISSUE TITLE
Group exploded players into one propmt

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1179]
"X, X, X, X, Etc, Exploded" instead of just having every individual player have their own message, would be a nice qol, for reading and for removing the clutter.

**Comment by EmeraldLoc** [comment]
First off, doing such would reduce readability, all the names being cramped into a single popup. Secondly, the boom effect would not be as big with a lot of players if it was just one popup, seeing a list of names with multiple audio queues has a little more power to it. so yea.
