### ISSUE TITLE
Keep Sardines

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1181]
Even though it isnt the most tag gamemode, its still a really fun gamemode that should stay (basically everyone agrees with me and the statement lol)

**Comment by EmeraldLoc** [comment]
Will be a separate gamemode. Its really that simple.

**Comment by TheMan6900** [comment]
wdym?

**Comment by EmeraldLoc** [comment]
Haven't we talked about this before? Its going to be a separate gamemode, a separate mod.

**Comment by TheMan6900** [comment]
lame....
