### ISSUE TITLE
Rebalance the gravity modifiers

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1184]
in general honestly.

**Comment by EmeraldLoc** [comment]
This is an intentional dupe issue, really?

**Comment by TheMan6900** [comment]
To be fair, they both really do need rebalanced (or at least high gravity does) they arent really bad but there pretty obsessive with the gravity changes.

**Comment by EmeraldLoc** [comment]
Yea and that's an excuse to waste my time, thanks. This has been discussed many times, and every time Ive come to the same conclusion.
