### ISSUE TITLE
Change 'Tag Options" to "Tag Settings"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1185]
They both mean the same and it removes this annoying inconsistency with these settings.

![image](https://github.com/user-attachments/assets/2239db84-18d1-4bd4-9bfc-5d99a8d996db)

**Comment by EmeraldLoc** [comment]
Its not just settings, its also options like achievements, stats, etc.

**Comment by TheMan6900** [comment]
fair

**Comment by TheMan6900** [comment]
wait why is "Coop Settings" not "Coop Options" it also has stuff that arent just settings.

**Comment by EmeraldLoc** [comment]
Its "Options" my man

**Comment by Bear64DX** [comment]
> Its "Options" my man

I thought it said "Coop Settings"?

**Comment by EmeraldLoc** [comment]
Holy crap what was I on drugs when I sent this??? I thought he was talking about something else and not what it is in Tag. Pardon me TheMan, I'm dead wrong here. Yes it is "Settings" and there should 100% be continuity between the two. Im gonna change it to Tag Settings, as coop already has an option called options. Sorry about that lol, thanks for saying something bear.

**Comment by Bear64DX** [comment]
> Holy crap what was I on drugs when I sent this??? I thought he was talking about something else and not what it is in Tag. Pardon me TheMan, I'm dead wrong here. Yes it is "Settings" and there should 100% be continuity between the two. Im gonna change it to Tag Settings, as coop already has an option called options. Sorry about that lol, thanks for saying something bear.

Ay you're welcome man 👍
