### ISSUE TITLE
Make fly's bullets faster than normal blaster's

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1187]
would make catching people with fly a lot less of a hassle, while having runners, having to keep on there feet more to evade attacks, overall making it funner and more balanced. (also like a 1.5 - 2x speed increase for fly bullets would be good)

**Comment by EmeraldLoc** [comment]
The bullet speed is proportional to Mario's speed, so it really depends on how fast you're going. I suppose I could increase the multiplier.

**Comment by EmeraldLoc** [comment]
done
