### ISSUE TITLE
Make the bonk sound effect for shells more impactful

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1189]
the one shells have right now feel really lame, and doesnt really give much of an impact, as it should

**Comment by TheMan6900** [comment]
uh can you give a reason?

**Comment by EmeraldLoc** [comment]
Do I have to give a reason for somethings that's purely subjective? Like there really isn't a reason. But sure, here ya go:

I don't like it, fine as is

**Comment by TheMan6900** [comment]
I mean, Id like a reason, just kinda makes it confusing on why a issue is close when its kinda objectively a good idea.

**Comment by EmeraldLoc** [comment]
Dang, an objectively good idea, that's something, Im gonna change my opinion now!
