### ISSUE TITLE
Reposition the pipe in dorrie's domain 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1193]
to the circle of coins, make it a lot easier and faster to jump outta the pipe, plus itd look nicer

![image](https://github.com/user-attachments/assets/9ff917e2-a58e-4b8e-ba89-9603a04c93fa)

**Comment by EmeraldLoc** [comment]
> and faster

Huh?

Anyways, I did this so there'd be more room to run around on the platform, I still like it this way.

**Comment by TheMan6900** [comment]
> > and faster
> 
> Huh?
> 
> Anyways, I did this so there'd be more room to run around on the platform, I still like it this way.

Wdym huh, you wouldnt have to reposition yourself so that you won't get spat out of the platform.
