### ISSUE TITLE
Player rankings on leaderboards dont disappear when disconnecting

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1199]
![image](https://github.com/user-attachments/assets/29449677-9715-47ae-9010-b639fae643dc)
 (he left with 1 second)

**Comment by EmeraldLoc** [comment]
Were they disconnecting, or were they disconnected? This should not happen, as a connected check should be ran. What leaderboard in what gamemode?

**Comment by TheMan6900** [comment]
disconnected

**Comment by EmeraldLoc** [comment]
Are you certain there wasn't another player named this/impersonating this player?

**Comment by TheMan6900** [comment]
nope no one was impersonating

**Comment by EmeraldLoc** [comment]
Interesting, and what gamemode?

**Comment by TheMan6900** [comment]
oddball

**Comment by EmeraldLoc** [comment]
Im having many issues believing that you interpreted the issue right, and Ill explain why

Firstly, I have an explicit check for checking if a player is connected when they're added to the runners table, but that's not the main thing

The big problem im having is if this player wasn't connected their name wouldn't exist. I think you made a mistake and thought they were disconnected but they weren't. If this happens again lmk
