### ISSUE TITLE
Achievements 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#12]
Kinda of a werid suggestion but, basically titles would be a kind of achievement(???) system for completing challenges achieving milestones. other players would also see your titles.
exams: 
Starting Out (getting atleast one tag), 
Tagging Intermediate (getting atleast 100 tags) 
Tagging Professor (getting atleast 1000 tags), 
Genocider (eliminating a server 10 or more people as the terminator, timer must be default of lower) 
DOUBLER (tagging 2 people within a span of 1 second)
SAVIOR (saving 10 or more people in a single round of freeze tag, timer must be default of lower)

**Comment by TheMan6900** [comment]
(Oh yeah you would be able to pick any of your gotten titles in a new menu category designated to titles)

**Comment by EmeraldLoc** [comment]
Implemented, closing this
