### ISSUE TITLE
Bowser 2 and Bowser 3 (but cool)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#120]
Credit to Bear,

Bowser 2 would wobble periodically, and bowser 3 would be in its star shape.  bowser 2's lava would also be a death floor.

**Comment by EmeraldLoc** [comment]
Hmm

**Comment by EmeraldLoc** [comment]
Think ill add

**Comment by EmeraldLoc** [comment]
Bowser 2 wasn't working out, did add bowser 3 though
