### ISSUE TITLE
Make the runner role unable to be given (via player menu) in royale, deathmatch, and other modes where everyones a tagger

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1202]
it causes players to not be taggable, nor them being able to tag to get points from others.

**Comment by EmeraldLoc** [comment]
Someone shouldn't be abusing that, if they are you should leave the lobby, however ye will do

**Comment by TheMan6900** [comment]
you shouldnt just chalk up issues to the player not doing the thing that causes the issue.

**Comment by EmeraldLoc** [comment]
I'm not?

**Comment by TheMan6900** [comment]
no just in general

**Comment by EmeraldLoc** [comment]
Well for 99% of issues that is the problem so ya know :evil laugh:
