### ISSUE TITLE
Make the boost/blaster meter the same color as your respective trail

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1204]
would be a cool detail and add more customizability.

**Comment by EmeraldLoc** [comment]
Nah

**Comment by TheMan6900** [comment]
wait I just realize, this would probably require trail code to be rewritten, yeah I can see why you would reject this

**Comment by TheMan6900** [comment]
would actually be cooler if you were able to customize the meter(s) within a setting (probably a theme setting)

**Comment by EmeraldLoc** [comment]
> would actually be cooler if you were able to customize the meter(s) within a setting (probably a theme setting)

If I were to do it this is what I'd do, however I'd first want to rewrite that whole bar thing to conform to your theme.
