### ISSUE TITLE
Slight blink when checking someones stats

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1207]
https://github.com/user-attachments/assets/98dd52a4-cf12-461e-af56-ee71bfa0badb

**Comment by EmeraldLoc** [comment]
Yea this is it loading the stats

**Comment by TheMan6900** [comment]
should at least inform that its loading when checking stats, espically when it takes a while to load them, so it doesnt feel like the game is broken.

**Comment by EmeraldLoc** [comment]
I can agree with this
