### ISSUE TITLE
Give players a different title that isnt tagger when in a gamemode where everybody is one

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1209]
would make more sense since your not actually a tagger like the role. (would possibly be brawler, ffa, killer)

**Comment by EmeraldLoc** [comment]
erm, actually you are a tagger, a tagger tags players, hehehehehehehehehehehe

**Comment by TheMan6900** [comment]
> erm, actually you are a tagger, a tagger tags players, hehehehehehehehehehehe

🤓
