### ISSUE TITLE
Achievement and Reward Messages

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1212]
Similar to the welcome message, this would be a special pop up that would appear when you get your first achievement or reward and would direct you to the achievement or reward menu. Nice for clarity

**Comment by EmeraldLoc** [comment]
I believe the popup is fine enough, especially if the welcome menu is directing you to a help menu (where there should be something on achievements and rewards anyways)

**Comment by TheMan6900** [comment]
ehhhhhhhhhhh, feels better to display a message that informs them about it when its actually relevant to do so.
