### ISSUE TITLE
Make taggers go faster than runners with the speed modifier

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1217]
balance, since boost dont exist with the speed modifier.

**Comment by EmeraldLoc** [comment]
I disagree with this, I believe taggers can tag just fine with the speed modifier.

**Comment by TheMan6900** [comment]
Why don't taggers have boost with speed

**Comment by EmeraldLoc** [comment]
It caused some rather funny bugs, I can give it a go again however
