### ISSUE TITLE
display general setting

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1236]
in the top right conner
![image](https://github.com/user-attachments/assets/7a8bb351-5fc2-45d1-805b-2f06ad3de656)

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
Uh display the setting and if there on or not

**Comment by EmeraldLoc** [comment]
I have a better idea for this

**Comment by TheMan6900** [comment]
what is that idea?
