### ISSUE TITLE
Tag Effects (not a reward for now)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1237]
(ripped) These would be special effects that would display when tagging someone.

**Comment by TheMan6900** [comment]
just having something that adds more impact to tags would be really fun and make tags way more satisfying to do. Like smash bros.

**Comment by EmeraldLoc** [comment]
Hm

**Comment by EmeraldLoc** [comment]
Prob not a good idea, they may become very distracting.

**Comment by TheMan6900** [comment]
how would they become distracting?

**Comment by TheMan6900** [comment]
(oh yeah I forgor to put this in the issue but these would also be toggleable)

**Comment by TheMan6900** [comment]
wait emerald here me out, tag effects but they only appear when doing a major action, like hunting someone in hunt or killing someone in deathmatch or taking the oddball or terminating someone, or even last second tags.
