### ISSUE TITLE
"X Hunted X"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1240]
The tag message for hunt, kill just makes no sense.

**Comment by EmeraldLoc** [comment]
Do you really think that "hunted" makes more sense? Kill is fine here, since the popup doesn't appear on a tag, only when you get rid of all their lives, or kill them.

**Comment by TheMan6900** [comment]
> Do you really think that "hunted" makes more sense?

Grammatically Debatable, In context, Yes

**Comment by EmeraldLoc** [comment]
<img width="341" alt="Screenshot 2024-09-13 at 3 13 20 PM" src="https://github.com/user-attachments/assets/cb5b2f82-9753-45ee-8946-495b517bb8ed">

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/92001be9-6cdd-40d5-8fd9-817b737810d5)
(im pretty sure theres other meanings of the word that mean something more accurate)

**Comment by EmeraldLoc** [comment]
If you can think of something more accurate, then that'll work, but I think kill is gonna be the most accurate. Also that definition proves my point further lol

**Comment by TheMan6900** [comment]
kill in it of itself doesnt really make a lot of sense.

**Comment by EmeraldLoc** [comment]
Ok that message transformed from what it originally was. No that's the wrong word.

**Comment by EmeraldLoc** [comment]
> kill in it of itself doesnt really make a lot of since.

Welp I got nothing. I explained my thought process. If you can think up something better I'll do that, otherwise for now staying as is.

**Comment by TheMan6900** [comment]
Ok there actually is a meaning of hunted that actually does indeed mean something has been hunted (that sounds stupid but you get what I mean)

**Comment by TheMan6900** [comment]
you can also use "X Hunted down X"
