### ISSUE TITLE
"Reds In The Cave"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1248]
Would be the new name for "Reds In HMC" its just weird having an abbreviation in a level name.

**Comment by Bear64DX** [comment]
> Would be the new name for "Reds In HMC" its just weird having an abbreviation in a level name.

I agree, this would be a sick change.

**Comment by EmeraldLoc** [comment]
I dont really like this name

**Comment by TheMan6900** [comment]
Uh, could we think of a name that isnt Reds in HMC

**Comment by TheMan6900** [comment]
that name simply sounds bad
