### ISSUE TITLE
Make c-up enter you into sniper mode with blasters

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1250]
In this state, youd be able to shoot bullets in whatever direction your head is facing in, basically letting you become a sniper. If you were using freecam, youd be able to enter this state by pressing Udpad. Would be mad fun.

**Comment by EmeraldLoc** [comment]
Nah

**Comment by TheMan6900** [comment]
mannnnnnnnnnnnnnnn.......................
