### ISSUE TITLE
Make the ui appear/disappear instantly when trying to reveal/hide it by using the player menu (should also be the pause menu smh smh)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1252]
In a gamemode as fast and kinetic as tag, its pretty annoying to have to wait for the ui to appear when trying to reveal, which has you have to basically makes your immobile for a few moments.

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
you know the transition from the ui appearing and disappearing, when you reveal it, that.

**Comment by EmeraldLoc** [comment]
The .1 second delay? no
