### ISSUE TITLE
Pipe indictators

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1256]
Pipe radars at the starting phase of the match thatd indicate where pipes are (maybe even springs), would be nice for new players whole dont exactly know the tag "layout" of a stage

**Comment by EmeraldLoc** [comment]
nah

**Comment by TheMan6900** [comment]
why-

**Comment by TheMan6900** [comment]
This would seriously be helpful for some of the hacks im porting.

**Comment by EmeraldLoc** [comment]
I dont believe that showing a pipe indicator for 5 seconds is gonna help anyone out. A player should either figure out where each pipe leads by themselves or the pipes should be placed intuitively. The latter should be done always, so if that's being done theres a very niche place the former happens, and honestly I dont believe a pipe indicator is a good solution, I think they should learn the level instead. Good players who have played for a while are obviously gonna have an advantage, and that should be the case, players shouldn't be babied into knowing where everything is.

**Comment by TheMan6900** [comment]
Its not necessaryly babing players, its more so giving clarity to new players on how levels are layed out (since some of them can be pretty confusing if you dont have prier experience with them)

**Comment by EmeraldLoc** [comment]
> (since some of them can be pretty confusing if you dont have prior experience with them)

Exactly, so you should experience them!

**Comment by TheMan6900** [comment]
> Exactly, so you should experience them!

The point is that players shouldn't have to have prior knowledge to enjoy a level they should just be able to pick up and then play, no issue.
