### ISSUE TITLE
Make the voting tie breaker random instead of the most left option

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1257]
make it more fair.

**Comment by TheMan6900** [comment]
duplicate?

**Comment by Bear64DX** [comment]
I made an issue on this awhile ago, but this really should be added either way (ik theres a reason but still, itd be cool)

**Comment by TheMan6900** [comment]
why wasnt this added? it just seems like a way better system for tie breakers

**Comment by EmeraldLoc** [comment]
I explained it and I stand by it
