### ISSUE TITLE
Tagger Reminder

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1258]
If a tagger aint tagging or is simply just messing around, a message saying that they indeed are a tagger and to start actually tagging people. Nice for the noobs who just bumble when there the terminator or something.

**Comment by EmeraldLoc** [comment]
hm

**Comment by EmeraldLoc** [comment]
This isn't really reasonable to detect, and may discourage players who are simply bad. This isn't reasonably possible, so will close
