### ISSUE TITLE
Add 4th-1st rankings to the voting 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1261]
![image](https://github.com/user-attachments/assets/bde30f01-ede1-4a7b-b61c-f625d7360502)

**Comment by EmeraldLoc** [comment]
What

**Comment by TheMan6900** [comment]
most voted level, 1st. least voted level 4th, and everything in between

**Comment by EmeraldLoc** [comment]
Huh, what are you wanting?

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/245d43e8-da2c-46bf-9ca3-4a84b2516e89)

**Comment by EmeraldLoc** [comment]
I see. Nah just look at how many votes each level has it takes a fraction of a second
