### ISSUE TITLE
Allow blacklisted levels to save

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1262]
would be a nice qol. If you were to go over the limit of 255 blacklisted levels, a popup saying that you can blacklist anymore levels would appear, along with the buzzer sound.

**Comment by TheMan6900** [comment]
(this would only work for supported hacks, also addons)

**Comment by EmeraldLoc** [comment]
As it stands right now, no. Now this may change if I can make a pr that gets merged, however as it stands no.
