### ISSUE TITLE
glitched juggernaut

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1266]
https://github.com/user-attachments/assets/e6a50daa-0663-44f8-850d-906e504cf5d6
pretty sure I was supposed to be a juggernaut this round, but the person who was playing last round left, so it left me in this glitched state where I was a jugger who couldnt double, but could throw bombs

**Comment by EmeraldLoc** [comment]
This isn't technically a glitched state, and is working perfectly as I programmed it, however I made it behave more intuitively

**Comment by TheMan6900** [comment]
Wait did you fix the juggernaut not double jumping this (in general)
