### ISSUE TITLE
New Achievement - Seems you have a lot of work to do!

### ISSUE THREAD

**Issue by SausRelicsSSJ2** [EmeraldLoc/tag#1271]
Enter Spectator Mode as a result of being AFK 20 times
Reward: Title: Pre-Occupied Player

**Comment by EmeraldLoc** [comment]
I dont really want to encourage being afk, which is what this does, so yea

**Comment by Bear64DX** [comment]
> I dont really want to encourage being afk, which is what this does, so yea

Aren't there already a few afk achievements? Like wasn't there one to play Tag for 12 hrs straight or smth?

**Comment by EmeraldLoc** [comment]
That's not a afk achievement, and no there are not

**Comment by Bear64DX** [comment]
> That's not a afk achievement, and no there are not

ah
