### ISSUE TITLE
Make the number next to level names in the pause menu, that level's place in its hack api

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1272]
would make more sense 

![image](https://github.com/user-attachments/assets/ff08acfa-1697-4030-99c5-a19a9db0c7b3)

**Comment by EmeraldLoc** [comment]
I prefer using the course number, I dont really agree with this change

**Comment by TheMan6900** [comment]
It should atleast say what segment of a level it is, if a entry shares a course with another entry.

**Comment by EmeraldLoc** [comment]
That's what the level name is for

**Comment by TheMan6900** [comment]
oh yeah, I forgot 💀
