### ISSUE TITLE
Make the enemy blacklist, list names alphabetically 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1273]
would make searching for a specific enemy easier, and searching in general

**Comment by EmeraldLoc** [comment]
Look again

**Comment by EmeraldLoc** [comment]
Take that back, give me a second

**Comment by EmeraldLoc** [comment]
Added to private build. I forgot I was using `pairs` since I couldn't use `ipairs` with the table I was using, so it appeared to be alphabetically sorted, mb.
