### ISSUE TITLE
Set the default level (where you spawn at when hosting into a hack) the first level entry

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1274]
Nice for hacks that dont have the first hack's actual level supported.

**Comment by EmeraldLoc** [comment]
This should be decided by the actual hack author, also when you are in the waiting for players state, chances are you want to run around into levels, so its good to have that intended hub. Also yes adding a exit course feature is planned for the pause menu if you are in the waiting for players menu
