### ISSUE TITLE
Make the free roam actually work

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1275]
Half the time it just breaks.

**Comment by EmeraldLoc** [comment]
Wow very useful issue, I definitely know what you are talking about!!!!11!!

Ok so what's the issue

**Comment by TheMan6900** [comment]
Warps dont work for some reason

**Comment by TheMan6900** [comment]
Also the spawnlocation api breaks the free roam spawns

**Comment by EmeraldLoc** [comment]
Spawn location is a valid issue, good! Now "Warps dont work for some reason" is completely useless since I dont have an example of one of these warps, the type of warp, and if its an instant warp

**Comment by TheMan6900** [comment]
(also unrelated but I dont think anyone has ever actually used the free roam feature :skull: (atleast the ones I ask) )

**Comment by TheMan6900** [comment]
> Spawn location is a valid issue, good! Now "Warps dont work for some reason" is completely useless since I dont have an example of one of these warps, the type of warp, and if its an instant warp

Pipes warps, Normal warps, Vanish warps.

**Comment by EmeraldLoc** [comment]
Alr I see, I gotcha.

**Comment by Bear64DX** [comment]
> (also unrelated but I dont think anyone has ever actually used the free roam feature 💀 (atleast the ones I ask) )

I use it...

**Comment by EmeraldLoc** [comment]
Got free roam to where I like it now
