### ISSUE TITLE
A way to disable the free roam feature

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1276]
I just find it really annoying. especially for romhack porting

**Comment by EmeraldLoc** [comment]
What's annoying about it?

**Comment by TheMan6900** [comment]
It just booting you outta the level when you die

**Comment by TheMan6900** [comment]
at the very least it shouldnt boot you outta the course when you die.

**Comment by EmeraldLoc** [comment]
Skill issue

**Comment by TheMan6900** [comment]
Why consider this a skill issue? Half the time when Im playing solo, its to practice hard technics and tricks which will probably have me dying.

**Comment by EmeraldLoc** [comment]
When you are in the waiting for players state, I intend that the player can just run around and do whatever they please. The intention is not to lock the player up in one stage. That's the way I want it to be and that's the way I'll make it (although a rather low priority)

**Comment by EmeraldLoc** [comment]
Oh also skill issue

**Comment by EmeraldLoc** [comment]
Oh also dupe

https://github.com/EmeraldLoc/tag/issues/1124

I knew this was something but I forgot what the issue was named, found it though
