### ISSUE TITLE
Free Roam Reminder

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1277]
A transparent message that tells the player that they can roam free until another player joins, no one knows this exist so uh yeah lol.

**Comment by EmeraldLoc** [comment]
They dont know it exists because the name free roam doesn't exist anywhere. The second a player wants to go to whomps, they will be able to.

**Comment by TheMan6900** [comment]
> They dont know it exists because the name free roam doesn't exist anywhere.

Huh?

**Comment by TheMan6900** [comment]
What does that response have to do with anything I said?

**Comment by EmeraldLoc** [comment]
> no one knows this exist

yea because when you say free roam that isn’t what someone thinks about. Now I don’t know what you actually said however based off of what you said here and what you’ve been calling it that’s what I believe you are asking people if they know. Also my main point still stands.

**Comment by TheMan6900** [comment]
> yea because when you say free roam that isn’t what someone thinks about.

No I do explain what that actually is thoroughly.

**Comment by TheMan6900** [comment]
> They dont know it exists because the name free roam doesn't exist anywhere. The second a player wants to go to whomps, they will be able to.

Wait a second, cant you just use the start menu?

**Comment by EmeraldLoc** [comment]
> No I do explain what that actually is thoroughly.

Ok then, disregard what I said above

> Wait a second, cant you just use the start menu?

Yes you can, however this isn't relevant to this issue nor does it warrant a reminder being made
