### ISSUE TITLE
Make naturally eliminated or spectator players not qualify for points once a round ends, if there reinstated to be a runner or a tagger

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1279]
Would be a good way to block out cheaters.

**Comment by EmeraldLoc** [comment]
What

**Comment by TheMan6900** [comment]
Ok so, if a player is a spectator or eliminated without being forced by with the player menu, if said player is forced into being a tagger or runner, theyll not be rewarded with points after the round is over (with tournaments on ofc).

**Comment by EmeraldLoc** [comment]
Why are they being forced in the first place, this is oddly specific

**Comment by TheMan6900** [comment]
> Why are they being forced in the first place, this is oddly specific

Host or moderators being filthy cheaters and making themseleves a runner when they get eliminated.

**Comment by TheMan6900** [comment]
and the poor defenseless little goobers who get forced spectated by the again, filthy cheater host or moderator

**Comment by EmeraldLoc** [comment]
So it's a little bit tricky. The only valid place you'd ever use the player menu is reinstating a player who accidentally disconnected or got disconnected by coopnet. Otherwise, every other use case is cheating (correct me if Im wrong). Doing this would make re-adding a player completely useless, so why not just remove the player menu? It removes a lot of code and a lot of abuse that can be done.

Also won't be able to respond to future messages, will be busy for a bit

**Comment by TheMan6900** [comment]
I mean the disconnection thing can be possibly be prevented by adding a possible protection for newly joined players, being granted the ability to be instated without the no point disadvantage, and also no the player menu should not be removed, it can be used for a lot of good when under the right hands (like fixing desynced players, and for no auto mode set-ups)

**Comment by EmeraldLoc** [comment]
I remember why I added this originally, I should keep that function in, however I'll probably opt for this solution:

Disable the players menu when the round state is active or when auto mode is on. Nice and easy. This was built for auto mode being off, I remember that.

> I mean the disconnection thing can be possibly be prevented by adding a possible protection for newly joined players

Not possible, and really just adding more toppings onto the pizza. The pizza being the problem. That's an analogy I just made up, I like pizza so I dont know why im treating pizza as the bug, but hey it kinda works!

**Comment by TheMan6900** [comment]
> I remember why I added this originally, I should keep that function in, however I'll probably opt for this solution:
> 
> Disable the players menu when the round state is active or when auto mode is on. Nice and easy. This was built for auto mode being off, I remember that.

the only real downside I see for this is not letting desynced players be resynced (though that is a pretty uncommon occurance so itll probably be fine) and not letting late joined players be instated (but late joinning exist for that purpose so I dont really see much of a loss)
