### ISSUE TITLE
Line indicators for the fly modifier

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1280]
Would be right in front of your head while flying, indicating that bullets come from that angle, pretty diffcult to know what direction bullets will go so this would be a nice qol for that, also this could be used for the blaster modifier ig.
![image](https://github.com/user-attachments/assets/81a4d5f3-1d1c-4a28-9947-da2b9ad13162)

**Comment by EmeraldLoc** [comment]
That should be skill based, not told to you
