### ISSUE TITLE
Add sparkles when flying w/ the Fly modifier

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#1281]
It'd look a lot cooler if you sparkled when flying, considering you're in the air most of the time when you fly.

**Comment by EmeraldLoc** [comment]
There's already mist particles when going up, I believe that's good enough imo

**Comment by Bear64DX** [comment]
> There's already mist particles when going up, I believe that's good enough imo

Fr? I never see many particles much
