### ISSUE TITLE
Double jump indicator

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1283]
Would be a little shape above players (or just the players) head that indicates that they have a double jump stored, not only just a nice qol, but would also be nice for notifing players that double jumps are indeed on (since a lot of players, including me dont noticed lol)

**Comment by TheMan6900** [comment]
kinda like this
![image](https://github.com/user-attachments/assets/254eef04-6566-4e7c-860d-89ccedabdd4a)
(also yes I did get inspiration from hitbox.io for this suggestion)

**Comment by EmeraldLoc** [comment]
Nah
