### ISSUE TITLE
Disable the player menu when a round is active, or auto mode is on

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1284]
might as well suggest it here.

**Comment by EmeraldLoc** [comment]
done

**Comment by TheMan6900** [comment]
NO MORE PLAYER MENU CHEATING WOOOOOOO

**Comment by Bear64DX** [comment]
wait what? does this like hide the roles or smth?

**Comment by TheMan6900** [comment]
Basically, if your playing with auto mode on, or in the case you dont have it on, in an active round state, the player menu will be disabled.

**Comment by Bear64DX** [comment]
OHHH, I thought you meant the playerLIST lol
