### ISSUE TITLE
Add walkable water to SL

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1293]
would fix that dumb water hole under the bully, looking ugly as frick.

**Comment by EmeraldLoc** [comment]
I dont know how much I agree with this. Will check out later

**Comment by TheMan6900** [comment]
heres what it looks like (its way deeper than displayed in the image)
![image](https://github.com/user-attachments/assets/ea9ea2cf-9249-47e1-90fd-02530a59eb61)

**Comment by EmeraldLoc** [comment]
Ok Ive added this for the time being, I think it'll be alright
