### ISSUE TITLE
Give the terminator status to someone else (like how oddball and hunt do it) if the previous terminator left the server

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1295]
at the very least at the first half of a round, would stop the annoying ah nub who rages when they get the terminator role.

**Comment by EmeraldLoc** [comment]
I dont really like this

**Comment by TheMan6900** [comment]
What if this only happened with disconnections, due to internet instead of the player willingly disconnecting (yes mariohunt does this, it is possible to do)

**Comment by EmeraldLoc** [comment]
> (yes mariohunt does this, it is possible to do)

And in mariohunt if you hit alt f4 or command Q on macOS the game believes you crashed. Either way wouldn't add this, it isn't fair to the person who won the lottery of not being a terminator
