### ISSUE TITLE
Titles are given out without actually being achieved

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1299]
Not sure if this is the fault of the actual api of the achievements or the system that is used for giving them out but it really should be fixed

![image](https://github.com/user-attachments/assets/85adc6d8-d9a9-47bb-bb08-16dfc745bad0)
![image](https://github.com/user-attachments/assets/a2f599c9-5438-48de-acb2-3f56b62c4861)

**Comment by TheMan6900** [comment]
wdym duplicate?

**Comment by EmeraldLoc** [comment]
https://github.com/EmeraldLoc/tag/issues/799

**Comment by TheMan6900** [comment]
Was the entire problem that this issue suggest, fixed?

**Comment by EmeraldLoc** [comment]
Take a wild guess

**Comment by TheMan6900** [comment]
> Take a wild guess

Debatable :trollface:
