### ISSUE TITLE
Eliminated in hunt!?!?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1304]
![image](https://github.com/user-attachments/assets/ab372c33-e444-41f6-a965-615a503cc703)

**Comment by TheMan6900** [comment]
you accidentally removed the bug label from this issue

**Comment by EmeraldLoc** [comment]
Don’t accidentally, need to look at if this is a bug or not

**Comment by TheMan6900** [comment]
why you cant actually get eliminated in hunt by normal means so.

**Comment by EmeraldLoc** [comment]
It’s a lil more than that, clearly there’s something else at play because that role exists.

**Comment by EmeraldLoc** [comment]
This ones gonna be a desync

**Comment by TheMan6900** [comment]
Why cant you just make it change you into a tagger if you get eliminated or something?
