### ISSUE TITLE
glitched trail texture next to live meter if it goes under 0

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1308]
it only grows the lesser it gets
![image](https://github.com/user-attachments/assets/d08ffda3-de10-47e4-a8ad-58a70b869a93)

**Comment by EmeraldLoc** [comment]
What the heck is going on here. Why do you have less than 0 lives

**Comment by TheMan6900** [comment]
https://github.com/EmeraldLoc/tag/issues/539#issue-2353684955

**Comment by EmeraldLoc** [comment]
2.4.1?

**Comment by TheMan6900** [comment]
no this was in 2.4, its just a bi-product of this bug that I thought was worth mentioning as something to fix

**Comment by EmeraldLoc** [comment]
Ok yea as stated in that issue and the big radar issue, this is also fixed
