### ISSUE TITLE
Slow down the background music with the fog modifier

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1309]
Would just add to the dingy atmosphere of it, plus it be cool listening to the slow down'd songs

**Comment by Bear64DX** [comment]
hmm idk about this ngl, does it fit fog?

**Comment by EmeraldLoc** [comment]
No

**Comment by Bear64DX** [comment]
Sequence functions exist nowadays, this is most likely possible to add.

**Comment by Bear64DX** [comment]
Added
