### ISSUE TITLE
A way to instantly spectate the person closest to you

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1314]
Would be a nice qol, maybe be assigned to the dpad or something.

**Comment by EmeraldLoc** [comment]
I would do this, however there aren't really many binds available

**Comment by TheMan6900** [comment]
You could just use this for the up dpad

**Comment by TheMan6900** [comment]
Would L + Y work?

**Comment by TheMan6900** [comment]
What if this used multiple inputs like L + Y?
