### ISSUE TITLE
Make the spectating camera (player cam) more dynamic in its movement

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1317]
Like the camera automatically moving around to match the terrain and environment to have better view angles.

**Comment by TheMan6900** [comment]
Now thinking about it, this would be a better place to implement this issue, than the place the orginal suggested 
https://github.com/EmeraldLoc/tag/issues/389#issue-2333776850

**Comment by EmeraldLoc** [comment]
I already tried this, see the issue you linked

**Comment by TheMan6900** [comment]
the cam should at least follow the logic that normal sm64 cam uses, where it switches cam styles, depending on where the player is located.
