### ISSUE TITLE
Gamemode Goal Messages

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1326]
Little messages that would display somewhere on the screen, telling what the simple goal of a gamemode is.

**Comment by Bear64DX** [comment]
me when tag help

**Comment by TheMan6900** [comment]
oh yeah I kinda just forgot that existed 💀

**Comment by Bear64DX** [comment]
Is tag help really becoming that forgettable?

**Comment by TheMan6900** [comment]
I just dont use it so yeah

**Comment by Bear64DX** [comment]
Same tbh

**Comment by EmeraldLoc** [comment]
In case you’re wondering, closing issues that I don’t add as not planned so I can keep track of issues easier
