### ISSUE TITLE
Hand states dont transfer into freeze frames

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1335]
![image](https://github.com/user-attachments/assets/1066ada3-b522-40cd-af3a-bf3aadb4e61d)
(this is a twirl btw lol)

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
uh thats a freeze frame?

**Comment by EmeraldLoc** [comment]
Yea it looks fine

**Comment by TheMan6900** [comment]
uh the hands, arent open like there supposed to be

**Comment by EmeraldLoc** [comment]
Oh I wouldn't know you're using a custom model. Yea honestly Im not gonna fix this because it's super small and nobody would really notice it unless you're looking for it. If someone makes a pr, sure, but the code to do it would be ugly, so Id rather not
