### ISSUE TITLE
Tourneys dont count points?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1339]
Won the round in 5th I think place, tagged 2 players and yet, still ended up with zero points at the beginning of the tourney (Im "TheMan" in this ss)
![image](https://github.com/user-attachments/assets/402a658b-dc69-4f07-a1e7-0bde0e64b729)

**Comment by EmeraldLoc** [comment]
Related to another bug I fixed, not gonna bother getting the issue out.
