### ISSUE TITLE
Make high gravity and low gravity not effect cannon springs

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1340]
Basically all of them are not built with there changes in mind (not to mention romhacking)

**Comment by TheMan6900** [comment]
?

**Comment by EmeraldLoc** [comment]
Did you even try to search it?

https://github.com/EmeraldLoc/tag/issues/222

**Comment by TheMan6900** [comment]
I swore it still effected them.

**Comment by TheMan6900** [comment]
(btw when I say cannon springs, I mean the springs that launch you at an angle, with the cannon action)

**Comment by EmeraldLoc** [comment]
Well maybe check for an issue next time and comment on that issue.

 > (btw when I say cannon springs, I mean the springs that launch you at an angle, with the cannon action)
 
 Yea it's the same action, and it's blocked. Not much else to say. Please dont make duplicate issues.
