### ISSUE TITLE
Make dives just instantly spawn a shell when preformed

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1347]
no matter how long its been since you've jumped of a spring, would make them way more reliable for that purpose

**Comment by EmeraldLoc** [comment]
Stop making duplicate issues

Edit: Nvm read that issue wrong, "dive slide" what the heck does that mean lol. Mb

**Comment by EmeraldLoc** [comment]
Either way what I said in that "dive slide" issue applies here

> There’s a cooldown, no
