### ISSUE TITLE
First second of a round doesnt get counted

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1351]
Say, The timer for a round is 120, the 120th second will just be counted down almost instantaneous, basically making the round 119 seconds long.

**Comment by EmeraldLoc** [comment]
No, it's actually 120 seconds. Think about it.

**Comment by TheMan6900** [comment]
Still feels incredibly wrong.

**Comment by EmeraldLoc** [comment]
Dont care what it feels like honestly. If you think about it for more than 10 seconds, you quickly realize it is 120 seconds, so

**Comment by TheMan6900** [comment]
I know what I means, it just doesn't make sense in a weird unexplainable way.
