### ISSUE TITLE
New level - Upper Castle (not including the tower area)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1352]
Don't really see anything wrong with this one.

**Comment by EmeraldLoc** [comment]
too many rooms, and pretty flat movement.

**Comment by Bear64DX** [comment]
I mean, I think it could work. You'd just have to block off the area where you'd enter in from the main area. If this would get added, I'd just combine Castle Tower into this new level.

**Comment by EmeraldLoc** [comment]
> You'd just have to block off the area where you'd enter in from the main area

Assume spiral staircase

> If this would get added, I'd just combine Castle Tower into this new level.

That is correct, nonetheless I think the current level is fine, and the rest of the castle wouldn't add much, and just bit more annoying than anything.

**Comment by Bear64DX** [comment]
> Assume spiral staircase

Correct

Hmm, what about the SL mirror room, THI room, and the main room with the WDW and TTM paintings. Could those work or nah?

**Comment by EmeraldLoc** [comment]
Too small, and once again suffers from a lack of any substance. It's mainly flat rooms with a few walls and maybe at best a tiny bit of deco. The level that already exists is really the only one with any substance.

**Comment by Bear64DX** [comment]
> Too small, and once again suffers from a lack of any substance. It's mainly flat rooms with a few walls and maybe at best a tiny bit of deco. The level that already exists is really the only one with any substance.

I understand.
