### ISSUE TITLE
Two oddballs?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1356]
![image](https://github.com/user-attachments/assets/53e6ccb0-217c-4102-9853-a6900a5c137f)

**Comment by EmeraldLoc** [comment]
It's called a desync, nothing much I can do about it except rob one of the players. Oddball handles multiple taggers fine so this isn't a big deal

**Comment by TheMan6900** [comment]
This should be implemented if you do wanna do single oddball.

**Comment by EmeraldLoc** [comment]
What do you mean, you didn't say anything should be implemented. Are you talking about robbing a player of their oddball spot due to a desync? This has some complications since, remember, its a desync, also, I wouldn't do that anyways, since I believe its unfair.

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/b9b68505-2d64-47fc-9727-ea819403f85b)

**Comment by EmeraldLoc** [comment]
What am I looking at?

**Comment by TheMan6900** [comment]
The oddballer with the winning score doesnt take priority

**Comment by TheMan6900** [comment]
What if the person who had there oddball taken away if there was a dupe was the player with the higher/highest score count (oh yeah this system would not apply if there were 2 or more oddballs applied via player menu) just thought this could be suggested here especially how annoying it is having the desync thing happen and having to manually take away roles, when you just want to do a single oddball match.
