### ISSUE TITLE
Display mutiple oddballers

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1357]
Have the timer hud, display more than one oddballers timer and name if there are more than one oddballer

**Comment by EmeraldLoc** [comment]
Not sufficient room, use sidebar

**Comment by TheMan6900** [comment]
Just cycle through there names, also what do you mean sidebar

**Comment by EmeraldLoc** [comment]
The sidebar on the right. Also I'd want to prioritize the oddball with the best score, which happens already
