### ISSUE TITLE
Resync Option

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1358]
Would resync you by making you a spectator and back to the role you had previously.

**Comment by EmeraldLoc** [comment]
This makes no sense, wdym?

**Comment by TheMan6900** [comment]
Basically this (which is what usually fixes desync) but as something you could do (as a player or host) that you could apply to a player.

https://github.com/user-attachments/assets/b61812e1-5d47-4498-be78-171151727bc9

**Comment by EmeraldLoc** [comment]
that can't be detected

**Comment by TheMan6900** [comment]
wdym?

**Comment by TheMan6900** [comment]
This would be an option the tag menu that you would apply as a host (a human) to a player (or the player)

**Comment by EmeraldLoc** [comment]
Oh I see what you mean. Don't really know how much I like it, won't add
