### ISSUE TITLE
Is the /start command really necessary 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1364]
Like it doesnt really matter to anything, unlike the tag command does
![image](https://github.com/user-attachments/assets/07ed2e17-847e-4473-ac1a-d2a06c697673)

**Comment by EmeraldLoc** [comment]
Was it really necessary to make an issue on a command that doesn't affect you?

**Comment by EmeraldLoc** [comment]
AND this is a duplicate issue, PLEASE check for dupes

**Comment by TheMan6900** [comment]
> Was it really necessary to make an issue on a command that doesn't affect you?

Yes

**Comment by EmeraldLoc** [comment]
Oh wow! Alright, you go do that and waste my time, woohoo!

Only make issues about things that you are affected by, or issues about features you'd like to see, or issues that benefit you as a player. This isn't any of those things. Removing this feature has no effect on what you do. The start command is something I use, and, if you actually looked for a duplicate, you'd know that its faster to run /start coursenum then it is to go into the tag menu, hit start, and find the course.
