### ISSUE TITLE
Make rounds that were skipped using the start menu count the positions that players were in

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1365]
Like placements (rankings), and tag counts, in terms of what amount of points to give them, could even have a little message saying how many points you were awarded with last round.

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
Uh say, you were 1st place in a round with 5 tags to your score, if the host started a new round you would have that 5 points from being 1st and 2.5 points from your tags added to your tourney total, along with a message saying how many points you got

**Comment by EmeraldLoc** [comment]
Oh yea no.
