### ISSUE TITLE
Elimination message when joinning?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1373]
![image](https://github.com/user-attachments/assets/cf9a601a-d3d1-4ccd-a619-1292dc00ffc6)

**Comment by TheMan6900** [comment]
pretty sure the game gave him a role as the round started, tricking the game into thinking he got eliminated???

**Comment by TheMan6900** [comment]
This one was trying to load in I think while the round was starting up and once the round began and he loaded in he was set to eliminated
![image](https://github.com/user-attachments/assets/067c3642-7dd5-4ca6-a30e-2d3e796448b9)

**Comment by EmeraldLoc** [comment]
This could very well be the player logging on at just the right time to get a role that isn’t eliminated, round state is set to active, but the player hasn’t entered the level yet, so the on warp hook is called, triggering them to be eliminated with a popup. Hope that makes sense typing on a phone this sucks lol

**Comment by TheMan6900** [comment]
Im also typing on a phone

**Comment by TheMan6900** [comment]
> This could very well be the player logging on at just the right time to get a role that isn’t eliminated, round state is set to active, but the player hasn’t entered the level yet, so the on warp hook is called, triggering them to be eliminated with a popup. Hope that makes sense typing on a phone this sucks lol

Also is that fixable?

**Comment by EmeraldLoc** [comment]
If that’s what’s happening then no this isn’t really reasonable to fix
