### ISSUE TITLE
Juggernaut bug???

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1376]
As a juggernaut match began, everyone was just set to a tagger...
![image](https://github.com/user-attachments/assets/9745c2a3-89d3-4fa0-b839-9e661defb641)

**Comment by EmeraldLoc** [comment]
The round didn't end instantly?

**Comment by TheMan6900** [comment]
the round did end instantly

**Comment by EmeraldLoc** [comment]
Could've been a round desync, I take it this isn't consistently reproducible, and theres luck involved?

**Comment by TheMan6900** [comment]
> Could've been a round desync, I take it this isn't consistently reproducible, and theres luck involved?

Its probably not consistently reproducible

**Comment by EmeraldLoc** [comment]
Will close then, I do believe Tag handled the occurrence perfectly fine
