### ISSUE TITLE
Make hold Z while preforming a triple jump as a spectator make you preform a regular instead of a winged one

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1380]
A lot of times where Id wanted to preform a normal triple but couldnt since I was spectating

**Comment by Bear64DX** [comment]
What if there was an option that just removed the Wing Cap for spectators?

**Comment by EmeraldLoc** [comment]
I'd do what bear said. See https://github.com/EmeraldLoc/tag/issues/311
