### ISSUE TITLE
New Modifier: Detonator

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#1383]
When you hit someone, you can put a blast tag on them to use for later. If you press X (bindable), everyone you've hit will be launched back by an explosion in the direction you're facing.

**Comment by EmeraldLoc** [comment]
Nah

**Comment by Bear64DX** [comment]
This was a genuinely good modifier 😭 (its alr)

**Comment by TheMan6900** [comment]
Anti-FunLockdown (realllll!!!)

**Comment by Bear64DX** [comment]
> Anti-FunLockdown (realllll!!!)

💀

**Comment by Bear64DX** [comment]
Is there anything wrong with this modifier?
