### ISSUE TITLE
More comfortable flying speed control

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1390]
Basically, if you were to say first be input A to go faster, then while holding A, you start holding B to go slower, B would override A and would make the meter slower, then by releasing B, youd be going back to A's action in vise versa, would make the flying controls feel way more comfortable (hope I made sense).

**Comment by EmeraldLoc** [comment]
Dead honest I have 0 clue how id implement this lol

**Comment by TheMan6900** [comment]
Que system?
