### ISSUE TITLE
New Modifier: Hitman

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#1400]
You'd get a random list of people to tag, and when you tag them you'll get a random buff. These buffs are the following:
- Speed Boost
- Jump Boost
- Strength Boost (And possibly more, I'm running out of ideas)

Oh and also, if the gamemode is Assassins, then you'll claim bounties by killing your targets. And if the gamemode is Killstreak, it'll just pull the list from there.

**Comment by EmeraldLoc** [comment]
Eh
