### ISSUE TITLE
New Map Names

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#141]
All credits to jzzle for these names, this is all recited from him.

volcano level should be named: “Inside of the Volcano”
dire dire docks area 2 def needs to be named: “Bowser’s Submarine Hideout”
Bowser 1 should be named: Bowser’s Dark Domain
he should add bowser 2 and bowser 3 aswell: “Bowser’s Fiery Domain” or “Bowser’s Fire Domain” and “Bowser’s Sky Domain”
reds in hmc should be called “Underground Playground”, “Work Elevator”, “Elevated Cave”, “Underground Work Elevators”
the new dorries domain stage should be called "Dorrie’s Cavern"

**Comment by EmeraldLoc** [comment]
I don't like any of these except the first one.
