### ISSUE TITLE
New modifier - Anti-Gravity

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1410]
Mk8 Anti-Gravity (or mario galaxy)!!! Youd be able to attach and do mario stuff on walls in ceilings, with the camera rotating respectively.

**Comment by EmeraldLoc** [comment]
Unfortunately this is not viable. Viable does not mean impossible btw, however its extremely unrealistic (I believe it would require rewriting every single Mario action)

**Comment by TheMan6900** [comment]
Emerald, could you make the general code for the (the actual sticking to walls and ceilings stuff) and give it to me to fill in the actual action stuff?
