### ISSUE TITLE
New Setting - Invincible Hunters

### ISSUE THREAD

**Issue by SausRelicsSSJ2** [EmeraldLoc/tag#1415]
Title explains everything. Runners cannot cause knock back to hunters. This would be for modes like freeze tag so that runners can’t save a teammate and hit the hunters in 1 swoop. 

(This could also be a modifier and not a setting ur choice tbh)

**Comment by EmeraldLoc** [comment]
Dont know how much I like this, feels like its more of a unfair advantage for a tagger, gonna be a no
