### ISSUE TITLE
Uniquer way of handling opening text boxes

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1431]
When entering a level for the first time, the text box (if it even has one) would display, any time after that it wouldnt (the textbox itself would only be readable for about 10 seconds before it automatically closes itself)

**Comment by Bear64DX** [comment]
Why not just remove them?

**Comment by EmeraldLoc** [comment]
I dont really see a need

**Comment by TheMan6900** [comment]
Just thought the opening text boxes were neat so

**Comment by Bear64DX** [comment]
I mean tbf they do kinda waste time and don't serve much purpose besides that

**Comment by TheMan6900** [comment]
> I mean tbf they do kinda waste time and don't serve much purpose besides that

fair point
