### ISSUE TITLE
Make matches only start if the player that is trying to load into tag is fully loaded in

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1435]
so it doesnt lead to moments like this where the person I have to compete with is still loading in while I basically get to do nothing for the entire round
![image](https://github.com/user-attachments/assets/08874856-3729-412e-b2e9-36cf8a7130b6)

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
the person in the ss is currently loading, thats why they only appear as a radar

**Comment by EmeraldLoc** [comment]
I dont really know what that means. It takes less than a second for a person to load in, unless their internet is terrible or they are desynced. Also, for the round to start, there would need to be more people in order for this to be valid, so what exactly is going on here?

**Comment by TheMan6900** [comment]
I guess there internet is bad (also this is 2p)

**Comment by EmeraldLoc** [comment]
Yea well then they're desynced or their internet sucks, one or the other. They had 15 seconds for their internet to get it together, but they didn't receive the desync packets sent and they couldn't sync their level.
