### ISSUE TITLE
Spectators can use abilities?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1440]
Got auto spectated here sooo.
![image](https://github.com/user-attachments/assets/fd7a4a75-6dbd-40c9-87d6-bf87e0f2edb7)

**Comment by EmeraldLoc** [comment]
This may be due to your round state, I’ll check though

**Comment by EmeraldLoc** [comment]
Yea thats exactly what this is. Harmless and completely fine
