### ISSUE TITLE
New tourney playstyle - Host Dependent

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1441]
Would basically be a tourney where the host decides when it ends, nice for auto mode off type of stuff.

**Comment by EmeraldLoc** [comment]
You made an issue about players abusing things then recommend this? lol, yea nah

**Comment by TheMan6900** [comment]
> You made an issue about players abusing things then recommend this? lol, yea nah

My logic is very broken lol (also I kinda changed my mind on that kinda stuff)
