### ISSUE TITLE
One single trail particle spawns when you spawn into a level (sometimes)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1453]
Strange......

**Comment by EmeraldLoc** [comment]
Who cares, it doesn't matter, nor does it affect anyone

**Comment by TheMan6900** [comment]
I mean it looks ugly.

**Comment by EmeraldLoc** [comment]
Im sorry, you said 1 particle? So, which would you rather me do:

Spend 5 hours rewriting core tag infrastructure for allowing mods to use new libraries
Spend 4 hours making a new gamemode
Spend 1 hour making a new modifier
Spend 5 hours fixing a minor bug that you most likely will never see that's purely cosmetic and only happens for .5 seconds

**Comment by TheMan6900** [comment]
Ok I get your point.

**Comment by TheMan6900** [comment]
didnt think this bug would take that long to fix (if thats not hyperbole)
