### ISSUE TITLE
Spectator warped when following player to the void

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1456]
it just makes the camera spazz out.

**Comment by EmeraldLoc** [comment]
Can you send a video?

**Comment by TheMan6900** [comment]
(this only happens if the player thats falling off the stage gets eliminated, trying to get footage rn btw)

**Comment by TheMan6900** [comment]
The camera also gets confused if the person whos falling off the stage is a tagger (its unclear in the footage but the slight moment where the camera isnt focusing on anything after this person falls, is focused on no one)

https://github.com/user-attachments/assets/30a9635a-dc8c-4f50-a36e-01c7762a4ab2

**Comment by EmeraldLoc** [comment]
Alright I see the problem

**Comment by TheMan6900** [comment]
That isnt the sole problem, it can also spazz out (like in the description) thats just something that also relates to the problem.

**Comment by TheMan6900** [comment]
Spectating players that are before they actually fall off the map seems to actually cause the camera to spazz out.

https://github.com/user-attachments/assets/9d018958-3cd9-4377-9b8b-1dfcc32e974e

**Comment by EmeraldLoc** [comment]
I see what I observed above, so idk, anyways I resolved that portion
