### ISSUE TITLE
Bullets go through walls

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1458]
This is really annoying and should be fixed.

**Comment by EmeraldLoc** [comment]
You know what's even more annoying than bullets going through walls? Dealing with duplicate issues. Every. Single. Time.

#1099

**Comment by TheMan6900** [comment]
Huh? That issue is relating to oob, not just normal terrain

**Comment by TheMan6900** [comment]
Oh wait nevermind.

**Comment by TheMan6900** [comment]
Whoops, thought the other issue I made about this was solely on bullets going through oob walls
