### ISSUE TITLE
Spectator freecam unlocked while in tag settings

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1459]
itll just make you rise upwards while pressing or holding A.

**Comment by EmeraldLoc** [comment]
First off, who cares? Secondly, yes, indeed, the camera isn't frozen, but what does that matter, is it really a bad thing that you can look around and double check that you aren't gonna get hit while you're customizing settings?

**Comment by TheMan6900** [comment]
OH WAIT NO, Im talking about tag's freecam

https://github.com/user-attachments/assets/01661e56-383f-4771-8f31-38970b70008a

**Comment by EmeraldLoc** [comment]
Ok that makes more sense lol

**Comment by EmeraldLoc** [comment]
Resolved
