### ISSUE TITLE
Desync cannons for everyone

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1468]
So you wouldnt have to wait your turn for a cannon, especially if theres an area that has to be gotten to via a cannon.

**Comment by EmeraldLoc** [comment]
If you think about this for more than 5 seconds, you'll quickly find multiple issues with it.

**Comment by TheMan6900** [comment]
eh, I still think this could work, maybe display other people within cannons as a ghost cannon or something.

**Comment by TheMan6900** [comment]
Have desynced cannons appear as ghost cannons, that display what a player is doing with the cannon there in.
