### ISSUE TITLE
Make ground pounding from a cannon shot make you do a wing cap ground pound instead of a regular one

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1470]
Yes they are in fact different, and would look a lot nicer seeing how your hands are spread out while flung from a cannon.

**Comment by EmeraldLoc** [comment]
not affecting vanilla animations

**Comment by TheMan6900** [comment]
wdym?

**Comment by EmeraldLoc** [comment]
For whatever reason I thought that you could ground pound from a cannon in the original game, however clearly I can't think right now. Added.
