### ISSUE TITLE
Wrong github handle for bear

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1471]
Its "Bear64DX" not "PolarBear32"
![image](https://github.com/user-attachments/assets/debfea12-c749-4ab6-b1a8-d7fca0fd83ff)

**Comment by EmeraldLoc** [comment]
Are you trying to get the issue counter to 300 or something? Anyways, I've already fixed this

**Comment by TheMan6900** [comment]
> Are you trying to get the issue counter to 300 or something? Anyways, I've already fixed this

Kinda lol, also just noticing a lot of problems that should be fixed
