### ISSUE TITLE
Dust doesnt properly freeze frame?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1473]
![image](https://github.com/user-attachments/assets/2b5e775a-d5d8-42d5-ac67-fc677c17af4a)
It just appears in it almost dissipated state, atleast I think thats whats happening here

**Comment by EmeraldLoc** [comment]
Yea, its frozen, is there something confusing about this?

**Comment by TheMan6900** [comment]
I 99% sure that the dust was not in the state its in the picture, when the round freeze framed

**Comment by EmeraldLoc** [comment]
Either way, this is the most nitpicky unnecessary issue that affects absolutely no one
