### ISSUE TITLE
Give sausrelic the romhack porter status in the credit

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1474]
He did indeed help with coords and stuff.

**Comment by EmeraldLoc** [comment]
Please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, for my sanity, check for duplicate issues,

**Comment by EmeraldLoc** [comment]
And stop making issues just for the sake of making issues, and stop intentionally looking for issues, thank you.
