### ISSUE TITLE
Change "Tournament Wins" to "Tournament Victory"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1478]
To make it more consistent with the other stat names

**Comment by EmeraldLoc** [comment]
First of all, if you're gonna give a suggestion like this, you should know the proper grammer. It's not "Tournament Victory," It's "Tournament Victories". And sure, I did do this.

**Comment by TheMan6900** [comment]
> First of all, if you're gonna give a suggestion like this, you should know the proper grammer. It's not "Tournament Victory," It's "Tournament Victories". And sure, I did do this.

It was supposed to be victories but autocorrect gave me a faulty fill-in automatically while I was typing (I do know proper grammar though, im just 90% of the time too lazy to use it)

**Comment by EmeraldLoc** [comment]
> im just 90% of the time, to lazy to use it

Just like how you put a comma that shouldn't exist and use the wrong to, it should be too. Anyways yea autocorrect sucks lol/

**Comment by TheMan6900** [comment]
My semi-habit of using commas in random places is destroying me
