### ISSUE TITLE
Royale lag spike?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1481]
Was playing on "Large Leaf Forest" and with the royale gamemode on (as the title says) and while counting down the game spiked HEAVY and wouldnt even let me move for a good 15 seconds. (also this wasn't exclusive to me because half of the server I was playing with crashed and disconnected)

**Comment by EmeraldLoc** [comment]
Is this easily reproducible by heading to that specific level?

**Comment by TheMan6900** [comment]
Not really, it often happens in the starting state

**Comment by EmeraldLoc** [comment]
Unsure on what the issue is. I have since revamped the entire gamemode, so I dont know if this still occurs in dev. How many players were connected? Has this happened more than once? Does it only happen in that specific level?

**Comment by TheMan6900** [comment]
12 players were connected at the time. Yes this has happened more than once, and no this can happen on any level I believe

**Comment by EmeraldLoc** [comment]
Will close since Royale has been rewritten, but if this pops up again lmk
