### ISSUE TITLE
Visible stars?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1482]
Was just playing on ccm and then it turned to the waiting state and then 
![image](https://github.com/user-attachments/assets/2afb63a2-2350-40d9-b5b7-7d226453e03e)

**Comment by EmeraldLoc** [comment]
Well, for 1 who cares, secondly what other mods were you using? How did the star get here, 100 coin star? Did it just poof into existence?

**Comment by TheMan6900** [comment]
> Well, for 1 who cares, secondly what other mods were you using? How did the star get here, 100 coin star? Did it just poof into existence?

Wasn't using any mods besides tag, and it was probably a 100 coins star coin star.

**Comment by EmeraldLoc** [comment]
Did you collect the coin there? Did the other person who I assume was playing with you then disconnected grab the coin? Did you grab a lot of coins beforehand?

**Comment by TheMan6900** [comment]
eh didnt collect a lot of coins, im guessing someone grabbed the 100 star and then dipped.

**Comment by EmeraldLoc** [comment]
There isn't a whole lot of stuff to go off of, and since 2.4 I've redone a small bit of the behavior removal function, and its related to round state changes, and if this is related to 100c, 100c is gone now so
