### ISSUE TITLE
2.4.1 Bug 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1484]
All I did was join a private server with it and then this lovely message displayed

![image](https://github.com/user-attachments/assets/a401b6ef-b42b-4b31-81ca-533432871c61)

**Comment by EmeraldLoc** [comment]
1. wrong repo.

2. yea that's your custom theme. Welcome to a dev repo. I am already aware of this, the theme saving and loading is being rewritten, and new customization options are yet to be added.

Oh yea and as of right now I wouldn't play 2.4.1 with anyone else unless they are in the dev repo aswell

**Comment by TheMan6900** [comment]
> 1. wrong repo. 2. yea that's your custom theme. Welcome to a dev repo. I am already aware of this, the theme saving and loading is being rewritten, and new customization options are yet to be added..

Was gonna post this on the actual dev repo whoops
