### ISSUE TITLE
Oddball Robbing

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1489]
If a oddballer is about to win and someone steals the oddball from them as there victory is displaying, the game will think the person who stole the oddball is the winner and not the actual person who one

**Comment by EmeraldLoc** [comment]
Yea this is an edge case. It's a bug, but it's a hard bug to actually encounter, and a fix is possible, but ugly and ridiculous to implement, so for that reason I won't be fixing this.

**Comment by TheMan6900** [comment]
How would this be fixed? Not necessarily any reason just curious.

**Comment by EmeraldLoc** [comment]
> How would this be fixed? Not necessarily any reason just curious.

Making those packets custom with date stamps

**Comment by TheMan6900** [comment]
How would it look ugly?
