### ISSUE TITLE
Terminators dont have a passive speed boost?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1492]
Looked in the code and they dont seem to have one, along with them not feeling as fast as juggernauts (which have the same passive speed boost)

**Comment by EmeraldLoc** [comment]
Yea, that's right, why?

**Comment by TheMan6900** [comment]
thought you said they did have one?

**Comment by EmeraldLoc** [comment]
Where did I say that? I dont remember saying that, if I did, then I was wrong, idk 🤷‍♂️

**Comment by TheMan6900** [comment]
I remember you saying and I quote "I gave terminators a 1.15 speed boost"

**Comment by TheMan6900** [comment]
In-game

**Comment by EmeraldLoc** [comment]
Well if I said that I was wrong.. I don't really want such a thing to be added.
