### ISSUE TITLE
Make sandy floors not set all terrain slipperyness to default

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1495]
Makes traversing non-slippery stuff way more annoying then there meant to be, and also cheeses very slippery stuff.

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
You know how the sandy floor modifier makes all the floors the same slipperyness?

**Comment by EmeraldLoc** [comment]
Yes, its sand, so of course it does that?

**Comment by TheMan6900** [comment]
oh..
