### ISSUE TITLE
Make fog more consistent

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1498]
75% of the time it just doesnt work even though it really should, and when it does work the color just doesnt really fit the stage that well

**Comment by EmeraldLoc** [comment]
1. Wdym by “it doesn’t work”?

2. If the fog color is wrong, then the romhack porter should override the fog color

**Comment by TheMan6900** [comment]
75% of the time the fog color just goes to the default

**Comment by EmeraldLoc** [comment]
Yes, it's based off of the skybox, this isn't it not working, it's working as intended. If there is a fog color you don't like, then that should be changed by the romhack porter manually, otherwise let it figure it out automatically.
