### ISSUE TITLE
Overkill life count

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1501]
![image](https://github.com/user-attachments/assets/4a159938-8791-49c5-a814-ffc9f959865c)

**Comment by EmeraldLoc** [comment]
More context is needed. What's the error? Why is the nametags like that?

**Comment by TheMan6900** [comment]
Not really sure why its like that

**Comment by EmeraldLoc** [comment]
I'm assuming you're talking about the live count in like juggernaut, but I believe that's been tweaked in 2.4.1 (I believe).

**Comment by TheMan6900** [comment]
ye

**Comment by EmeraldLoc** [comment]
This should all be fine then now
