### ISSUE TITLE
Level Time Cutoff, along with Level/Modifier/Gamemode Spaz Out

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1503]
I was just playing on bowser's sub and as it approached around 70s, the match for some reason just ended and immediately went to the voting screen where it displayed this message:
![image](https://github.com/user-attachments/assets/0dcef1e1-7a2f-41dd-b798-6a3de6dcfad0)
Then random around 5 seconds later just sent to a level, than another 10 seconds, the game just randomly started having a seizure and randomly alternating levels, modifiers and gamemodes (all of this wasn't by me)
![image](https://github.com/user-attachments/assets/3be0f87e-c6d4-4d64-90c4-bbe49f2b2d48)

**Comment by TheMan6900** [comment]
Update: I'm 99% this wasn't actually tag glitching out and was instead just a hacker whole just decided to join in my server and ruin my day, I can prove by this ss.
![image](https://github.com/user-attachments/assets/b60b7474-0931-42a6-ada3-29725749ae1c)
Gonna keep this open though in case you want to take note of the voting timer.

**Comment by EmeraldLoc** [comment]
Interesting, because the data shown here is not super reliable (due to a potential hacking scandal) I will close this
