### ISSUE TITLE
Input Error?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1504]
![image](https://github.com/user-attachments/assets/42d081d8-f590-439b-9c53-9bc520373b72)
Just happened during the incident after a level switch (the romhack was also set to sm74 I believe)

**Comment by EmeraldLoc** [comment]
`gGlobalSyncTable.tagMaxLives` was nil, which its never set to, so I'm going to assume that this is a syncing bug, but I may be wrong.
