### ISSUE TITLE
Round Counter

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#151]
This would display near the the top right of the screen near the Current Gamemode and modfier things. (If the round tourney playstyle was enabled) It would display a Current Round Count, saying "Current Round: X"

**Comment by EmeraldLoc** [comment]
No room for this

**Comment by TheMan6900** [comment]
what do you mean?

**Comment by TheMan6900** [comment]
You can just, put it at the top of the leaderboard-
