### ISSUE TITLE
Make tourney points be given out on the match leaderboard screen

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1511]
So you can do the good ol' start a match immediately after a round ends trick, without having the points be thrown away (I assume this would be incredibly easy to implement so)

**Comment by EmeraldLoc** [comment]
They are added there, always have been, am I missing something?

**Comment by TheMan6900** [comment]
just tested once, and it didnt work for some reason

**Comment by EmeraldLoc** [comment]
Yea I don't know. It's definitely being added in the leaderboard. This issue doesn't really matter anyways, because you shouldn't start a round instantly anyways.
