### ISSUE TITLE
Make starting a level with auto mode off not teleport you to your chosen level but instead display a message saying that you cant start a level solely with auto mode off

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1512]
The extra clarity would be really nice, since makes it look like the game is broken.

**Comment by EmeraldLoc** [comment]
But you can start a level with auto mode off, heck thats what you're meant to do. Wdym by this?

**Comment by TheMan6900** [comment]
when your solo and start a level (auto mode off) youll just get teleported back to the starting area

**Comment by EmeraldLoc** [comment]
This system has been revamped, by effect fixing this issue
