### ISSUE TITLE
New option - Training 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1514]
Would let you practice the general gameplay of tag while solo: Running, Chasing, Fighting, Etc. Not necessarily the surest on implemented but if I had to give one, I guess have an ai dummy that'd run or chase you or fight you around the stages (would also be nice if you could possibly adjust the difficulty of it like in smash). Would also be nice for porting to see if the stage works well in practice.

**Comment by Bear64DX** [comment]
> Would let you practice the general gameplay of tag while solo: Running, Chasing, Fighting, Etc. Not necessarily the surest on implemented but if I had to give one, I guess have an ai dummy that'd run or chase you or fight you around the stages (would also be nice if you could possibly adjust the difficulty of it like in smash). Would also be nice for porting to see if the stage works well in practice.

I don't think you can spawn in dummy players with lua, but I might be wrong

**Comment by EmeraldLoc** [comment]
Outside the scope, also making a running ai is EXTREMELY hard to make, possible, as it has been done, making a smart one is possible too, but it takes a lot of time
