### ISSUE TITLE
New Feature - Randomized Lobbies

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#1516]
These would be something you could add to your romhack port. Basically you could make a table of all the randomized lobbies you want. You could set the level, area, and spawn (maybe some other bonus stuff like unwantedBhvs for all i know). This would be nice for people who have Auto Mode turned off. Here's an example of what it could look like (Taken from Flood +, system originally coded by birdekek):
![image](https://github.com/user-attachments/assets/3a4b4e92-95d8-4d4e-b019-62a5379ff010)

**Comment by EmeraldLoc** [comment]
You aren't forced to one specific lobby, the whole world is open up to you, so this doesn't work for this mod

**Comment by Bear64DX** [comment]
> You aren't forced to one specific lobby, the whole world is open up to you, so this doesn't work for this mod

Oh yeah I kinda forgot about that 💀
