### ISSUE TITLE
Make the random start option unable to pick the currently active level

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1517]
Just makes sense and removes some annoyance

**Comment by EmeraldLoc** [comment]
This should already be happening, is it not?

**Comment by TheMan6900** [comment]
It occasionally doesn't happen

**Comment by EmeraldLoc** [comment]
Unable to reproduce this, assuming either fixed in 2.4.1 or you're interpreting this wrong. I went to a hack with just 4 levels and was unable to reproduce it, and that's a 1/4 chance.
