### ISSUE TITLE
keep runner role/round scores if you rejoin within a short period of being kicked out due to wifi disconnect

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1521]
Pretty self-explanatory, if you have a point score above default, or have the role of a runner, get kicked due to a wifi timeout from the host, and rejoin within a maybe 10 - 20 second time frame, youd keep all of your placement that you had before getting booted. This could also extend to other round related stuff ofc, those are just the main ones that I had at the top of my head.

**Comment by EmeraldLoc** [comment]
Keeping a runner role or any role could easily be abused, however keeping tourney points would be good, as seen in https://github.com/EmeraldLoc/tag/issues/1046

**Comment by TheMan6900** [comment]
I dont really see how this could be abused, seeing that it would only apply if you were to disconnect due to an internet shut off, not something you can just do on your own as a client

**Comment by EmeraldLoc** [comment]
You can't confirm if it was their internet dying or someone using task manager. And then what if someone has bad internet? Well, they got 30 seconds of not needing to be active, but preserving their runner role, so it can feel unfair.
