### ISSUE TITLE
"On Menu"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1523]
If someone were to be on the tag menu a tag menu, a tag above their (above their actual title though if they have one) head saying "On Menu" would appear. Nice for keeping track of moderators and if they're potentially changing any settings.

**Comment by EmeraldLoc** [comment]
Mmm no, there seems to be a common theme of you having bad moderators, you should prob head to your sm64config.txt file and remove all moderators.

**Comment by Bear64DX** [comment]
> Mmm no, there seems to be a common theme of you having bad moderators, you should prob head to your sm64config.txt file and remove all moderators.

💀

**Comment by TheMan6900** [comment]
💀

**Comment by TheMan6900** [comment]
> Mmm no, there seems to be a common theme of you having bad moderators, you should prob head to your sm64config.txt file and remove all moderators.

Wait, why can you just unmoderator people?
