### ISSUE TITLE
Tournament Style: Elimination

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#1524]
Whoever does the worst in a match would be eliminated and permanently set as Spectator for as long as the tournament's duration.
You would be able to adjust how many people get eliminated per match.

**Comment by TheMan6900** [comment]
Not specific to this style or anything, but for these type of booting styles (ones that permanently or temporarily eliminates you), there should be a text saying that your out of commission for a round(s), if you were to be well out of commission.

**Comment by EmeraldLoc** [comment]
I like https://github.com/EmeraldLoc/tag/issues/802 more, these 2 are similar, but I prefer 802, will keep that and not add this
