### ISSUE TITLE
New Level “Black Hole Cave"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#156]
This would be the area in hmc where the black hole (thats what its called) and the borders are.
thank you jzzle for the idea.

**Comment by EmeraldLoc** [comment]
Not happy with that name, level idea's good though

**Comment by EmeraldLoc** [comment]
Added, still need to come up with a better name

**Comment by EmeraldLoc** [comment]
Got a name, dw about it
