### ISSUE TITLE
New star road level "The Castle"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#160]
This would contain every castle area, the sewer, the main floor, and the upstairs.

**Comment by EmeraldLoc** [comment]
No

**Comment by EmeraldLoc** [comment]
I thought this was vanilla, nevermind

**Comment by EmeraldLoc** [comment]
I’d only add the sewer

**Comment by TheMan6900** [comment]
you should just add them all as there own levels

**Comment by EmeraldLoc** [comment]
Sewer has been added. The rest of the castle won't work well so.
