### ISSUE TITLE
New Gamemode: Salmon

### ISSUE THREAD

**Issue by SlingshotMage** [EmeraldLoc/tag#18]
**_Hiding fase_**
At the start of the match, all players are invisible to each other, they have a small amount of time (Same as sardines) to hide an object (Let's say stars) in the level, placed with a button (X?) or after the timer expires if they haven't placed it.

**_Search fase_**
All players reappear and have a limited time to get as many stars as possible, whoever collects the most, or is first to get them all, wins.

_Settings_
-HidingTIme: Duration of each the hiding fase.
-SearchTime: ¯\_(ツ)_/¯.
-WarpOnSearchStart: if enabled, when the Search fase begins, all players are teleported to spawn.

**Comment by EmeraldLoc** [comment]
Neat gamemode idea, however i'm unsure if this matches the tag style, I'll think about it more later

**Comment by EmeraldLoc** [comment]
This is a good gamemode idea, however I don't think it matches the "tag" idea for all the gamemodes. Thanks for the idea though, and it was a good one!

**Comment by TheMan6900** [comment]
I honestly do think this could work if it was reworked and tweaked to be more tag like.
