### ISSUE TITLE
Delete Big Boo

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#180]
Delete the big boo in Gloomy Garden (he spawns right on top of the pipe)

**Comment by EmeraldLoc** [comment]
What boo are you referring to? How do you spawn this boo in?

**Comment by TheMan6900** [comment]
its the boo at the top of the tower

**Comment by EmeraldLoc** [comment]
<img width="1512" alt="Screenshot 2024-05-26 at 8 41 42 PM" src="https://github.com/EmeraldLoc/tag/assets/86802223/510268f8-157e-4191-89cf-78348bdcbf13">
Thats craaazy

**Comment by TheMan6900** [comment]
the fuck !!
