### ISSUE TITLE
Misc Modifier Bugs/Tweaks

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#19]
Shells break cannons (If you enter a cannon, the shell modifier interrupts the cannon animation and softlocks the player)
Makes shells not spawn while on poles
Friendly Fire Modifier doesn't work for Sardines
Change the name of the mod to !Tag! (kinda like how Mariohunt does it)
Make Blacklisted Modifiers and Gamemodes and Gamemode Settings and levels from support romhacks save
Make Terminators AT THE VERY LEAST have modifiers like blaster, double jump, and bombs be exclusive to them (also just give them a speed boost of 1.25 or more... please)
Blaster doesn't do damage for gamemodes with health bars like hunt, and deathmatch.
Make Custom maps (like bitfort, and mcdonalds) show up for unsupported hacks

**Comment by EmeraldLoc** [comment]
Will not change the mod name, the sorting should be fixed on the coop repo. Savings blacklists for game modes and modifiers is good, levels use too much keys, so it’s not viable. Will look into shells and friendly fire modifier,

**Comment by TheMan6900** [comment]
If anything, Terminator really needs to be rebalanced to be more in the terminator's favor, just having the terminator have the exact same utility as a normal tagger doesn't really work well with the whole objective of terminator.

**Comment by EmeraldLoc** [comment]
> Make Custom maps (like bitfort, and mcdonalds) show up for unsupported hacks

Going thru each of these, this happens? Are you sure the mod name was the regular and not the edited !Tag! modname when you tested this?

**Comment by EmeraldLoc** [comment]
Fixed all of these issues, when I close an issue you can still comment on it, so please report about the last bug.
