### ISSUE TITLE
Update General Help

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#190]
Just look at it
![BAD DES](https://github.com/EmeraldLoc/tag/assets/168046906/a4ed31d6-6a94-49ff-a6ae-0b9a2eb836fa)

**Comment by EmeraldLoc** [comment]
Thats text wrapping. It has since been fixed.

**Comment by TheMan6900** [comment]
you also just need to update the general description, like the thing saying 6 gamemodes
