### ISSUE TITLE
Tag - Freeplay Mode

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#196]
Credits to Bear,

This would basically be a mode (maybe in general settings) that would let you (even solo) start any level, without having to play a gamemode or have a timer. Modifiers and Gamemodes would have the tag "Freeplay" over them while in this mode.

**Comment by EmeraldLoc** [comment]
So it's just a level selector? Elaborate a bit more, that doesn't really make sense.

**Comment by TheMan6900** [comment]
yeah its basically is just a level selector

**Comment by EmeraldLoc** [comment]
Lol, yea no.
