### ISSUE TITLE
Sky Resort Softlock

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#197]
The area where you use the vanish cap, without water its impossible to get out

**Comment by EmeraldLoc** [comment]
@Bear64DX Can you cook with this too?

**Comment by Bear64DX** [comment]
Ok I can DEF cook w/ this, Zero Life isn't cooperating w/ me though

**Comment by Bear64DX** [comment]
![image](https://github.com/EmeraldLoc/tag/assets/171458695/67623a48-b090-4b68-93b6-6c83177a9b6e)
