### ISSUE TITLE
New Gamemode - Terminator

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#2]
Basically, there's only one tagger (that being the murderer), The murderers goal is to kill as many players as they can (they'll win regardless of if they tag everyone or not). If the murderer tags someone, the someone is eliminated.

**Comment by EmeraldLoc** [comment]
Would need a better name, however a good gamemode idea.

**Comment by TheMan6900** [comment]
The murderer would have the same speed boost as taggers in fly have, and all special ability's  (Speed, Bomb, Blaster, and Double Jump) would be specific to them only.

**Comment by TheMan6900** [comment]
Some possible names: Killer, Deathrunner, Deathtagger, Eliminater, or Chosen One (I guess)

**Comment by EmeraldLoc** [comment]
If you have a better name throw it here, I think it's a fine name however I'd prefer a less confusing one (deathrunner and deathrun and very similar).

**Comment by TheMan6900** [comment]
would terminator be a good name?

**Comment by EmeraldLoc** [comment]
Done *sigh*
