### ISSUE TITLE
New Setting - Sabotaging

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#20]
Basically, while being eliminated, you would be given a significantly nerfed bomb modifier (maybe like 5 or 6 second cooldown) to be thrown at taggers or runners. You would have to be in mario spectator mode to do this. You would also not be able to do this while finished in sardines.

**Comment by EmeraldLoc** [comment]
I'll have to do somde pondering, as this could lead to targetters, although it isn't a bad suggestion.

**Comment by EmeraldLoc** [comment]
I've decided I won't be adding this
