### ISSUE TITLE
Tag Hitboxes

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#207]
Sometimes you can get hit, even though you weren't supposed to

**Comment by EmeraldLoc** [comment]
Sounds like a coop bug, what do you mean?

**Comment by TheMan6900** [comment]
Ive had many times, where I (person with good internet) hit someone even though I wasnt supposed to (that person I hit always has as good of internet as me so)

**Comment by EmeraldLoc** [comment]
This is just coop behavior, get good
