### ISSUE TITLE
Make pipe entries consistent

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#208]
Make it so no matter if you enter a pipe, from the bottom or the top, itll always spit you out from the top

**Comment by EmeraldLoc** [comment]
Enter a pipe from the bottom??? What??!?

**Comment by TheMan6900** [comment]
yup, this is an actual problem some porters are having believe it or not.

**Comment by EmeraldLoc** [comment]
It always throws you up onto the pipe, not down. Can you show an example of this?

**Comment by TheMan6900** [comment]
It apparently does so with bears port (green stars port) so you should ask him
