### ISSUE TITLE
New Setting (Kinda) - Dynamic Freeze Timer

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#21]
Basically. Selecting a number below 0, would select the freeze tag timer to be dynamic. Dynamic Freeze Timer behaves differently depending on how many players are in the server, less players = more freeze time, more players = less freeze time.

**Comment by TheMan6900** [comment]
(random note but make nametags for the sardine invisible)

**Comment by EmeraldLoc** [comment]
Don't think i'll add this, as I don't see the purpose. Also, if the frozen health drain is == 0 then only runners win, so not frozen players, and the hud for dying of the cold is removed.
