### ISSUE TITLE
New tips

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#216]
These would be new tips that would appear at the bottom of the leaderboard and stuff (just like how tips work now)
"Did you know that you can shoot backward with the blaster modifier, by pressing dpad down then shootings"
"If you're enjoying tag, and haven't downloaded it yet, please consider doing so "

**Comment by EmeraldLoc** [comment]
> "If you're enjoying tag, and haven't downloaded it yet, please consider doing so "

This isn't a project for advertising, the first one's fine though

**Comment by TheMan6900** [comment]
I kinda threw that one in as a joke.

**Comment by EmeraldLoc** [comment]
Done
