### ISSUE TITLE
Cannon Timer

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#219]
While in a cannon a timer would show up, indicating how long you have in the cannon.

**Comment by TheMan6900** [comment]
> I should probably do this.... procrastination....

ONG JUST DO IT !!!!!!!!

**Comment by EmeraldLoc** [comment]
No >:)

**Comment by TheMan6900** [comment]
MY GOD !!

**Comment by TheMan6900** [comment]
D O  I T  N O W ! !

**Comment by EmeraldLoc** [comment]
So impatient. Added
