### ISSUE TITLE
More Misc Tag Bugs/Tweaks

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#22]
Hunt live counts dont apply if your reviving yourself.
Being frozen on or above a quicksand surface makes you sink rapidly into the ground, making it so its impossible to be saved.
Hunt hud overlaps certain hud elements (I forgot to put the thing here, its the fly blaster hud)
Disable sardine's nametag.

**Comment by EmeraldLoc** [comment]
> Disable sardine's nametag.

Can't until v1 comes out

> Hunt hud overlaps certain hud elements still.

What elements?

> Being frozen on or above a quicksand surface makes you sink rapidly into the ground

Of course

> Hunt live counts dont apply if your reviving yourself.

Assuming you mean the player menu

**Comment by TheMan6900** [comment]
Oh yeah, make star doors automatically open like regular doors do, and make it so bombs thrown by you cant hurt you or teammates

**Comment by EmeraldLoc** [comment]
> make star doors automatically open like regular doors do

they do???

> and make it so bombs thrown by you cant hurt you or teammates

Has been done for both blasters and bombs

> if your were to be at 1 life (in jugger, deathmatch, and hunt) you would play the panting animation instead of the normal idle animation, when idle

Neat idea, could probably get away with it.

**Comment by TheMan6900** [comment]
For some reason star doors just dont work for levels in sm74, (like the temple and the tower of the east and the courtyard)

**Comment by TheMan6900** [comment]
another thing, make it so the oob fail safe can only teleport you to your teammates

**Comment by EmeraldLoc** [comment]
I don't believe this is possible. Also, make seperate issues instead of piling stuff into this one. I'm going to close this ,as I've fixed the majority of the problems outlined here

**Comment by EmeraldLoc** [comment]
> For some reason star doors just dont work for levels in sm74, (like the temple and the tower of the east and the courtyard)

This is due to sm74's custom star door behavior, I don't think I can really do anything about it.
