### ISSUE TITLE
Make Changing Gamemodes Not Change The Map

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#225]
Pretty self explantory. this would do (what the title says), and would reset the timer.

**Comment by EmeraldLoc** [comment]
No, just start the game in the same map.

**Comment by TheMan6900** [comment]
Why?

**Comment by EmeraldLoc** [comment]
Because I said so >:)

**Comment by TheMan6900** [comment]
Brap mother fucker

**Comment by TheMan6900** [comment]
THIS LITERALLY MAKES THE GAME WORSE !!!!!!!
