### ISSUE TITLE
Tag - Anti-Softlock

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#23]
If you were to be stuck in a diving-slide state with very little movement (lets say about 1-5 velocity) for about 10-20 seconds, you would activate the same fail-safe that happens when you are oob, you could maybe also just be sent back to the start.

**Comment by EmeraldLoc** [comment]
You would be sent back to the start. This is better for another mod, not Tag.

**Comment by EmeraldLoc** [comment]
If it happens with a official romhack, report the spot it's happening in instead.

**Comment by TheMan6900** [comment]
This really should be added especially for unsupported romhacks.
