### ISSUE TITLE
Unlimited Lives

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#230]
Unlimited Lives (to make it so players cant spawn at the first hub which can cause issues)

**Comment by EmeraldLoc** [comment]
?"

**Comment by TheMan6900** [comment]
desync (sometimes)

**Comment by EmeraldLoc** [comment]
Desync is broad, I have a feeling this isn't an actual problem. What's the desync that's occuring?

**Comment by TheMan6900** [comment]
Castle Grounds Desync (also this would just look a bit nicer)
