### ISSUE TITLE
Make Wins by use of the player menu not count to stats

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#238]
I feel like this is pretty obvious.

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
lets say you were eliminated and you revived yourself using the player menu, that wouldnt count to your stats or anything

**Comment by EmeraldLoc** [comment]
You can’t really detect that without it getting ugly. If someone’s doing that, leave their lobby
