### ISSUE TITLE
API - Object Editing

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#24]
Make it so using the api, you can both add and remove from a stage.

**Comment by EmeraldLoc** [comment]
I don't understand, can you explain it a bit more

**Comment by TheMan6900** [comment]
Objects like Enemies, Platforms and Item

**Comment by TheMan6900** [comment]
Example: Removing the blocks, blocking you from going in side the pyramid in koopa canyon

**Comment by EmeraldLoc** [comment]
I don't see why an api would be needed for this, this feels like a separate mod that would just use your currentLevelNum. You have brang something up though in that I should remove the blocks in koopa canyon, which already exists.
