### ISSUE TITLE
New star road stage - Zero Life (let me explain)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#242]
This would be the stage that you'd go to when getting a gameover. This is actually possible to implement. This stage is located in the metal cap stage in a blackbox beneath the actual metal cap stage, which is where its stored. so basically youd have to have this stage in the same index as the mc stage, just with the spawn pos changed so that, you can actually play on it.

**Comment by TheMan6900** [comment]
go into toad tools 64 and look under the map

**Comment by EmeraldLoc** [comment]
Sir…. What. That softwares like 20 years old. Toads tool could very well be tripping. Can you send the location of the exact coordinates where this level is supposedly stored?

**Comment by Bear64DX** [comment]
Okay so I was right and wrong at the same time. (I was right though, it is under the level in the actual SR hack)

**Comment by EmeraldLoc** [comment]
It’s ok, I figured out a way to do this.
