### ISSUE TITLE
New Gamemode - Oddball

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#25]
Kinda like shine theif mixed with juggernuat. The objective of this mode is to stay as a runner for a certain amount of time, without being tag. This mode would not have an actual time limit but instead, would have a time objective, this time objective is the time a player would have to get to, to win (this would obviously be adjustable)

**Comment by EmeraldLoc** [comment]
That's the name!

**Comment by TheMan6900** [comment]
Yippee

**Comment by EmeraldLoc** [comment]
Added
