### ISSUE TITLE
New Gamemode - Seeker

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#26]
Kind of like sardine, but with the roles reversed. There would be one tagger, with the rest being runners. The runners would have to hide, and the tagger would have to seek them, if a tagger finds a runner and tags them, that runner would become a tagger and would also try to find other runners. The goal for the taggers would be to find all the runners, with the runners having to not be caught.

**Comment by EmeraldLoc** [comment]
This sounds like the same thing as Tag.

**Comment by TheMan6900** [comment]
its basically sardines but everyone expect one person is the sardine, there would also be no radar just like sardines

**Comment by EmeraldLoc** [comment]
This is just terminator without a radar
