### ISSUE TITLE
New api - AddedArenaBhv

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#265]
This would let you add both arena objects, Springs and Cannon Springs to help navigate levels. Cannon springs would be able to be angled. example: springs to get up the hill in the center of dorries domain.

**Comment by EmeraldLoc** [comment]
This could be accomplished with the other api example you gave

**Comment by TheMan6900** [comment]
Just add arena objects into the AddedBhv Api

**Comment by TheMan6900** [comment]
Also springs would just be fun
