### ISSUE TITLE
Tag - Tournaments

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#27]
Tournaments would be an entirely different playstyle (Not gamemode), where you would compete against other players, to reach a point threshold to win. You would earn points by winning matches, with gamemodes giving different points amounts, (tag = 2 points, hot potato = 10 points) all being customizable in a new section simply called "Tournament".

You would be able to toggle:
Tournaments
Winning Threshold
Gamemode(s) Point Giveout

**Comment by TheMan6900** [comment]
Not sure if this would be a extension of the normal stats, or something completely on it own.

**Comment by EmeraldLoc** [comment]
Added, it has been added to normal stats.
