### ISSUE TITLE
Packet Optimizations

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#271]
Optimize the number of packets being sent (they cause noticeable amounts of lag from what Ive played)

**Comment by EmeraldLoc** [comment]
That’s extremely broad, please give specific examples.

**Comment by TheMan6900** [comment]
Like the start up period for, any gamemode basicaly

**Comment by EmeraldLoc** [comment]
The starting in timer? While sure it isn’t optimized great, that won’t be the problem with syncing, most mods sync the timer every frame, it’s a bad, but common practice. Generally, syncing problems only occur when you have a bad connection. When I feel like it, I’ll take some time to optimize some of the syncing, nonetheless it isn’t really a problem, and works fine if you have a decent connection,

**Comment by EmeraldLoc** [comment]
Oh, wait, do you mean for lag or packet lag?

**Comment by TheMan6900** [comment]
yeah

**Comment by EmeraldLoc** [comment]
Which one, yeah doesn’t tell me anything

**Comment by TheMan6900** [comment]
(didnt read the question)

**Comment by TheMan6900** [comment]
> The starting in timer? While sure it isn’t optimized great, that won’t be the problem with syncing, most mods sync the timer every frame, it’s a bad, but common practice. Generally, syncing problems only occur when you have a bad connection. When I feel like it, I’ll take some time to optimize some of the syncing, nonetheless it isn’t really a problem, and works fine if you have a decent connection,

though this too should be considered

**Comment by EmeraldLoc** [comment]
You already made an issue on it, gonna reopen that one
