### ISSUE TITLE
Display "X's Stats"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#279]
Display "X's Stats" near the top right of the conner when look at a players stats

**Comment by EmeraldLoc** [comment]
Truthfully I do t see the need. You pressed the players name, you should know who it is. Nonetheless, will add

**Comment by TheMan6900** [comment]
Oh yeah this would also apply to everything else "X's Achievements" and etc.

**Comment by EmeraldLoc** [comment]
Added
