### ISSUE TITLE
Make Throwing Bombs While Holding A Bom-omb Make You Actually Throw The Bom-omb

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#280]
As if you were throwing a modifier bomb. It would also appear as it's actual size as well, further making it look like you actual threw it. This bom-omb would also have the same exact explosion radius as it actually does in the game (which is bigger than the modifier bomb one from what I remember)

**Comment by EmeraldLoc** [comment]
Hmm

**Comment by EmeraldLoc** [comment]
nah
