### ISSUE TITLE
Bomb Squash 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#281]
If you throw a bomb while crushed, youll permeantly be stuck in the crushed state

**Comment by EmeraldLoc** [comment]
Was unable to reproduce. Can you reproduce this in vanilla? Or does TMK affect something with that.

**Comment by TheMan6900** [comment]
https://github.com/EmeraldLoc/tag/assets/168046906/b0f5429c-244b-49a3-b65c-749c46b644ce

**Comment by EmeraldLoc** [comment]
resolved
