### ISSUE TITLE
Ability Number Display

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#300]
Would display over ability cooldowns, showing how long until you can use it again (would count down 0.1 per tenth of a second)

**Comment by EmeraldLoc** [comment]
?

**Comment by EmeraldLoc** [comment]
Oh, you mean like how long until the boost is recharged, or bombs, etc?

**Comment by TheMan6900** [comment]
yeah

**Comment by EmeraldLoc** [comment]
Added
