### ISSUE TITLE
Bomb Explosion

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#309]
For some reason, bombs can randomly indefinitely grow.

**Comment by EmeraldLoc** [comment]
Can you elaborate on that? Is there a way to reproduce it?

**Comment by TheMan6900** [comment]
No, not to my knowledge. Also basically bombs will expand forever, completely taken up the entire screen over a span of time

**Comment by EmeraldLoc** [comment]
Has this happened again, or is it still down to this one occurance?

**Comment by TheMan6900** [comment]
no

**Comment by EmeraldLoc** [comment]
Gonna close this
