### ISSUE TITLE
JRB's Eel Infestation

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#314]
For some reason, I've noticed that there are quite a few eels in JRB. I'm pretty sure UnwantedBHV can deal with this, but I'm not sure (also hi emerald! it's me bear).
![image](https://github.com/EmeraldLoc/tag/assets/171458695/84471c35-4ff9-4d84-bfe4-c6ef971b5943)

**Comment by TheMan6900** [comment]
I forgot about this

**Comment by TheMan6900** [comment]
This is great, now theres two goobers suggesting suggestions that emerald has to both filter and add.

**Comment by EmeraldLoc** [comment]
Ye, that's correct, easily fixable using the unwantedBhvs call.
