### ISSUE TITLE
Death system for Deathmatch

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#315]
So I'm pretty sure you're aware that if you fall off, you'll lose a life. But you won't turn into a tagger or get eliminated once you lose all of your lives. You'll just stay with 1 life (I don't know if this has already been suggested but I think this should be made clear). You'd still lose your lives like normal, rather than just going straight to 1 (Also I think this system is good for hunt as well).

**Comment by EmeraldLoc** [comment]
Done
