### ISSUE TITLE
Final Bowser Arena for Sapphire

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#322]
Basically, this would add the final bowser arena to tag, not the actual bowser level itself. The reason why I'm suggesting this is because Sapphire only has like a puny 4 levels. So if it got some more love, that'd be great. (I could also make this a PR if you want)

**Comment by EmeraldLoc** [comment]
If you want to make prs feel free, it helps me out a ton :)

**Comment by Bear64DX** [comment]
alr, I'll probably get that going either now or once Green Stars gets accepted.
