### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#329]
This would be a, well honestly not really sure what category this would be in. that would change the whole settings ui's aesthetics, from simple color changes to the ones that coopdx has, to completely unique ones exclusive to tag (maybe like one that represents the colors of every gamemode).

**Comment by EmeraldLoc** [comment]
I was already looking at this. If I were to do it I’d do it right, which means it’d change all the hud. The amount of work to build this is incredible, not reasonable for 2.4.

**Comment by Bear64DX** [comment]
I was just thinking of a black or white option, rather than almost every Coop Deluxe theme

**Comment by TheMan6900** [comment]
yeah, exactly

**Comment by TheMan6900** [comment]
> (maybe like one that represents the colors of every gamemode). 

know thinking about this more indepthly really makes me, realize how long this would take

**Comment by EmeraldLoc** [comment]
Theme creation would be free. I have to actually build the system, that’s the only hard part (and it’s a very hard part)

**Comment by EmeraldLoc** [comment]
Added
