### ISSUE TITLE
Oddball with multiple runners

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#33]
In the gamemode setting for oddball there would be a toggle for sharing the oddball timer, basically kinda like mario kart double dashes shine theif.

**Comment by EmeraldLoc** [comment]
? Do you mean an option for multiple players being a runner?

**Comment by TheMan6900** [comment]
yeah kinda

**Comment by EmeraldLoc** [comment]
I'll probably end up making this the default, and having the original one be if the ONE_RUNNER modifier is on. Still have to decide how i'm doing the UI though.

**Comment by EmeraldLoc** [comment]
Added
