### ISSUE TITLE
Game failing to automatically detect Sapphire

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#334]
So basically, if you host a tag server w/ Sapphire on, the game says "Could not detect Romhack", which basically means you have to manually enable it. This is weird because it works perfectly fine with other hacks. Here are some videos showing the error, and other hacks that do not have the error.

Here, Tag doesn't detect Sapphire
https://github.com/EmeraldLoc/tag/assets/171458695/a3fea905-5e37-4bee-ac4f-4ed270a6f300

Here, Tag detects Green Stars perfectly fine.
https://github.com/EmeraldLoc/tag/assets/171458695/5c9197fd-42cc-40f7-ae24-a5ef18b5c728

**Comment by EmeraldLoc** [comment]
The way the detection works is it checks the mod name (it ignores hex so hex doesn't affect the detection system). If the modname you have isn't sm64 sapphire (it's prob sm64 sapphire (v1.1) or whatever they named the mod now), then this bug occurs. I have no better way of detecting the hack, I should allow tag to check multiple mod names for the same hack, however that's functionality I need to add.

**Comment by Bear64DX** [comment]
Hmm, It's 1.1, and it looks like it has hex code. The lua's look like they match up, and the name looks like it's the exact same. I think it's the Hex code that's messing with it

**Comment by Bear64DX** [comment]
Forget what I said, it's named the same but has 1.1 at the end
That may have smth to do with it

**Comment by Bear64DX** [comment]
The lua short names are the same though, maybe I should test this with GS rq

**Comment by EmeraldLoc** [comment]
It doesn't check shortnames so it doesn't matter.

**Comment by Bear64DX** [comment]
Alright, after testing with greenstars I can confidently say that the mod name's 100% the issue. This is a quick fix though, just name Sapphire to Sapphire 1.1. Anyway, that sounds like a good solution.
