### ISSUE TITLE
Rolling Ball Infest

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#335]
For some reason, on bob-omb battlefield, way more rolling balls, spawn than normally

**Comment by EmeraldLoc** [comment]
This may be a coop bug. Is this easily reproducible with only the tag mod?

**Comment by TheMan6900** [comment]
Yeah, it basically happens every time you play on it.

**Comment by EmeraldLoc** [comment]
Definitely a feature!
