### ISSUE TITLE
New gamemode - Laser Tag

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#336]
Credits to SausRelic, all information was recited from his discord.

Laser Tag
how it works is
the level u play on has black fog forced on it
Even more fog than normal
runners glow blue light and taggers glow red
taggers and runners get a blaster
radar is off except every 15 seconds a tagger can see radars for 5 seconds
that’s the mode thoughts?

**Comment by Bear64DX** [comment]
so blaster with fog 2x?

**Comment by TheMan6900** [comment]
Its a more harsh fog effect

**Comment by Bear64DX** [comment]
hmm, I'll wait for emerald to give his feelings on this

**Comment by EmeraldLoc** [comment]
This is NOT a gamemode. Won't add this. When multiple modifiers are allowed to be used at the same time in 2.5, this will almost be possible, so I don't really see a purpose here.
