### ISSUE TITLE
Dynamic Lives Bar

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#341]
100% - 66%: Blue Bar, basically the same as it appears in game now.
66% - 33%: Yellow Bar, a yellow bar representing that your midway to dying.
33% - 0: Red Bar, your about to die.

These would primarily effect the bluer internal bar, with the external have a respective tint of the internal one's color.
If the bar was in the red zone, Mario's Idle animation, would switch to the panting one.

**Comment by EmeraldLoc** [comment]
I take this back, this will look ugly.
