### ISSUE TITLE
Remove Tag Decryption Data From Chat Logs

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#344]
Seriously, it takes like 2 - 3 minute to scroll through them all, having them apart of some possible "Debug" setting would be nice. Honestly this should go along with every tag related thing that pops up in the chat logs.
![image](https://github.com/EmeraldLoc/tag/assets/168046906/c03c1f33-cdcb-41b7-a58a-fa6491958672)

This is obviously not all of them.

**Comment by EmeraldLoc** [comment]
Decrypted String ""

Yea prob will

**Comment by TheMan6900** [comment]
This would be better as some sort of Debug setting (as a mentioned)

**Comment by EmeraldLoc** [comment]
Done
