### ISSUE TITLE
Voting Start Option

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#346]
This would be an option right below (or above) the stop round option, which would take players back to the voting screen, if this option was used while on the voting screen, the maps to vote on would change.

**Comment by Bear64DX** [comment]
Dude this is perfect for testing paintings in hacks

**Comment by TheMan6900** [comment]
Exactly why I suggested it :thumb:

**Comment by EmeraldLoc** [comment]
Added
