### ISSUE TITLE
Wiggler's Cave Pipes

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#347]
Basically, there'd be a pipe where the blue coin switch is that'd lead you to where you fight wiggler. This is to make the stage bigger, cause it's so small (also is there a higher chance of smth getting added if its a pr rather than an issue cause if so im gonna make a crap ton of prs anyway ty).

**Comment by EmeraldLoc** [comment]
The more prs the better. Really not a fan of this idea. Removes a lot of skill required to navigate the map confidently

**Comment by Bear64DX** [comment]
Alright, that's fine by me
