### ISSUE TITLE
Bullet's go through walls

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#35]
This would be a setting for the blaster modifier that would enable or disable it from phasing through walls.

**Comment by EmeraldLoc** [comment]
Why? Idk about this change.

**Comment by TheMan6900** [comment]
I just would rather have projectiles not go through walls, it feels better

**Comment by EmeraldLoc** [comment]
... They don't? If they do, that's a bug

**Comment by TheMan6900** [comment]
yep they do

**Comment by EmeraldLoc** [comment]
Fixed
