### ISSUE TITLE
Make Everything Freeze Frame

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#355]
particles, objects, enemies, etc, all would freeze, on the freeze frame at the end of a match.

**Comment by TheMan6900** [comment]
Oh yeah, all sound effects would mute.

**Comment by TheMan6900** [comment]
OH YEAH ALSO MOVING OBJECTS

**Comment by TheMan6900** [comment]
AND SQUASHING EFFECTS

**Comment by EmeraldLoc** [comment]
Hopefully timestop doesn't break objects, added.
