### ISSUE TITLE
Save Blacklisted Items

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#361]
Basically, you can blacklist levels, modifiers, or gamemodes without having to re-blacklist them everytime you host.

**Comment by TheMan6900** [comment]
already being added

**Comment by Bear64DX** [comment]
oh sweet

**Comment by TheMan6900** [comment]
how do you close post?

**Comment by Bear64DX** [comment]
There's a "Close Issue" button at the bottom of the issue.

**Comment by Bear64DX** [comment]
you can also reopen them as well
