### ISSUE TITLE
New Tips

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#365]
Pipes not showing up correctly? Make sure you have dashes (-) when they're supposed to be there, and vice versa.
On https://mods.sm64coopdx.com/, there are a ton of ported romhacks you can check out. You can even port them to tag if you want.
whats ligma? (joke)
If there is an issue, or you want to suggest something, report it to me (Emerald) at https://github.com/EmeraldLoc/tag/issues/.
You can color your name however you'd like with {backslash}RRGGBB{backslash}. You can even add a star to your name with U+007F.
Assassins is peak. - Bear (joke no.2)
You can contribute to Tag by opening a Pull Request! (idk if this is advertisement, it's not supposed to be but if it is dont include this.)
If you've ever wanted to port a hack to Coop, then Sunk and Isaac have made a great guide on that. It's somewhere on the modsite.
Remember when I said there were 26 tips? There's more. (joke no.3)
Have you ever checked out GeoGuessr in SM64? Well now you can! It's a great mod by EmilyEmmi.
Did you know there's an entire repo just dedicated to arena stages being ported to Tag? You can find it on https://github.com/EmeraldLoc/tag-arena-maps, you can even make a PR to get an arena stage there if you've ported one.

That's every tip I could think of. You don't have to include all of them (especially the joke ones). But I thought I'd suggest this sometime

**Comment by EmeraldLoc** [comment]
Not a ligma joke

I need to invite you to the dev repo

**Comment by Bear64DX** [comment]
LOL aight bet
