### ISSUE TITLE
Vote Cancel Input

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#368]
I feel like vote cancelling should just be B. For some reason, I feel like having it be both A and B just feels weird.

**Comment by EmeraldLoc** [comment]
I can kinda see why, will need to create a tip explaining that.

**Comment by TheMan6900** [comment]
This would honestly work better, if there was a prompt under the map you voted, saying that you could unvote it by pressing B

**Comment by EmeraldLoc** [comment]
Done
