### ISSUE TITLE
Sardine Pipe

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#369]
If you time going into the pipe while the time runs out, just right. You can have your sardine spot be in the pipe, making it impossible for people to hit you.

**Comment by EmeraldLoc** [comment]
This... literally isn't possible, you will always be able to hit the sardine in that case, are you sure?

**Comment by TheMan6900** [comment]
you are.... how?

**Comment by EmeraldLoc** [comment]
A ground pound. Either way, this has been fixed next ver as a side effect of freezing the sardine.
