### ISSUE TITLE
Elimination Message Bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#373]
The elimination message saying "X got Eliminated" displays when a player connects to the match (from none to a role) just when the round starts

**Comment by EmeraldLoc** [comment]
Wait, huh?

**Comment by TheMan6900** [comment]
If a player switches from the none team to the eliminated team, as the match starts, itll display that their eliminated.

**Comment by EmeraldLoc** [comment]
> as the match starts

What is this exactly, is it a second before the match starts, a second after, or anywhere in between?

**Comment by TheMan6900** [comment]
pretty sure its anywhere in between, if not its probably the other too

**Comment by EmeraldLoc** [comment]
Has this occurred since then?

**Comment by TheMan6900** [comment]
Yea

**Comment by TheMan6900** [comment]
Like 3 times

**Comment by EmeraldLoc** [comment]
Does the player actually get eliminated, or is it immediately reversed? What gamemodes do this happen in?

**Comment by TheMan6900** [comment]
They do get eliminated and happens in every gamemode where you CAN get eliminated

**Comment by EmeraldLoc** [comment]
Wait so then what's the bug here?

**Comment by TheMan6900** [comment]
It's not supposed announce that there eliminated with a pop up

**Comment by EmeraldLoc** [comment]
You died while the round was started..... so wouldn't that be correct?

**Comment by TheMan6900** [comment]
I mean, you die because you joined the game, I don't feel like that should be considered you dying 💀

**Comment by EmeraldLoc** [comment]
> you die because you joined the game

The popup doesn't trigger when you join the game, you sure the player isn't dying beforehand?

**Comment by TheMan6900** [comment]
Im 95% sure they ain't just joining and dying in 2 seconds

**Comment by EmeraldLoc** [comment]
Well if you could try to reproduce it, that'd help a bit :)

**Comment by TheMan6900** [comment]
Tried replicating to not avail

**Comment by EmeraldLoc** [comment]
Gonna close this, I believe there's an error in how you are interpreting what's happening here, I don't think it's the mod at fault. If you can send a video I'll reopen this.
