### ISSUE TITLE
Behind the Scenes Sardines (nice flow wait what)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#378]
Alright so basically, if the sardine gets chosen to hide and you're in a weird state (being near an enemy), you may or may not just keep hearing your character scream over and over again. I can't really describe how you encounter this, but it happens pretty regularly for me. (not sure if I should suggest these on the dev repo or not)

**Comment by EmeraldLoc** [comment]
This shouldn’t happen anymore. And yea keep making issues here, there are some exceptions but I’ll tell you those when it’s relevant

**Comment by Bear64DX** [comment]
Alright, I'll keep making PRs on the new one though. I can wait for you to accept them.
