### ISSUE TITLE
Possible name ideas for Bower levels in SR

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#387]
I had a thought that for SR, the Bowser stages could have their own names: Some ideas I had were:
- Bowser 1 < Piranha Plant Hideout/Base
- Bowser 3 < Star Road Showdown
- Bowser 3 < Star Domain

All the ideas I could think of for now. Also, speaking of stage names for SR, I noticed that The Final Hub isn't actually called "Star Road". I'm like 99% sure it's actually called Star Road, since if you were to just search up "Super Mario Star Road" and look at the areas, it'd most likely be called Star Road. There's also a sign in game that says this:
![SMSR](https://github.com/EmeraldLoc/tag/assets/171458695/a48b3364-a67a-4776-972a-9b91a5723d4f)

**Comment by EmeraldLoc** [comment]
I like the direction of the first bowser level, kinda long though

**Comment by Bear64DX** [comment]
Oh, hmmm. I specifically named it Piranha Plant Base, because it has piranha plants. What about just "Piranha Hideout" or "Garden Hideout", or what about "Garden Apocalypse"? The stage kinda looks like it's taken straight out of one

**Comment by TheMan6900** [comment]
what about Piranha's Hideout/Base

**Comment by Bear64DX** [comment]
Piranha Hideout makes it sound plural, which makes since cause there's multiple piranhas. If you just say "Piranha's Hideout", it kinda sounds singular. I guess it'd work as well though

**Comment by EmeraldLoc** [comment]
Gonna stick with bowser 1 for the first one, if anyone has better suggestions, throw'em here.

**Comment by Bear64DX** [comment]
Piranhas' Battle Base (' after s because plural piranhas)

**Comment by EmeraldLoc** [comment]
Love how you edited out the message about s' and plurals. The favorite in the bunch rn is Piranha Hideout, although I'm not quite there with making that the name.

**Comment by Bear64DX** [comment]
I feel like the one I suggested fits well tbh
