### ISSUE TITLE
New modifier - Small

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#39]
This would make the player half there regular size with the camera zoomed in accordingly.

**Comment by EmeraldLoc** [comment]
It’s impossible to change Mario’s hitvox, so this can’t be done good

**Comment by TheMan6900** [comment]
You can?

**Comment by EmeraldLoc** [comment]
I saw what Isaac said. I have never seen this be done. I believe what he is referring to is changing Mario's object hitbox, which doesn't affect Mario's collision with walls. You should ask him and see how to do it on discord, otherwise though I've looked into this for a while now, so
