### ISSUE TITLE
Auto Mode Bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#404]
If you have auto mode off, and cancel the current ACTIVE round, the roles that players had when the round was cancel will remain for the next round.

**Comment by EmeraldLoc** [comment]
Define cancel. Are you hitting the Stop Round button, or changing the gamemode?

**Comment by TheMan6900** [comment]
just starting a random map after the round is active

**Comment by EmeraldLoc** [comment]
Was gonna fix this until I realized this actually makes sense. If you have certain people set to be taggers, you should be able to keep those when starting a new round.
