### ISSUE TITLE
Spring Momentum 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#407]
This is such a minor change but, make it so that springs carry your momentum instead of canceling it all together, or at least carry some of your previous momentum.

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
Springs set speed to zero, so id rather them carry some of the speed you went on them with

**Comment by EmeraldLoc** [comment]
OH, I see

**Comment by EmeraldLoc** [comment]
Added
