### ISSUE TITLE
Rename the runners name in juggernaut

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#41]
from "The Juggernaut" to just "Juggernaut"

**Comment by EmeraldLoc** [comment]
I would, however it doesn't fit, so it says "Juggernau," if you have a better name suggestion, throw it here (maybe just runner'll do fine?)

**Comment by TheMan6900** [comment]
The Jugger doesnt fit either

**Comment by TheMan6900** [comment]
maybe just have the name be "Jugger"

**Comment by EmeraldLoc** [comment]
It does?

**Comment by TheMan6900** [comment]
> It does? 
nope

**Comment by EmeraldLoc** [comment]
Must be a coopdx thing. I renamed it to runner anyways, so will close this.
