### ISSUE TITLE
Ideas for a rework of Misty Mine

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#414]
Alright, so I bet it's no surprise that I've been re working cut GS stages so that they can be added. One that stood out to me was MM.
MM is definitely my fav stage in Green Stars. So it'd be cool if we (or just me....) could think of some ideas for this stage.
I want it to get added, but chances of it being added are low so I won't get my hopes high. These changes are the following:
- Cut the amount of pipes, only have them for mass traveling and softlocks.
- Add a ton of springs for easier navigation, and not make the task slow-paced.
- Try to have like maybe 2 pairs of pipes minimum
- Make sure the stage isn't a slow boring course for navigation.

Now those are all the ideas I have. Like I said, MM is my fav gs stage, and I'd do anything for it to get added. Which is why I was planning on reworking it. These are just some ideas I had for it.
MM is just such a big stage that I feel like it'd be hard to complete this task. But if I tried hard enough, and it's okay for me to make a PR, I don't have low hopes. (anyway your gonna love the next remaster)

**Comment by EmeraldLoc** [comment]
> and it's okay for me to make a PR

Make a pr on anything, idc. I'll just tell you if it's good or not.

> MM is just such a big stage that I feel like it'd be hard to complete this task

Very much so, especially the very long tunnel

**Comment by Bear64DX** [comment]
Will try my hardest on it. Anyway now onto Rainbow Star Ha-

**Comment by Bear64DX** [comment]
Jokes aside, I'll still probably make issues like this just so I can get a general thought before straight up adding the stage

**Comment by EmeraldLoc** [comment]
You may be able to create an entry in the Discussions area btw. That might work better for this type of stuff. Anyhoo, will close this.

**Comment by Bear64DX** [comment]
alr, will start working on this once the BTT remaster gets dealt with

**Comment by Bear64DX** [comment]
And yeah, will start making stuff like this over there rather than in issues
