### ISSUE TITLE
Dynamic Api

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#416]
Make the api dynamically change based on the level, instead of having the api only have coords for one level, which can mess up the spawning position of other levels

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
Api doesnt change based off the level, the api only applies to one level, with all the other levels having the same api

**Comment by EmeraldLoc** [comment]
What? Ok, do you know what an API is?

**Comment by TheMan6900** [comment]
Oh wait...
