### ISSUE TITLE
API Addition: Blacklisted Modifiers (for singular stages)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#418]
Alright so, basically what you could do is blacklist certain modifiers on certain stages, to prevent stuff like softlocks. Stages like Perilous Cliffs are basically impossible to navigate with high gravity for example. So having an API that could do this would be cool.
Also, if this were to get added, make sure to add this to the Romhacks Documentation.

**Comment by TheMan6900** [comment]
ehhh

**Comment by Bear64DX** [comment]
Added (thanks emerald!)
