### ISSUE TITLE
Disable Cannon Bhv

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#425]
Delete Cannon Bhv when cannons are off.

**Comment by EmeraldLoc** [comment]
Is there a reason? I just simply disable the behavior.

**Comment by TheMan6900** [comment]
For some cannons (most notably in star road) that are exposed with no bomb omb thing on top of them

**Comment by EmeraldLoc** [comment]
Yea, that's cuz they don't exist to begin with. The behavior's still disabled.
