### ISSUE TITLE
Terminator 2nd Ability

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#427]
Credits to Onysfx,

This second ability would be a custom ability exclusive to the terminator, it would be a ball of goo that you would throw at runner to slow them down. This could stick on the ground once it well hits the ground.

**Comment by EmeraldLoc** [comment]
Why do you want the terminator buffed so much. I feel like it’s pretty balanced as is

**Comment by TheMan6900** [comment]
It aint me, Blame Onysfx
