### ISSUE TITLE
FINAL BLOW!!! 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#430]
Deathmatch, and Terminator exclusive detail. When hitting the final match-ending blow on someone, a custom KO sound effect would play (could be something from the game itself), this would also include a slomotion effect + a custom camera pan.

**Comment by Bear64DX** [comment]
we need the game sound from ssbu and then it slows down and then it takes you to a custom victory scre- (ok jokes aside, everything other than the custom victory screen sounds cool, oh and there wouldnt be music playing)

**Comment by EmeraldLoc** [comment]
> Deathmatch exclusive detail. When hitting the final match-ending blow on someone, a custom KO sound effect would play

Jus that? Kinda garbage. It should also include a slomotion effect + a custom camera pan.

**Comment by Bear64DX** [comment]
literally what emerald said

**Comment by TheMan6900** [comment]
no like the effects were possible

**Comment by TheMan6900** [comment]
due to syncing and stuff.

**Comment by Bear64DX** [comment]
what about assassins as well?

**Comment by EmeraldLoc** [comment]
I'll add this to every gamemode using the timer. Assassins will also do the other thing.

**Comment by TheMan6900** [comment]
Oh yeah, some special Smash Bros-like visual effects would look cool too.

**Comment by TheMan6900** [comment]
Maybe all these could be exclusive to tag cam.

**Comment by EmeraldLoc** [comment]
> Maybe all these could be exclusive to tag cam.

A slow motion effect does not need to be exclusive to tag cam, that's what I can say.

**Comment by TheMan6900** [comment]
alright than

**Comment by EmeraldLoc** [comment]
Unfortunately, it's not viable to create a slow motion effect before you hit a player. You'd have to be able to send a packet to every player stating you have killed the player within 0.2 seconds. Even if you hit that target time, 0.2 seconds is the total time before the round actually ends, so you only have 0.2 seconds to admire the slow motion (not a lot). This simply isn't viable. I've added this for when the round timer reaches 0.5 seconds. When it does, the game slows down to a third of the normal speed, and so does the timer. Hopefully this is good enough.
