### ISSUE TITLE
Non sign I-frames

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#432]
When testing in 2.4, I kinda found a loophole where you can just spam signs, and they don't affect you. I can already imagine a scenario where theres 5 seconds left of the game, and someone just reads a sign and spams it so they don't get hit. I'm a little clueless so I'm not 100% sure abt this but idk how much I'm a fan of readable signs. That's just me though, i'm not sure how good this anti cheat is.

**Comment by EmeraldLoc** [comment]
Oh, the anti cheat is as good as it can be. When you're reading a sign, or talking to an npc, it turns that person into touch to tag. The runner actually has a disadvantage if they're in there.

**Comment by Bear64DX** [comment]
Hmm, but what abt spamming the sign? Are there a few frames where runners could be hit?

**Comment by EmeraldLoc** [comment]
It doesn't give out any i frames when a runner enters a sign. The moment a runner enter a sign, it turns into touch to tag, which always gives a tagger an advantage, since they can just stand in the player due to the goofy nature of the action.

**Comment by Bear64DX** [comment]
Ohh, you touch. Clueless me was tryna tag them :skull:
