### ISSUE TITLE
Tagger wins reset?

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#433]
So I was in a server with TheMan, he said my tagger wins were 0, which was weird. And when I hosted a tag server, I saw that I had literally 0 runner wins. What happened to my stats? I don't remember messing around w/ save files, and a similar thing happened to me with MH. I'm so clueless on this

**Comment by EmeraldLoc** [comment]
If the folder name was changed from tag to a different name, your save won't carry over. You can see if your save was wiped by going to the sav folder and opening tag.sav. If it's filled to the brim then you're good, otherwise something goofy happened.

**Comment by Bear64DX** [comment]
It was in a different server. My tag 2.4 folder's called Tag, lemme check the .sav file

**Comment by Bear64DX** [comment]
All of my 2.4 stats were 0, here's part of the save file:
stats_6_totalTags=h3qe64hezdy
stats_global_totalTags=h3qe64hej
stats_4_playTime=h3qe64he5w05_5
stats_4_totalTimeAsRunner=h3qe64heza5zzw
stats_global_totalTimeAsRunner=h3qe64heja_d
stats_4_totalTags=h3qe64heaj
stats_2_playTime=h3qe64he5w5zw_
stats_2_totalTimeAsRunner=h3qe64hey_w0j0
stats_2_totalTags=h3qe64hey__
stats_4_runnerVictories=h3qe64heyj
stats_global_runnerVictories=h3qe64hey55
stats_8_playTime=h3qe64hevad_za
stats_8_totalTimeAsRunner=h3qe64he_d__55
stats_8_totalTags=h3qe64hezay
stats_3_playTime=h3qe64hey__5a0
stats_3_totalTimeAsRunner=h3qe64hezdd5yy
stats_3_totalTags=h3qe64hew5
stats_1_playTime=h3qe64hewzydyz
stats_1_runnerVictories=h3qe64hevw
stats_1_totalTimeAsRunner=h3qe64he_jjyjd
stats_1_totalTags=h3qe64he5z0
stats_7_playTime=h3qe64he_wjjwa
stats_7_totalTimeAsRunner=h3qe64heydwzd_

**Comment by EmeraldLoc** [comment]
I can't really read this without the encryption key's. What.I can say is the freeze tag gamemode is missing from the stats, that alone tells me your stats probably got reset. This is slightly worrying because I've had a similar issue, but had a backup (that's why I jumped from 120 wins to 95). Were you messing with the tournament mode in tag dev? What were you doing in the dev repo? When did theman notice this, when you joined or later?

**Comment by TheMan6900** [comment]
when he joinned.

**Comment by EmeraldLoc** [comment]
Can you give me your entire save file so I can see if anything's wrong with it?

> when he joinned.

You have the tag folder named "tag" right?

**Comment by Bear64DX** [comment]
I didn't do anything w/ freeze tag or tourneys

**Comment by TheMan6900** [comment]
> You have the tag folder named "tag" right?

yeah

**Comment by Bear64DX** [comment]
encryptionKey1=a3b-crdkelf7gqhii6j8kglcmtn4ompsqur2s9t
encryptionKey2=huxvbwnxfy1zo1z2y354_5v607a8j9w0d_e-..p
stats_6_playTime=h3qe64hezzyza_
stats_global_playTime=h3qe64hey_d0d
stats_6_totalTags=h3qe64hezdy
stats_global_totalTags=h3qe64hez_
stats_4_playTime=h3qe64he5w05_5
stats_4_totalTimeAsRunner=h3qe64heza5zzw
stats_global_totalTimeAsRunner=h3qe64hezzzaj
stats_4_totalTags=h3qe64heaj
stats_2_playTime=h3qe64he5w5zw_
stats_2_totalTimeAsRunner=h3qe64hey_w0j0
stats_2_totalTags=h3qe64hey__
stats_4_runnerVictories=h3qe64heyj
stats_global_runnerVictories=h3qe64hey55
stats_8_playTime=h3qe64hevad_za
stats_8_totalTimeAsRunner=h3qe64he_d__55
stats_8_totalTags=h3qe64hezay
stats_3_playTime=h3qe64hey__5a0
stats_3_totalTimeAsRunner=h3qe64hezdd5yy
stats_3_totalTags=h3qe64hew5
stats_1_playTime=h3qe64hewzydyz
stats_1_runnerVictories=h3qe64hevw
stats_1_totalTimeAsRunner=h3qe64he_jjyjd
stats_1_totalTags=h3qe64he5z0
stats_7_playTime=h3qe64hevdyvda
stats_7_totalTimeAsRunner=h3qe64heyzzv_y
stats_7_totalTags=h3qe64hejz
autoHideHud=h3qe-mmce73c9l
stats_8_runnerVictories=h3qe64he_0
stats_3_taggerVictories=h3qe64heyw
stats_global_taggerVictories=h3qe64hey
stats_10_playTime=h3qe64heajdyav
stats_10_runnerVictories=h3qe64he0a
stats_10_totalTimeAsRunner=h3qe64he_0wzdd
stats_10_totalTags=h3qe64hezda
stats_3_runnerVictories=h3qe64hezz
stats_10_taggerVictories=h3qe64hezj
stats_2_runnerVictories=h3qe64hezj
stats_9_playTime=h3qe64he_yz_5w
stats_9_totalTags=h3qe64he_az
stats_6_taggerVictories=h3qe64he5w
stats_5_playTime=h3qe64hej0a
stats_5_totalTimeAsRunner=h3qe64hed
stats_5_totalTags=h3qe64he_
bljs=h3qe-mmce73c9l
eliminateOnDeath=h3qe-mmceh2xl
autoMode=h3qe-mmceh2xl
boost=h3qe-mmceh2xl
useRomhackCam=h3qe-mmceh2xl
hazardSurfaces=h3qe-mmce73c9l
stats_1_taggerVictories=h3qe64hev
stats_2_taggerVictories=h3qe64hezz
achievement_1=h3qe-mmceh2xl
achievement_3=h3qe-mmceh2xl
achievement_4=h3qe-mmceh2xl
achievement_5=h3qe-mmceh2xl
achievement_6=h3qe-mmceh2xl
achievement_8=h3qe-mmceh2xl
achievement_25=h3qe-mmceh2xl
achievement_16=h3qe-mmceh2xl
achievement_2=h3qe-mmceh2xl
stats_global_totalTournamentPoints=h3qe64he55d
playerTitle=h3qe64he.5
achievement_14=h3qe-mmceh2xl
stats_11_playTime=h3qe64hew_0ay
stats_11_totalTimeAsRunner=h3qe64heza_vy
stats_11_totalTags=h3qe64he0a
stats_5_taggerVictories=h3qe64hez
stats_9_taggerVictories=h3qe64heyz
achievement_29=h3qe-mmceh2xl
playerTrail=h3qe64heza
achievement_9=h3qe-mmceh2xl
stats_11_runnerVictories=h3qe64hey
achievement_27=h3qe-mmceh2xl
bind_1=h3qe64he0_
firstLaunch=h3qe-mmce73c9l
achievement_26=h3qe-mmceh2xl
changelogVer=byp_
activeTimers_9=h3qe64hev_ddpd
maxLives_9=h3qe64he5
tournamentPointSystem=h3qe64hed
maxLives_8=h3qe64he5
maxLives_5=h3qe64he5
stats_global_totalTournamentWins=h3qe64hey
achievement_22=h3qe-mmceh2xl
stats_5_runnerVictories=h3qe64hez
achievement_17=h3qe-mmceh2xl
achievement_18=h3qe-mmceh2xl
hidingTimer_7=h3qe64hewdd
theme=h3qe64he_
cannons=h3qe-mmce73c9l9ll

**Comment by Bear64DX** [comment]
Entire save file if you're wondering

**Comment by EmeraldLoc** [comment]
> Yeah, it's named tag (with a capital T)

Well that's why... It has to be called "tag".

**Comment by Bear64DX** [comment]
just "tag"? My stats were there even with a capital T. they're now just gone.

**Comment by Bear64DX** [comment]
they're still gone....

**Comment by EmeraldLoc** [comment]
Whats the name of the .sav file?

**Comment by Bear64DX** [comment]
tag.sav. But I figured out that if I rename tag 2.32 to Tag, my stats are back. 2 problems is that:
- I can't really rename tag 2.4 to tag (i think)
- My tagger stats are still gone

**Comment by Bear64DX** [comment]
When I renamed Tag 2.4 to tag, my stats went back

**Comment by Bear64DX** [comment]
Now the runner ones are back when I join TheMan's server, but when I host a 2.4 server they're gone?

**Comment by EmeraldLoc** [comment]
Right, that's correct. Here, look:

Your save file is called tag.sav. Because of that, it corresponds to a mod folder called "tag". If the mod folder is named, say, "tag 2.4", then it will link to a save file called "tag 2.4.sav." The mod you are currently using, whether it be tag dev or tag main, should always be renamed to "tag". Does this make sense?

**Comment by Bear64DX** [comment]
No, the problem is the stats don't load even when tag 2.4 IS called tag

**Comment by Bear64DX** [comment]
The achievements load, but my runner wins and tagger wins on 2.4 don't

**Comment by EmeraldLoc** [comment]
Ok, you should make a backup of the tag.sav file.

I'm gonna try to load your save file into tag to see if it works for me

**Comment by Bear64DX** [comment]
alr, made a backup tag.sav file, do you want me to host a server with the same psw you used before?

**Comment by Bear64DX** [comment]
or do you just want me to send the tag.sav file

**Comment by EmeraldLoc** [comment]
I just used the one you sent me. Ok, so for some reason, and I Can't tell you why, your tagger wins are infact reset. However, it's only the global tagger wins that got reset. All this means is your gamemode tagger wins and your global tagger wins are desynced. I can resync them for you and send you that specific key you can throw into the tag.sav file.

**Comment by EmeraldLoc** [comment]
stats_3_taggerVictories=h3qe64heyw
stats_global_taggerVictories=h3qe64hey

it seemed to have synced up with the Infection gamemode's stats... this may be a bug within Tag, however based off of the code there that simply isn't possible.

**Comment by Bear64DX** [comment]
Alright, yeah. Noticing the runner wins save when renaming Tag 2.32 to "tag" but loading up tag 2.4 doesn't even show me runner wins. It's still a mystery of what happened. I have to go know. Keep this issue open and send me further info.

**Comment by EmeraldLoc** [comment]
I came up with a total of 124, does this sound accurate?

To replace the entry in your save file, replace `stats_global_taggerVictories=h3qe64hey` with `stats_global_taggerVictories=h3qe64hezy_`. This should give you a tagger victory count of 124

**Comment by EmeraldLoc** [comment]
> Alright, yeah. Noticing the runner wins save when renaming Tag 2.32 to "tag" but loading up tag 2.4 (when its called tag) doesn't even show me runner wins.

There seems to be a lot of moving parts to this. How many save files for tag do you have? Can you send every single one here?

**Comment by Bear64DX** [comment]
124 wins, sounds accurate. I'm like 70% on the side of it being 15X but i'm not sure. Will do that. =

**Comment by Bear64DX** [comment]
Most of the save files are un organized for Tag. There are 2 "Tag Custom" ones, which were used for RH porting and are seperate for tag. Then there's Tag 64, which looks like this:
[storage]
encryptionKey1=a4bvcrdcehfkgmh2ilj5kslnminwoqp9q1rxsft
encryptionKey2=0u_vywzx3ybzu1.263p4a5g677t8-9o08_j-e.d
stats_2_playTime=04mjlw0j-tg7
stats_global_playTime=04mjlw0j6.paaa
stats_2_totalTimeAsRunner=04mjlw0jag8p
stats_global_totalTimeAsRunner=04mjlw0j.8g68g
stats_2_totalTags=04mjlw0j6
stats_global_totalTags=04mjlw0j.8-
stats_6_playTime=04mjlw0jatap
stats_6_totalTags=04mjlw0j.
stats_3_playTime=04mjlw0j.7o66
stats_3_taggerVictories=04mjlw0jp
stats_global_taggerVictories=04mjlw0jt
stats_3_totalTimeAsRunner=04mjlw0jtt7-
stats_3_totalTags=04mjlw0jt
stats_10_playTime=04mjlw0ja.76
stats_10_taggerVictories=04mjlw0j.
stats_10_totalTimeAsRunner=04mjlw0j6.t
stats_10_totalTags=04mjlw0jg
stats_8_playTime=04mjlw0j76oo
stats_8_totalTimeAsRunner=04mjlw0jg8pt
stats_8_totalTags=04mjlw0ja
stats_9_playTime=04mjlw0j.-ooa
stats_9_taggerVictories=04mjlw0j6
stats_9_totalTags=04mjlw0jap
useRomhackCam=04mjvqqnj0x_h
autoHideHud=04mjvqqnjk4nfh
stats_7_playTime=04mjlw0jp-76.
stats_7_totalTimeAsRunner=04mjlw0j..777
stats_7_totalTags=04mjlw0j.8
stats_8_runnerVictories=04mjlw0j.
stats_global_runnerVictories=04mjlw0j66
stats_1_playTime=04mjlw0j...-a6
stats_1_runnerVictories=04mjlw0j.o
stats_1_totalTimeAsRunner=04mjlw0jt78.a
stats_1_totalTags=04mjlw0jpa
stats_3_runnerVictories=04mjlw0j6
stats_5_playTime=04mjlw0jp.8g
stats_5_totalTimeAsRunner=04mjlw0j8
stats_5_totalTags=04mjlw0j6
stats_1_taggerVictories=04mjlw0j.

**Comment by TheMan6900** [comment]
name = "llf",
                level = LEVEL_SSL,
                painting = get_texture_info("painting_sr_llf"),
                area = 1,
                pipes = {
                    {
                        { x = 1158, y = 3336, z = 3333 },
                        { x = 3, y = -529, z = -4816 }
                    },
                    {
                        { x = -259, y = -2213, z = 2789 },
                        { x = 654, y = -751, z = 893 }
                    }
                },
                overrideSurfaceType = {[SURFACE_DEFAULT] = SURFACE_HARD_NOT_SLIPPERY}
like this

**Comment by EmeraldLoc** [comment]
Yea tag 64 is jzzle's lobby. I suppose it'll be clearer when 2.4 comes out, since it'll alert you if the folder is named wrong. This could have very well been a bug with coopdx failing to load the entry in the save file (as that is a bug), however I'm unsure if that's the case. What i do know is tag is pretty much perfect in terms of code, as `stats.globalStats.taggerVictories = stats.globalStats.taggerVictories + 1` is the only time the variable is set and saved. So it most likely failed during the loading process, and then you played a round, leaderboard triggered, stats saved, and it got wiped. Will close this now.
