### ISSUE TITLE
Adding OW2 to GS

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#438]
Was planning on adding the second overworld to SM64: The Green Stars. It was originally gonna get in, but I cut it cause I thought it was too misc. But I want to add more stages, those stages being good.
There'd be a diagonal spring that would take you on the castle itself. The level's also really flat in general.
Does this idea appeal you? (also this was originally a discussion post but it was irrelevant and didn't get attention)

**Comment by EmeraldLoc** [comment]
Tbh I didn't know why you hadn't added it in the first place, so yea this sounds good

**Comment by Bear64DX** [comment]
This will get added once the current PR is done.
