### ISSUE TITLE
New gamemode - Search

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#44]
This would basically be reversed sardines with there being one tagger and the rest runners, the runners would have 30 seconds to hide wherever in the map until the timer runs out. After the timer runs out, the tagger then would try to find all the runners in the time limit, with the runners having to not be tagged until the time runs out.
If the tagger tagged a sardine (runner) that sardine would then turn into another tagger and would try to find other sardines. taggers would receive a 1.03 speed boost along with the boost, and the runners would have the same sardine properties as in sardines (freezing in the air, not being able to move, etc) and runners would not be able to ready-up as in sardines (for obvious reasons)

**Comment by EmeraldLoc** [comment]
The name's ok, however if there's a better one i'd go for that instead

**Comment by TheMan6900** [comment]
Seekers, Hiders, Search

**Comment by EmeraldLoc** [comment]
Search is definitely heading in the right direction, and I believe I like that name more than seeker

**Comment by TheMan6900** [comment]
alright 👍

**Comment by TheMan6900** [comment]
glad I was able to make this gamemode actually good and not, terminator but no radar

**Comment by TheMan6900** [comment]
if a searcher leaves/disconnects, while in the hiding phase, another searcher is randomly pulled.

**Comment by EmeraldLoc** [comment]
I've decided on a different method for this. I will not be making this into a gamemode, I will instead make sardines have multiple runners, and have the one tagger and one runner modifiers activate old sardines and "old" search.

**Comment by TheMan6900** [comment]
> I've decided on a different method for this. I will not be making this into a gamemode, I will instead make sardines have multiple runners, and have the one tagger and one runner modifiers activate old sardines and "old" search.

This also sounds worst

**Comment by TheMan6900** [comment]
yeah uh, this would work way better as its own thing.

**Comment by EmeraldLoc** [comment]
Ye, will keep this as is.

**Comment by TheMan6900** [comment]
ADD !! !!

**Comment by EmeraldLoc** [comment]
no >:)

**Comment by TheMan6900** [comment]
WHAT ELSE ARE YOU GONNA DO !! !!

**Comment by EmeraldLoc** [comment]
no, no more tag gamemode, now 2.5 feature >:)

**Comment by TheMan6900** [comment]
NUH UH !! !!

**Comment by TheMan6900** [comment]
YOU CANT JUST PROMISE A 2.4 THEN DELAY IT !! !!

**Comment by EmeraldLoc** [comment]
watch me

**Comment by EmeraldLoc** [comment]
erm acktully I didnt promise it

**Comment by TheMan6900** [comment]
You literally added everything else, and this was on the back burnner for like 3 weeks.

**Comment by TheMan6900** [comment]
> erm acktully I didnt promise it

You promised it in chat once-

**Comment by EmeraldLoc** [comment]
Proof???

**Comment by TheMan6900** [comment]
use brain.

**Comment by TheMan6900** [comment]
also what else are you gonna be doing for the next couple of months

**Comment by EmeraldLoc** [comment]
My brain is currently on vacation

**Comment by EmeraldLoc** [comment]
> also what else are you gonna be doing for the next couple of months
Be lazy

**Comment by TheMan6900** [comment]
no it aint, keep working

**Comment by EmeraldLoc** [comment]
Nah, fr though, I'm hard focusing on other stuff for Tag, this can wait.

**Comment by TheMan6900** [comment]
> Nah, fr though, I'm hard focusing on other stuff for Tag, this can wait.

Like???

**Comment by TheMan6900** [comment]
theres like 5 other things to hard focus on-

**Comment by EmeraldLoc** [comment]
Added. You're funny.

**Comment by TheMan6900** [comment]
Alright you have to actually add it now.

**Comment by EmeraldLoc** [comment]
Bro, what do you think the word "added" means?
