### ISSUE TITLE
2.4 Save Data Problem

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#447]
So for a little bit context, as I said in some of my issues, I was helping murioz with his 2.4 port of "Mario in the colorful lands", and for some reason after we finished our session, once I switched over to 2.32, all my stats were completely wiped (similar to how bears stats got so)

**Comment by EmeraldLoc** [comment]
Can you send your tag.sav file here?

**Comment by TheMan6900** [comment]
Yeah wait a second.

**Comment by TheMan6900** [comment]
encryptionKey1=axb4crdie5f9ghhdikjskolem7n6oap8qgrpsvt
encryptionKey2=0ujvqw.xmy_zw1t233-4l5n6f7u8y9z0b_1-2.c
autoHideHud=0xh14aae19xev5
stats_1_playTime=0xh1k601tb33nz
stats_global_playTime=0xh1k601tu3f3z
stats_1_taggerVictories=0xh1k6013
stats_global_taggerVictories=0xh1k601n
stats_1_totalTimeAsRunner=0xh1k601lnf3n
stats_global_totalTimeAsRunner=0xh1k601ubtu3
stats_1_totalTags=0xh1k601tl
stats_global_totalTags=0xh1k601-3
stats_6_playTime=0xh1k601tlyly
stats_6_totalTags=0xh1k601u
stats_1_runnerVictories=0xh1k601t-
stats_global_runnerVictories=0xh1k601tn
stats_2_playTime=0xh1k6013bbz
stats_2_totalTimeAsRunner=0xh1k601tzz-
stats_2_totalTags=0xh1k601b
stats_3_playTime=0xh1k601yfnu
stats_3_totalTimeAsRunner=0xh1k6013u3b
stats_3_totalTags=0xh1k601b
stats_10_playTime=0xh1k601ltuu
stats_10_totalTimeAsRunner=0xh1k601-yzl
stats_10_totalTags=0xh1k601b
stats_9_playTime=0xh1k601ttly
stats_9_taggerVictories=0xh1k601t
stats_9_totalTags=0xh1k601l
stats_4_playTime=0xh1k601uzz3
stats_4_totalTimeAsRunner=0xh1k601l333
stats_4_totalTags=0xh1k601b
stats_4_runnerVictories=0xh1k601t
stats_5_playTime=0xh1k6013-3t
stats_5_totalTimeAsRunner=0xh1k601b
stats_5_totalTags=0xh1k6013
stats_6_taggerVictories=0xh1k6013
stats_8_playTime=0xh1k601tfy-y
stats_8_runnerVictories=0xh1k601t
stats_8_totalTimeAsRunner=0xh1k601ttuty
stats_8_totalTags=0xh1k601n

**Comment by EmeraldLoc** [comment]
Yea your save's wiped. There must be something wrong with 2.4, will look into.

**Comment by TheMan6900** [comment]
any way for me to get them back??

**Comment by EmeraldLoc** [comment]
I can't. Unlike bears, this one was wiped, so any attempt to recreate such values will fail. I believe this is a problem with DX, however truthfully I'm unsure. I run a custom version that has many failsafes for this kind of stuff. DON'T go reporting this to the DX team, I already have an issue on this very thing there, and I'm still figuring out how to reproduce it.

**Comment by TheMan6900** [comment]
well thats sucks, atleast I got my 1000 runner wins. so thats all that matters

**Comment by EmeraldLoc** [comment]
> I already have an issue on this very thing there, and I'm still figuring out how to reproduce it.

I take this back. I believe I know the problem, and it has been resolved on dx's side for v1. `mod_storage_load` sometimes frees memory when it shouldn't. If i were to guess, it's not loading in those tagger wins due to goofy memory stuff. This has happened for 2 people now, both of which are using coopdx, so it makes sense for that to be it since I, the guy who launches this thing the most (and every single time the tagger stuff loads), who is running a modified build of dx that has these problems fixed, don't encounter such issues.

**Comment by TheMan6900** [comment]
Oh alright than.

**Comment by TheMan6900** [comment]
all right then

**Comment by TheMan6900** [comment]
Once again, I dont really care that my saves got wiped, just thought it was something that should be considered

**Comment by Bear64DX** [comment]
Sheesh, sorry to hear that. Definitely gonna make a backup for sure.

**Comment by TheMan6900** [comment]
nah its fine, truly I didnt really care what happened to my save, dont really play tag as much anymore

**Comment by TheMan6900** [comment]
I didnt really have any other goal to strive for so.

**Comment by EmeraldLoc** [comment]
I'm gonna assume this is a coopdx problem for now... if it happens again on v1 of coopdx or regular ex-coop, make another issue.
