### ISSUE TITLE
Invalid Theme?

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#448]
So TheMan made an issue abt a script error. But what I want to focus on is about a theme script error I get when loading up Tag 2.4. It happens everytime I boot up 2.4, I thought it was a tag issue, but I think it has to do with the theme maker. I've never really used the theme builder so this is interesting. Here's a screenshot of it:
![image](https://github.com/EmeraldLoc/tag/assets/171458695/8cea8610-8a51-4f0d-aebf-9a3ffb83d35b)

**Comment by EmeraldLoc** [comment]
Wow look, a helpful screenshot, thanks

**Comment by Bear64DX** [comment]
ty. hope it's good enough

**Comment by Bear64DX** [comment]
Works perfectly on normal Coop, sad that its a dx only thing.

**Comment by TheMan6900** [comment]
wtf is up with coopdx with tag 2.4

**Comment by EmeraldLoc** [comment]
Just memory stuff. I believe this is fixed next version.
