### ISSUE TITLE
Delete Vanish Cap Walls

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#45]
Simply delete any objects that are meant for the vanish cap

**Comment by EmeraldLoc** [comment]
Why?

**Comment by TheMan6900** [comment]
inaccessible areas

**Comment by EmeraldLoc** [comment]
Where? Those should simply be removed in the tag level data.

**Comment by TheMan6900** [comment]
cant remember, if I find one ill make sure to show you

**Comment by EmeraldLoc** [comment]
Closing this
