### ISSUE TITLE
New modifier - Invisible Walls (April Fools)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#451]
As the title suggest this would be a modifier exclusive to April first, that would add more invisible walls to levels.

**Comment by TheMan6900** [comment]
To go along with this, I think it would be cool to have a whole "event" for special days like this one, like for Christmas, 4th of july, New years, etc.

**Comment by EmeraldLoc** [comment]
Shh, why are you putting this here??!!?!?! (Will add)

**Comment by TheMan6900** [comment]
everyone here knows !!
