### ISSUE TITLE
Retro Remix Castle Boss (w/ cool stuff)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#454]
TheMan originally made a suggestion for this, but I'm making one, because I got some ideas and plus that issue's already closed.
Basically, it'd be the RRC boss arena, where the blueberry bully is. It's not that big of a stage but it'd definitely be fun to play on.
One more thing, there are some secret areas you can access. You just never see them because you always get burnt. Here's an image of them.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/119fb4c4-a1c1-4ce0-ae73-65b81b7b1540)

Oh and also, some springs to recover would be nice.

**Comment by EmeraldLoc** [comment]
Yea, I don't really like this level, I don't think it would be good for tag, so this is a no. The secret areas aren't really helping it's case either.
