### ISSUE TITLE
Level Picture Tags

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#457]
Basically levels, would have tags displaying what gamemodes and modifiers would be in them, in the top right conner of there pictures.
![image](https://github.com/EmeraldLoc/tag/assets/168046906/e62d2a53-6add-41c6-ae01-3a287f25cdb6)

This took less than 10 seconds to draw

**Comment by EmeraldLoc** [comment]
That's a crazy diagram. Now, why? You have 15 seconds to process the gamemode and modifier

**Comment by TheMan6900** [comment]
youd basically be voting for the gamemode and modifier aswell

**Comment by EmeraldLoc** [comment]
Hmm, I see... this does sound pretty cool.
