### ISSUE TITLE
Rainbow Star Haven Remaster Idea

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#459]
Instead of having a ton of pipes, I was planning on making some springs to replace some pipes. Since generally there were too many pipes in that level. I could probably make some launch you to a specific part to the map and prevent softlocks in general

**Comment by TheMan6900** [comment]
Like the changes

**Comment by EmeraldLoc** [comment]
Idk what level this is, uh, sure.

**Comment by Bear64DX** [comment]
idk if im actually gonna cook this im ngl

**Comment by EmeraldLoc** [comment]
Will close this
