### ISSUE TITLE
New Maps

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#46]
Dorries Areas, The Secret Aquarium, Volcano Subarea, Bowser 3 (But fully broken), and The Secret Slide
(Side Note but actually try to organize the level order for base game stages in the start menu)

**Comment by EmeraldLoc** [comment]
A lot of these I won't add, however, I don't mind adding the volcano subarea and dorrie.

**Comment by TheMan6900** [comment]
WAIT WAIT WAIT, add bowsers submarines hideout (dire dire docks subarea)

**Comment by EmeraldLoc** [comment]
Sounds kinda fun actually, good idea

**Comment by EmeraldLoc** [comment]
Done
