### ISSUE TITLE
New modifier - Sword

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#466]
Pretty out there idea but, the sword would basically be its own mini moveset.

Swing: B
Air Swing: A + B

could be more moves, but I tried not to make it to complicated.

**Comment by EmeraldLoc** [comment]
It’s called your fist and diving

**Comment by TheMan6900** [comment]
You know this wouldnt just be the normal combat right

**Comment by EmeraldLoc** [comment]
Something like a sword/hammer makes sense for, say, arena. For tag, it doesn't.
