### ISSUE TITLE
New setting - Language 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#467]
Switches the language of every text in tag.

**Comment by Bear64DX** [comment]
Esta es mi oportunidad de obtener la etiqueta de desarrollo con el traductor de Google.

**Comment by EmeraldLoc** [comment]
*sigh*

**Comment by Bear64DX** [comment]
oh hey emerald if you're gonna add languages can you add modifier help wink wink ;) ? thanks

**Comment by EmeraldLoc** [comment]
> can you add modifier help

If you wanna write them up, I'll gladly make a system so you can write some down.

**Comment by Bear64DX** [comment]
I would, I just don't know code but if you can make a system I'll probably write some down. (you can also include -- in the code as a guide for how I'd make these)

**Comment by EmeraldLoc** [comment]
This is pretty off topic, however in the sign dialogs, in the dialogs file, if you don't mind, could you write some of those out as well?

**Comment by Bear64DX** [comment]
Like for readable signs? Yeah I'll do that but it might take awhile cause my non coding brain doesn't know jack. But yeah will probably do those

**Comment by EmeraldLoc** [comment]
Yea this ship sailed a long time ago

**Comment by Bear64DX** [comment]
New 2.5 feature just drop-
