### ISSUE TITLE
New Achievement - TBLJ

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#468]
Objective: Tag someone from a BLJ
Reward: Nothing

**Comment by EmeraldLoc** [comment]
You can do this?

**Comment by TheMan6900** [comment]
pretty sure you can.

**Comment by EmeraldLoc** [comment]
Ill tell you some new information. You can't hit someone from a long jump.

**Comment by TheMan6900** [comment]
You can hit some one from a blj if your grounded from a blj and use the gained blj speed to kick someone

**Comment by EmeraldLoc** [comment]
This is infact true, detecting such a thing isn't viable though.

**Comment by TheMan6900** [comment]
oh
