### ISSUE TITLE
Dx Stages Music Bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#471]
Music in dx stages dont mute when turning music off.

**Comment by Bear64DX** [comment]
This is because they use OGG files instead of .m64 files. I can't really fix this

**Comment by TheMan6900** [comment]
oh, well close

**Comment by EmeraldLoc** [comment]
> This is because they use OGG files instead of .m64 files. I can't really fix this (also I feel like this would go on the arena stages repo)

This is fixable (I think). You can use a function that I think exists to get the person’s audio, use a linear function thing like in tag, profit. I’ll go ahead and fix this though

**Comment by Bear64DX** [comment]
Once you do that, we'll have to make sure to release DX Stages Hotfix #893749386825094897943898325768635 with how many hotfixes there already are.
