### ISSUE TITLE
Flying w/ Springs

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#481]
I feel like it'd be cool to start flying if you had the fly modifier on while bouncing off of a launch spring (springs that don't just send you straight up). (also I've been kinda lazy w/ tag for now and have been taking a break from deving it, hence the script errors I get when I try to add some info to a modifier help page. It's a mess and it's 100% due to my code so I've been taking a break) (oh and I don't know if this is also already in the game)

**Comment by EmeraldLoc** [comment]
This is done.
