### ISSUE TITLE
Elimination Abuse

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#486]
Make it so if you fall of the stage in a short enough period, with eliminations off (aka falling off the map over and over again abusing the i-frames you get from spawning), youll not be granted i-frames on spawn.

**Comment by EmeraldLoc** [comment]
Just turn it on. Also, you don't get i frames from respawning?

**Comment by TheMan6900** [comment]
you dont? werid

**Comment by TheMan6900** [comment]
guess its just a internet issue
