### ISSUE TITLE
New setting - Fog Color 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#496]
This would let you set the color of fog the same way you can with themes, youd be able to set a color or have it be dynamic, dynamic being basically what fog is now.

**Comment by EmeraldLoc** [comment]
this'll be a no.

**Comment by Bear64DX** [comment]
Honestly feel like this is a cool idea, maybe sometime I'll add this (assuming it'll get added in the final release)
Though this might have to be exclusive to already existing fog colors (like the lava red or haunted purple), unless it's somehow possible to like get the skybox color or smth if it isn't an image (if this is possible i needa know how to do this frfrfrfrfrfrfr)
