### ISSUE TITLE
Random Map Pulling

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#498]
Make maps not pull on disconnect, or when changing modifiers/gamemodes.

**Comment by EmeraldLoc** [comment]
Will still do this when changing modifiers and gamemodes

**Comment by TheMan6900** [comment]
is it not viable or something?

**Comment by TheMan6900** [comment]
is this not viable or something

**Comment by EmeraldLoc** [comment]
When did I say this wasn't viable? It's just not a priority

**Comment by TheMan6900** [comment]
oh... well my brain wasnt brainning

**Comment by EmeraldLoc** [comment]
A lot of this was changed, so the maps are gonna pull if a player disconnects with less than the player count needed for a gamemode..
