### ISSUE TITLE
Remove Hard Backward Fall

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#511]
Remove the action that happens when taking a hard fall backward (dont know what its called). This happens in both unsupported and supported hacks.

**Comment by EmeraldLoc** [comment]
Why am I doing this?

**Comment by TheMan6900** [comment]
> Why am I doing this?

I document everything, ok?

**Comment by EmeraldLoc** [comment]
?

I just don't know why this is needed, if you get into this action, you just have a skill issue, why am I removing this?

**Comment by TheMan6900** [comment]
I dont really have a reason, I just kinda want to see this in the game.
