### ISSUE TITLE
Remove i-frames

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#512]
Make i-frames not activate(?) if you tag someone, but dont change into a runner.

**Comment by EmeraldLoc** [comment]
Believe I got this fixed, if it shows up in a different gamemode, then make another issue.

**Comment by TheMan6900** [comment]
this is not fixed I believe

**Comment by TheMan6900** [comment]
yeah this happens in other gamemodes, and is also not fixed
