### ISSUE TITLE
Disable Abilities

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#513]
Disable Abilities for sardine.

**Comment by EmeraldLoc** [comment]
I think I know what you actually mean, is it that while the sardine is hiding, they can use a blaster?

**Comment by TheMan6900** [comment]
yeah, also now thinking about it, abilities should be disabled for the taggers as well.

**Comment by EmeraldLoc** [comment]
> abilities should be disabled for the taggers as well

?

**Comment by TheMan6900** [comment]
> > abilities should be disabled for the taggers as well
> 
> ? Why?
 
Would be funner. since abilities can some times cheese sardines location

**Comment by EmeraldLoc** [comment]
> since abilities can some times cheese sardines location

These need to get fixed, what modifiers cause that?

**Comment by TheMan6900** [comment]
boost, bombs, and blasters.

**Comment by EmeraldLoc** [comment]
How do these show where the sardine is?

**Comment by TheMan6900** [comment]
No I mean, they give the taggers an unfair advantage

**Comment by EmeraldLoc** [comment]
It's sardines, what do you mean it's an unfair advantage?

**Comment by TheMan6900** [comment]
blasters and bombs, let taggers tag the sardine with the projectiles, instead of having to get up to the sardine and actually punch them

**Comment by EmeraldLoc** [comment]
What's the point of the modifier if it doesn't let them do that? Anyways, will fix the original problem.

**Comment by EmeraldLoc** [comment]
Fixed
