### ISSUE TITLE
Wrongful Github Descriptions

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#518]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/b4ac14cb-7196-41cb-93e7-8a7d4b89bcb0)
![image](https://github.com/EmeraldLoc/tag/assets/168046906/7bde992d-5ecd-4a87-ba33-5d7682301411)

No, arena maps DO have paintings, and there are 10 (about to be 12) gamemodes, not 9. These arent all of them but you get the point

**Comment by Bear64DX** [comment]
No. The description is talking about non-ported arena stages. Ported stages have them just like normal stages would. If you were to load Warehouse (which I haven't ported yet but stay tuned :), there wouldn't be a painting for the level. If Warehouse was an arena stage, it'd automatically have pipes. Pipes are determined by the stage you're porting. If you're porting an arena stage, it automatically generates pipes based off of the CTF flags. However, it does not generate a painting for said level. You're correct about the gamemodes though, there are currently 10 (terminator) gamemodes in Tag.

**Comment by TheMan6900** [comment]
Oh didnt know that.
