### ISSUE TITLE
Goofy Dialog w/ certain NPCs

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#520]
While testing 2.4, I noticed that the CCC penguin was glitched out.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/aa66ecb0-3679-4ae5-99e9-40a119db931b)
This also happens with QTK as well.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/fb051fbf-645b-46f4-b1cb-cc362d77e8c2)
Oh, and you can race both of them btw.
Another bug I found w/ CCC is that there's just some penguin "chilling" at the bottom of the slide. (I have no idea what he's doing there)
![image](https://github.com/EmeraldLoc/tag/assets/171458695/78406c6a-a390-4cd3-97f0-3c36768c68c7)

**Comment by EmeraldLoc** [comment]
That’s the race penguin

**Comment by Bear64DX** [comment]
Yeah. I was also just letting you know abt another bug at the end of the slide.

**Comment by EmeraldLoc** [comment]
Generally should be resolved, since you no longer actually interact with the npc's
