### ISSUE TITLE
2.4 voting doesn't work?

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#522]
Okay, so this is kind of hard to explain but I was testing 2.4. And when I got to the voting screen, it didn't let me do anything. I was testing this w/ Star Road and 2.4. It seems like voting just doesn't work in 2.4

**Comment by EmeraldLoc** [comment]
Is this still the case?

**Comment by Bear64DX** [comment]
Let me download 2.4, and I will test this.

**Comment by Bear64DX** [comment]
This bug still occurs, the bug where you can't enter the tag menu/cant move in the tag menu when the round is ended also still occurs

**Comment by Bear64DX** [comment]
Lemme explain that better, if the round ends and you pause, it's the vanilla pause screen, and you can't open the Tag menu. And if you have the tag menu open while the round has ended, you can't do anything. None of these bugs were in 2.3

**Comment by EmeraldLoc** [comment]
Fixed
