### ISSUE TITLE
2.4 Randomly slowing down?

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#526]
Alright, so how do I explain this.... The game basically just slows down whenever it feels like it. I have no idea why this is the case, but here's what it looks like (I guarantee you its not my pc, it only happens in 2.4, and it happened to tm and saus as well.)

https://github.com/EmeraldLoc/tag/assets/171458695/d8f16e87-5c9f-435a-a6e3-b974e5e1ba11

**Comment by EmeraldLoc** [comment]
Will take a look at. This isn’t that big of a deal, but  when hosting with other players, I’d like to know just in case I don’t believe the mods acceptable even for a small test. In this case probably would have said yes. Plus what if I want to play too??!!?!?!?

**Comment by Bear64DX** [comment]
> Plus what if I want to play too??!!?!?!?
Well you can send me a DM and we can do just that! (w/ 2.4 and custom maps)

**Comment by EmeraldLoc** [comment]
Was this issue exclusive to when the gamemode was set to oddball? If so it's been fixed.

**Comment by Bear64DX** [comment]
It was with other gamemodes as well.

**Comment by EmeraldLoc** [comment]
Hmm... gonna assume fixed for now, if it happens again open up another issue.
