### ISSUE TITLE
Shell Bonk

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#527]
When hitting a wall with the shell modifier, the triangle particle effect (that plays when punching or kicking a wall) would play.

**Comment by EmeraldLoc** [comment]
You don’t bonk with a shell so I don’t see why this is here

**Comment by TheMan6900** [comment]
No I mean like

**Comment by TheMan6900** [comment]
When you hit a wall and you slow down

**Comment by EmeraldLoc** [comment]
Ah I see

**Comment by TheMan6900** [comment]
kinda mario kart like in a sense

**Comment by EmeraldLoc** [comment]
Added
