### ISSUE TITLE
Grounded Hiding Screen

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#530]
When on the "hiding" screen in sardine and search, your grounded position would be set to your last x, y, z coords (exactly how the old sardine hiding worked)

**Comment by EmeraldLoc** [comment]
Wait, is this for taggers on the waiting screen? If so, what's the reason?

**Comment by TheMan6900** [comment]
for taggers, would just be nice for the odd case where get hiding screen'd at a bad spot

**Comment by EmeraldLoc** [comment]
Skill issue
