### ISSUE TITLE
Sliding On Non-slippery

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#534]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/2ad24edf-2c15-4bb0-8d58-0be1d059d513)
(this is another player btw)
this surface is made non-slippery through api, this doesnt actually do anything, it just looks werid.

**Comment by Bear64DX** [comment]
It does make the surface non slippery, It's still possible to slide on it by doing something like a Dive due to the game's geometry. You can easily get back up as it's not truly "slippery"

**Comment by TheMan6900** [comment]
no like butt sliding

**Comment by Bear64DX** [comment]
Why this happens is beyond me. But it's not actually slippery.

**Comment by EmeraldLoc** [comment]
That's most likely due to that surface being treated as a wall, can't really do anything about it.
