### ISSUE TITLE
-1 Lives

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#539]
I was goobering around w/ TM in a priv 2.4 server, since he wanted to help me reproduce the big radar bug. Turns out we discovered something worse. When I fell off the map with 1 live in Hunt, I got -1 lives instead of getting eliminated.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/adf30498-1694-45f3-9e94-6a330de2349f)

**Comment by EmeraldLoc** [comment]
Nice

**Comment by Bear64DX** [comment]
Oh and btw, you can infinitely fall down by yourself if you have -1 lives, it's basically a kill yourself to win method.

**Comment by EmeraldLoc** [comment]
Did theman show your lives as -1 as well?

**Comment by Bear64DX** [comment]
He said my lives were indeed -1, which was true. We both had this glitch happen to us

**Comment by EmeraldLoc** [comment]
Fixed
