### ISSUE TITLE
Arena Stage Porter Tag

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#541]
I'm not biased (i made this issue as a joke but itd be kinda cool? i think?)

**Comment by EmeraldLoc** [comment]
I don't even know what this means which is awesome!

**Comment by Bear64DX** [comment]
Just a tag similar to Rom Hack porter, where if you ported an arena stage to tag, you get the title or smth. Sounds cool to me

**Comment by EmeraldLoc** [comment]
OH, I see. Don't think I'll add this however, since it isn't really specific to editing the actual tag mod.
