### ISSUE TITLE
Swap Fall Damage

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#542]
So basically, if you swap while falling from a high place to someone on the ground, you'll take fall damage (you wont take damage but you'll get the animation). The best way to replicate this is to go to Cloudy Quadrangle w/ swap, have someone be on the ground, and when the meter shows up, fall from the blimp. Me and TM were able to replicate this easily. 

https://github.com/EmeraldLoc/tag/assets/171458695/535d27d5-50d4-45fb-8050-0e373fbfd014

**Comment by EmeraldLoc** [comment]
Ah, funny

**Comment by Bear64DX** [comment]
real

**Comment by EmeraldLoc** [comment]
Not anymore
