### ISSUE TITLE
Big Radar

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#545]
So I was goofing around w/ TM in 2.4, and when he hit me, I not only got absolutely FLUNG but I also got this
![image](https://github.com/EmeraldLoc/tag/assets/171458695/988a04c6-025b-4082-a509-438c4a95cc2b)

**Comment by TheMan6900** [comment]
Pretty sure this happens from the OOB failsafe

**Comment by EmeraldLoc** [comment]
Bear can you send me the pass for this lobby so I can check this out?

**Comment by Bear64DX** [comment]
alr
