### ISSUE TITLE
New Setting - Pages

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#550]
For menus like blacklist and start, menus that list a bunch a stuff, would have its contents be split into mutiple pages, to make it easier to navigate.

15 contents per page, and pages would be scrolled through with R and L trigger or bumper.

**Comment by EmeraldLoc** [comment]
prob 2.5

**Comment by Bear64DX** [comment]
2.5 release when

**Comment by EmeraldLoc** [comment]
Some things I simply dont have the energy for and/or I dont see as a high priority at all, this will probably never get added.
