### ISSUE TITLE
JRB Division

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#551]
I had a little idea for JRB. I was thinking that JRB could be split into 2 parts, the ship, and the cave. There'd be blocks near the cave that'd block the entrance to the cave/exit to the ship (just like how shine thief has blocks). The painting for the ship would be the ship painting (the current one, while the cave painting would be the JP JRB painting (and yes, jrb has different paintings in jp and in usa)

**Comment by EmeraldLoc** [comment]
I think it works pretty well as 1 map, so nah.

**Comment by Bear64DX** [comment]
I kinda just wanted the JP painting to be used lol
