### ISSUE TITLE
JRB Softlock

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#554]
https://github.com/EmeraldLoc/tag/assets/168046906/dc06bfa5-c6c2-46e3-a3c1-32ab5f1938cc

**Comment by EmeraldLoc** [comment]
How did you do that in the first place?!?!?!?!? Can other players hit you in that position? If so, I'm leaving it in so this encourages ppl not to clip into the ship.

**Comment by TheMan6900** [comment]
for like a frame or so yeah (I think)

**Comment by EmeraldLoc** [comment]
Perfect.
