### ISSUE TITLE
Spring Wall Collision

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#557]
Make it so that you can hit the wall (aka softbonk) when your spring bouncing, until you reach the peak up the bounce

**Comment by Bear64DX** [comment]
PEAK

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
You basically wouldnt be able to bonk while spring bouncing

**Comment by EmeraldLoc** [comment]
So.... you mean that you want it so when you are NOT past the peak height, you DON'T bonk, but when you PAST the peak height, you DO bonk? Because that sounds good.

**Comment by TheMan6900** [comment]
Just make it so you just, cant bonk when bouncing off a spring, thats lot less confusing.

**Comment by EmeraldLoc** [comment]
There is not wall sliding in Tag. That's not apart of the vanilla moveset. I think I should just revert the change adding momentum to springs, since it does cause a headache for what a good spring placement is for romhack porters.

**Comment by Bear64DX** [comment]
> There is not wall sliding in Tag. That's not apart of the vanilla moveset. I think I should just revert the change adding momentum to springs, since it does cause a headache for what a good spring placement is for romhack porters.

BROOOOOO LETS GOO!!!!! THIS IS THE BEST CHANGE EVER :D Seriously though, it was kinda hard landing the placement on springs. Especially in Spire, where you have to perfectly go on the vertical spring. I was happy about my spring placements in GS but was kinda sad that it was kinda ruined by the momentum change. SO TYSM EMERALD I APPRECIATE IT! :D
