### ISSUE TITLE
Non-Sardine air hiding.

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#564]
I feel like it'd be neat if you couldn't hide in the air. Everything just feels way too accessible with 

https://github.com/EmeraldLoc/tag/assets/171458695/4b0fbe6a-33d1-4458-86a4-c4756a8e3a25

hiding in the air. It just feels weird that you can do this. Plus, there's a lot of broken hiding spots. I'm not sure if you can use smth like a fly guy to get an impossible spot. Oh, and you can also get into an infinite death loop w/ this. I mean just look at this, this is ridiculous. This was tested in Search, so I'm unsure if this works in Sardines. But it'd still be nice if this wasn't in the game imo.

**Comment by TheMan6900** [comment]
air sardine is a lot more balanced than grounded sardines

**Comment by Bear64DX** [comment]
Really? If anything, it's just unbalanced cause of the sheer amount of spots with this

**Comment by TheMan6900** [comment]
grounded sardine is way more limited and just less fun

**Comment by EmeraldLoc** [comment]
There are benefits to being able to hide in the air along with the ground, however being able to hide in the air causes there to be a lot of annoying, unreasonable spots. Ground is a lot more safe, and generally more balanced imo. Only reason the air thing exits is similar to search, ppl really wanted me to add it (which, isn't there fault btw, I should have thought about it and just stuck with what I thought).

> air sardine is a lot more balanced than grounded sardines

I just disagree with this statement, and agree with what bear said here:

> Really? If anything, it's just unbalanced cause of the sheer amount of spots with this

> grounded sardine is way more limited and just less fun

There are some cool spots you could go to with being able to hide in the air in sardines/search, however the downsides are greater than the ups.

And that's my list of opinions, hope you enjoy!!!! Will come to a definitive conclusion about this later.

**Comment by Bear64DX** [comment]
I agree with what you said and I think that is an amazing response to this issue.

**Comment by Bear64DX** [comment]
(I do believe that not everything should be added because people want it to. The internet doesn't have good ideas half of the time I'm gonna be real)

**Comment by TheMan6900** [comment]
> (I do believe that not everything should be added because people want it to. The internet doesn't have good ideas half of the time I'm gonna be real)

Fr

**Comment by EmeraldLoc** [comment]
Added
