### ISSUE TITLE
New gamemode - Survival 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#566]
Basically like the throne gamemode suggested, but assassinified.

Youd have the same timer, but youd have to tag a specific person instead (would be on the same list as in assassins)

**Comment by Bear64DX** [comment]
That name hits hard ngl

**Comment by TheMan6900** [comment]
thanks :)

**Comment by EmeraldLoc** [comment]
I don't know how much I like this one, I think I'll stick with the 1 gamemode.
