### ISSUE TITLE
Backward Softbonk Infinite Speed

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#568]
Cap softbonks negative speed

**Comment by EmeraldLoc** [comment]
Does this happen with a certain modifier? If so it's been fixed.

**Comment by TheMan6900** [comment]
Happens with speed modifier and boosting, this can be replicated with the double bonk glitch

**Comment by TheMan6900** [comment]
Just fall off a ledge or softbonk with it and you go flying

**Comment by EmeraldLoc** [comment]
Fixed
