### ISSUE TITLE
New setting - Rubberbanding

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#569]
the further you are from a runner the faster you go (would go up to a 1.05x speed boost)

**Comment by TheMan6900** [comment]
Wow I'm surprised you didn't just label this issue a "skill issue" and close

**Comment by EmeraldLoc** [comment]
Woah wait a minute this is a dumb request

**Comment by TheMan6900** [comment]
Ain't no way bro just waited for me to speak just to dunk on me
