### ISSUE TITLE
GS Telephoto Lens w/ Freecam

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#577]
Hey, so I'm not sure if this is possible to fix or not, but basically if you go into Freecam and you hold L with Freecam on, you'll get a telephoto lens view, which is normal. The problem is that the camera also follows you when you hold L. This is intended, but the problem is that they interrupt eachother, which basically means the camera follows you while you hold L. I'm a HUGE fan of the Telephoto Lens cam that comes with Green Stars, it's just annoying that it's wonky when used with freecam. I understand if this cannot be fixed. (Also I just realized that this isn't really a tag issue. It's just annoying and the hack is in tag so I thought I'd report it)

**Comment by Bear64DX** [comment]
Oh yeah, another thing I found is that you can't go into Mario Cam w/ the vanilla cam (in gs)

**Comment by EmeraldLoc** [comment]
Yea this can't be fixed.

**Comment by Bear64DX** [comment]
That's what I thought. rip
