### ISSUE TITLE
Addon Documentary

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#578]
Recently, I've been digging deep into making addon stages for Tag. I've made some of them, and I've learned a lot over my research.
I was wondering if I could write a document on how to use the add_level function in order to add an addon level. I'd need to learn how to make .MD files for Github, but I think I would be able to write one.

**Comment by EmeraldLoc** [comment]
Sure. It's just markdown, so if you learn that it'll be pretty clear.
