### ISSUE TITLE
Tag Credits

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#579]
A cool idea that I think would be cool is that there'd be an option in the menu that allows you to see the people who worked on Tag. Even if it's small, it'd still be nice. I know there's credits in the Changelog, but those aren't just direct credits. They're only in the RH port credits.

**Comment by EmeraldLoc** [comment]
Yea I could prob write something up for this, with each player having information about them, i.e their discord username, modding site name, github username, etc.

**Comment by Bear64DX** [comment]
Sounds good, I'd probably just be fine w/ my Github user there tbh (Also I don't think people who made suggestions would be on the credits unless they actually dev'ed something)

**Comment by EmeraldLoc** [comment]
added
