### ISSUE TITLE
Tag launch spring model

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#587]
Make the launch spring base longer so it can fit on more terrain

**Comment by Bear64DX** [comment]
I'm no expert but I'm not entirely sure if this is possible unless .blend files for the spring already exist, since the spring's model is technically split into 2 parts. I'm not sure if having the .c files to the model would help either.

**Comment by EmeraldLoc** [comment]
Can't really do much, not in the mood to do this in c files either.

**Comment by Bear64DX** [comment]
gotta love mid-c (wait i cant make a joke abt c its literally one letter-)
