### ISSUE TITLE
"Questions" about the Button Challenge

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#589]
Okay so I don't want to sound like the guy who always complains (even tho I am the guy who always complains), but I wanted to talk about this specific modifier. Okay so how do I start this... do you by chance know why this was added in? I know we had a discussion about "bad modifiers" in Tag. But High Gravity, and Sandy Floors are nothing compared to this. I know that there being bad modifiers is intended, but this straight up just doesn't make the game fun imo. How I look at it is that Tag is a fun mod where you can play with friends and have a fun time with fun gamemodes. This however? Nah nah nah, complete opposite. Sure, high gravity and sandy floors aren't fun, but they're nothing compared to this. I know that it can also be the Z button that gets disabled, but that still doesn't really save it from the fact that there's a chance for it to be the A button. And when it IS the A button, it is NOT fun at all. Overall. I definitely think that the "Bad Modifiers" situation may have just gone a biiiit too far. Am I overreacting? I don't know, but I'm not 100% sure if this should have been added in.

**Comment by EmeraldLoc** [comment]
I ain’t reading all of that. I already said I’ll remove it dw
