### ISSUE TITLE
New modifier - Slippery Floors

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#59]
This would make every floor slippery

**Comment by EmeraldLoc** [comment]
First version of tag had this, it was very unenjoyable

**Comment by TheMan6900** [comment]
I really dont see why this isnt added espically since sandy floors was added

**Comment by EmeraldLoc** [comment]
*sigh*

This was in v1 of tag. it sucked. it was removed. sandy floors is 500000x different.
