### ISSUE TITLE
New gamemode - Spotlight

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#593]
Kinda like juggernaut, but hot potato

Basically in this game mode, one person would be the spotlighted player, which everyone would have to get. If no one was able to get the chosen player (lets say 10 or 20 seconds, could be adjustable in settings), that player would live on, if someone was able to get that player, they'd be eliminated.

The goal of the game isto be the last man standing, or just to not get eliminated within a 180 second time lot. There could a 3 second intermission between spotlights.

**Comment by Bear64DX** [comment]
So like hot potato w/ one runner modifier no? (This kinda seems similar to the Throne gamemode we suggested as well)

**Comment by TheMan6900** [comment]
I mean it wouldn't be just one runner

**Comment by TheMan6900** [comment]
I feel like the shorter timer would help keep the game from dragging on though

**Comment by EmeraldLoc** [comment]
The other gamemode should be called spotlight, this one feels like the other gamemode recycled.
