### ISSUE TITLE
Hot Potato Rebalancing

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#594]
I think you're aware that depending on how many people are currently not eliminated, the faster the timer goes. This makes it unfair for the people who get chosen as taggers on the first round, since you have barely any time to tag someone. I think a fix for this is to make the timer shorter (eg: 30 sec > 22 sec), but also not make it blazing fast so you actually have time to tag people. I don't know if this is a good solution but it makes it unfair for people who taggers on the first round.

**Comment by EmeraldLoc** [comment]
This just needs to be rebalanced. It's hard because on one hand you don't want the game to be long, but on the other hand you want to give taggers time.

**Comment by Bear64DX** [comment]
That's basically what made it so hard. It's hard to make it fair for everyone, but not make the game last the same amount of time as a 50 turn Mario Party game would be.

**Comment by Bear64DX** [comment]
was it added..?

**Comment by EmeraldLoc** [comment]
I rebalanced hot potato, that's all, didn't do what you said to do here, did what I thought would work. All changes made right now are on a local build.

**Comment by Bear64DX** [comment]
Oooh nice, ty!
