### ISSUE TITLE
Scripting error #9 (2.4)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#596]
![image](https://github.com/EmeraldLoc/tag/assets/171458695/398a0648-b08c-4c8e-8d66-a3be742261c6)

Got this when joining on my alt, it seems like themes just can't stop getting worse.
For more context, I didn't do anything special. All I did was just join on my alt. I even refreshed my mods.

**Comment by TheMan6900** [comment]
2.4 be very stable

**Comment by EmeraldLoc** [comment]
What’s an alt. Is it on the same pc?

**Comment by Bear64DX** [comment]
I call it an alt. It was a direct connection on the same PC. That may have something to do with it, however I always use that for testing

**Comment by EmeraldLoc** [comment]
I’m gonna close this, since I’m unsure if this is a coopdx save issue or not, if you get it when I get you my custom build, then we can talk.
