### ISSUE TITLE
Save file getting wiped

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#597]
![image](https://github.com/EmeraldLoc/tag/assets/171458695/284a07ea-b7ba-4fe2-b1dc-56915c04f600)

I just loaded up 2.4, what even happened-

Oh, and the game crashed btw. And now I can't even boot up 2.4 at all.

**Comment by EmeraldLoc** [comment]
That’s cuz your save just got wiped

**Comment by Bear64DX** [comment]
IT GOT WIPED 3 TIMES IN A ROW?!?!?! If you could tell me how I could get the old save function to DX I'd appreciate it, what is even happenening

**Comment by EmeraldLoc** [comment]
Yea I can tell you in a bit

**Comment by Bear64DX** [comment]
Alright, talk to me on the modsite, we can figure this out.

**Comment by EmeraldLoc** [comment]
Is it happening consistently?

**Comment by Bear64DX** [comment]
I restarted the game like 5 times now. Lemme take a look at my save.

**Comment by Bear64DX** [comment]
Ok, the save file got wiped. Adding the "special key" fixed it though.

**Comment by Bear64DX** [comment]
Oh, and if you're wondering what the save file looks like, it looks like this: (the key was cut out)
[storage]
stats_global_totalTimeAsRunner=h3qe64hez5avwv
stats_1_totalTags=h3qe64he5d
stats_global_totalTags=h3qe64hez_y
encryptionKey1=avb8cbd0e_fagghwiqj.kdllm-n2o1ptqnrisxt
encryptionKey2=5upvkwexyycz61u2h344j5m6f778r990o_z-s.3
achievement_1=5vgz811lz5ip_

**Comment by Bear64DX** [comment]
Good news, I used the backup save file to restore the stats I had. I don't want to encounter this though.
