### ISSUE TITLE
Scripting Error #10

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#599]
Was playing 2.4 w/ my good friend Saus, when all of a sudden I got a script error in Oddball. I was a runner and I died, so I should've been turned into a Tagger. I was still a runner and this error showed up:
![image](https://github.com/EmeraldLoc/tag/assets/171458695/146e9ec3-fb42-4895-9774-643ca63d58f1)

**Comment by EmeraldLoc** [comment]
Fixed
