### ISSUE TITLE
Consider wind as hazards

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#6]
Pretty simple make, both vertical and horizontal winds grouped in the hazardous terrain toggle (to along with this the toggle itself would just be renamed to "Stage Hazards")

**Comment by EmeraldLoc** [comment]
Wind is used to navigate the level, and should not be considered a hazard

**Comment by TheMan6900** [comment]
fair

**Comment by TheMan6900** [comment]
now thinking about it why is horizontal wind not just disabled in tag, it has literally 0 purpose other than to slow you down.
