### ISSUE TITLE
Oddball timer going to -1

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#600]
![image](https://github.com/EmeraldLoc/tag/assets/171458695/0445bee8-27b1-4505-bb75-52859d49d210)

**Comment by EmeraldLoc** [comment]
When saus became a runner again, did the round end or did it stay the same?

**Comment by Bear64DX** [comment]
He didn't become a runner. I won the game. Oh btw, I tagged him when he was at -1, so it was perfectly timed.

**Comment by EmeraldLoc** [comment]
Ah, k, easy fix then

**Comment by EmeraldLoc** [comment]
Fixed
