### ISSUE TITLE
Muti sardine idea

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#602]
If there were to be multiple sardines, the taggers would have to fine, all the sardines and not just one

**Comment by Bear64DX** [comment]
That's what it's supposed to be like.

**Comment by EmeraldLoc** [comment]
Hmm... coulda recalled I had an idea to do this very thing instead of adding search as a separate gamemode, and have the one tagger and runner modifiers handle the other stuff... Either way, this is too close to hns for comfort.

**Comment by Bear64DX** [comment]
ONE TAGGER SARDINES PLEASE NO

**Comment by EmeraldLoc** [comment]
literally was search 💀

**Comment by Bear64DX** [comment]
💀

**Comment by TheMan6900** [comment]
💀

**Comment by TheMan6900** [comment]
💀

**Comment by TheMan6900** [comment]
> Hmm... coulda recalled I had an idea to do this very thing instead of adding search as a separate gamemode, and have the one tagger and runner modifiers handle the other stuff... Either way, this is too close to hns for comfort.

Wait wouldn't that just make sardines easier though?

**Comment by Bear64DX** [comment]
What are you talking about? The one runner modifier? Cause if so, yeah that'd make this way easier.

**Comment by TheMan6900** [comment]
Yeah
