### ISSUE TITLE
Make normal knockback the default 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#607]
The other two just don't work for tag

**Comment by Bear64DX** [comment]
What do you mean by "other two"?

**Comment by TheMan6900** [comment]
Weak and too much (yes thats what its called) knockback

**Comment by EmeraldLoc** [comment]
I'm not gonna control that, if you wanna host with that, go ahead, otherwise, don't join a lobby that has that.

**Comment by Bear64DX** [comment]
Maybe there could be a pop-up that tells you the knockback. It's hard to see what the knockback on a server is before it's too late.
