### ISSUE TITLE
Double Jump Lava Boost

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#609]
Okay so I'm not sure if this would get added, but I thought it'd be cool if you could set the Double Jump to be a lava boost instead of a normal double jump.

(also if you're reading this uhh please add double jump twirl ok bye! you dont actually have to add this infact I need to dearly apologize for my sins of begging you to add this)

**Comment by TheMan6900** [comment]
You've suggested the twirl double jump like 5 times by now, I don't think he'll be adding it, either way cool idea

**Comment by Bear64DX** [comment]
> You've suggested the twirl double jump like 5 times by now, I don't think he'll be adding it, either way cool idea

real

**Comment by TheMan6900** [comment]
Twirl double jump is dope, I'm just saying

**Comment by Bear64DX** [comment]
> Twirl double jump is dope, I'm just saying

I agree with that on my soul

**Comment by EmeraldLoc** [comment]
> infact I need to dearly apologize for my sins of begging you to add this
 
 You better 😈 
 
 I'd rather add the twirl than this, not adding any of it though.

**Comment by Bear64DX** [comment]
> > infact I need to dearly apologize for my sins of begging you to add this
> 
> You better 😈
> 
> I'd rather add the twirl than this, not adding any of it though.

WAIT YOU'RE ADDING THE TWIRL LES G-
