### ISSUE TITLE
Improved Flying Physics

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#615]
Make it so that when flying straight, no joystick inputs, you just go straight instead of upwards or a direction that your not inputting (for some reason)

**Comment by Bear64DX** [comment]
We should suggest more ideas for the Fly modifier and then ask Emerald to make a modifier setting for Fly. There could be a "Tag" version of Fly that adds stuff like controllable speed, and what you just suggested. And there could be a "Vanilla" setting that is literally just vanilla Wing Cap with no adjustments whatsoever.

**Comment by EmeraldLoc** [comment]
I want the wing cap to fly like the vanilla one, thus I'll keep it like the way it is.
