### ISSUE TITLE
Removing MMM

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#616]
Another suggestion that might not get added but I kind of want to clear this up.
Mad Musical Mess has never been my favorite level, even in the actual Star Road rom hack. I don't know why it's really in tag, but if Cloudrail Station wasn't added because it's trash, then idk how MMM made its way into the pack. It's your decision if you want this level to stay, but with all the tight platforming and not having a good overall structure for Tag, I would recommend this got removed. But these are just my opinions, and I'm not the one who controls the levels. Oh and yeah, this is the most controversial issue I've posted

**Comment by TheMan6900** [comment]
Anything that gets added is permanent

**Comment by TheMan6900** [comment]
RRC can be fixed though, just make the spikes non-slippery

**Comment by Bear64DX** [comment]
> RRC can be fixed though, just make the spikes non-slippery

RRC getting removed isn't my point. I don't want to constantly argue about this. I want us both to agree that this level shouldn't have gotten added in the first place. It's a platform level, it's not really flat, and it's just bad.

**Comment by EmeraldLoc** [comment]
WHAT! I'm not removing Retro Remix Castle!!!

I mean, you give a really good point with cloudrail station, cuz mmm is a millennium worse than mmm........ so the 2 options I have are removing MMM or adding CS, in order to be consistent. I think MMM is kinda funny, is it good? Absolutely not, but its good in another way. Cloudrail station.... I mean it's just kinda meh. Idk. I'll probably add cloudrail station. Still need to think about it a bit more, look at the cloudrail station level, etc.

**Comment by Bear64DX** [comment]
I don't know if CS would be good. However I'd be happy if that replaced this level. MMM can be funny, but just because its funny doesn't mean it should stay. (also I don't wanna remove RRC I just said Murioz said he might remove it) How about this, you remove MMM and replace it with CS. Or just remove MMM entirely. (Or the third option is to keep MMM and I add as many stages to GS as I want to even if they're bad >:D

**Comment by Bear64DX** [comment]
I do agree that RRC shouldn't get removed. I was just making a point that it IS 100% possible to remove Stages, cause tm didn't really think that.

**Comment by EmeraldLoc** [comment]
> How about this, you remove MMM and replace it with CS. Or just remove MMM entirely. (Or the third option is to keep MMM and I add as many stages to GS as I want to even if they're bad >:D

I personally think the 4th option is best. Fill the entire stage with a ton of springs.

**Comment by Bear64DX** [comment]
This actually aging better than Kirby in Smash 64

**Comment by Bear64DX** [comment]
My final idea is to just remove MMM and not add CS. Star Road is a good hack, but not every level needs to be added. That being said, they're both equally garbage so I'd say remove MMM and not add CS.

**Comment by Bear64DX** [comment]
I do just want to get out load and clear that I don't want RRC to get removed. This conversation kind of devolved into removing RRC. I never wanted to remove RRC anyway, I made that as an example to understand that stages can get removed easily. I'm not exactly sure how the conversation devolved into removing that, as it was never my plan to begin with. I just want MMM gone, and nothing else.

**Comment by TheMan6900** [comment]
My point was that I don't like just having elements of tag just randomly get added and removed.

**Comment by TheMan6900** [comment]
I personally don't care about quantity as long as it's still quality

**Comment by EmeraldLoc** [comment]
Holy thats a lot of messages

I played both MMM and CS again, and I think I'm keeping it the way it is. MMM is very similar to the ttc and wc of vanilla sm64, and I think it works great that way! CS, well, there's just too much. It's so big, and most of the areas require a specific path to get to them. Springs wouldn't help a whole lot, unless I want to make a spring travel a unreasonable gap, it just doesn't seem like a good stage for this.

> [this] is a perfect example of Quantity > Quality

I believe the stage has it's place, it's great for good players to go ahead and do advanced and risky tricks on, it's very similar, as stated above, to ttc and wc.

> I don't like just having elements of tag just randomly get added and removed.

If it's for the better of the mod, it should happen, the idea of removing content should always be open.

> I don't care about quantity as long as it's still quality

Of course!

Will close this now.
