### ISSUE TITLE
New achievement - Mad Musical Master 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#618]
Objective: Win on MMM, 20 times.
Reward: Nothing

**Comment by Bear64DX** [comment]
I feel like I got spited

**Comment by EmeraldLoc** [comment]
Desperate 💀

**Comment by Bear64DX** [comment]
> Desperate 💀

Honestly 💀

**Comment by TheMan6900** [comment]
I kinda just got reminded of this dumb idea I had like a week ago, sorry 💀
