### ISSUE TITLE
Modifier Setting - Gravity

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#619]
Instead of having a low gravity or high gravity modifier, it'd be one modifier that changes (Not in round). Basically, you could make it so that you can set it to low gravity or high gravity. You could even make it random if you want! But I'd have it just be low gravity for obvious reasons.

(Speaking of modifier settings, actually I'm not gonna sugarcoat it. Add it, You know what I'm talking about. And yes, I'm desperate okay?

**Comment by EmeraldLoc** [comment]
No, just blacklist the high gravity modifier, same result!!!

**Comment by Bear64DX** [comment]
Oh yea I forgor
