### ISSUE TITLE
New modifier  - volcano 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#623]
This modifier would spawn in a giant volcano, that would shoot out lava rocks, that would shoot out sharpenal when hitting the ground, that would hurt the player on contact.

**Comment by Bear64DX** [comment]
I kinda had an idea for this same modifier. I just didn't post it because packets

**Comment by EmeraldLoc** [comment]
Yea packets are a problem.... also shoving a volcano in the middle of the map won't work for every map lol
