### ISSUE TITLE
New gamemode - royale

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#625]
Basically you'd have a tag threshold to fill, once filled you be labeled "finished" and would, well win.
You'd be able to tag anyone to fill this threshold.

**Comment by Bear64DX** [comment]
Frenzy is a perfect name. I didn't even think of that.

**Comment by TheMan6900** [comment]
Oh lel.

**Comment by EmeraldLoc** [comment]
So...... you have to tag any player, say, 10 times, first to do that wins... that kinda gamemode?

I feel like this gamemode already exists, and has a different name (not in tag, just in general)

**Comment by TheMan6900** [comment]
Nope doesn't exist. Also yes that's how you win.

**Comment by EmeraldLoc** [comment]
Frenzy isn't really a name for a gamemode, I'd rather this be a different one

**Comment by TheMan6900** [comment]
What about vampire? Or smth

**Comment by Bear64DX** [comment]
I am vampire. I suck blood. Suck suck suck

**Comment by EmeraldLoc** [comment]
ig vampire would work, if there's a better name I'd like to know that first

**Comment by EmeraldLoc** [comment]
Frenzy doesn't really make sense as a name for this, and just isn't really a gamemode name imo

**Comment by Bear64DX** [comment]
Hmmm....

**Comment by Bear64DX** [comment]
Wait this gamemode could be caleld Royale. That name hits HARD

**Comment by TheMan6900** [comment]
YEA

**Comment by EmeraldLoc** [comment]
Added
