### ISSUE TITLE
Royale (Teams)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#633]
The Royale gamemode probably has to be my favorite. I mean, it's a really fun concept in general. However, I think it'd be cool if there could either be a new gamemode that's royale but w/ teams (havent decided a name) or just make teams a seperate option w/ Royale. (Could also be random)

**Comment by TheMan6900** [comment]
How would a Royale team gamemode variant even work?

**Comment by Bear64DX** [comment]
You'd have teams, one person on a team has to get the amount of tags needed to win.

**Comment by TheMan6900** [comment]
Oh

**Comment by EmeraldLoc** [comment]
Would be apart of the Team setting that may or may not come in 2.5, so adding this as a comment there would be better :)
