### ISSUE TITLE
Goofy Achievements

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#638]
For some reason, Tag says that I have every achievement unlocked, even though I don't. Here's the pics:
![image](https://github.com/EmeraldLoc/tag/assets/171458695/6a44ad0e-e88f-405f-8d3f-eca0e60393dd)
![image](https://github.com/EmeraldLoc/tag/assets/171458695/e7b66e03-af63-44cb-ae03-831a5b78db22)

I could be dumb or smth but idk what's going on.

**Comment by Bear64DX** [comment]
I forgor to put a description hold up 💀

**Comment by EmeraldLoc** [comment]
This still happening? Can't really see why this would happen....

**Comment by Bear64DX** [comment]
Hmm. Lemme boot up the latest 2.4 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/34d05ba8-f6b6-4f40-b95e-19febea33e04)

**Comment by Bear64DX** [comment]
Still happens 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/feb6e5bc-f706-434e-b420-e26fd67668b5)

**Comment by EmeraldLoc** [comment]
Can you send some of your save file?

**Comment by Bear64DX** [comment]
Alr, here it is. (I'm not sure how to mark it as code, as in highlighting. So uhh sorry about that lol)
[storage]
encryptionKey1=a3b-crdkelf7gqhii6j8kglcmtn4ompsqur2s9t
encryptionKey2=huxvbwnxfy1zo1z2y354_5v607a8j9w0d_e-..p
stats_6_playTime=h3qe64hez000wd
stats_global_playTime=h3qe64hew__v5w
stats_6_totalTags=h3qe64hezzj
stats_global_totalTags=h3qe64he5w_
stats_4_playTime=h3qe64he_jv0jv
stats_4_totalTimeAsRunner=h3qe64heydwady
stats_global_totalTimeAsRunner=h3qe64he5ya_dd
stats_4_totalTags=h3qe64hej0
stats_2_playTime=h3qe64he_awavw
stats_2_totalTimeAsRunner=h3qe64heywzw05
stats_2_totalTags=h3qe64he55j
stats_4_runnerVictories=h3qe64he5_
stats_global_runnerVictories=h3qe64hey0j
stats_8_playTime=h3qe64headyd_y
stats_8_totalTimeAsRunner=h3qe64he_0djd0
stats_8_totalTags=h3qe64heyza
stats_3_playTime=h3qe64heywa05v
stats_3_totalTimeAsRunner=h3qe64hezy0ja0
stats_3_totalTags=h3qe64hezz5
stats_1_playTime=h3qe64hezdzj5v5
stats_1_runnerVictories=h3qe64he0v
stats_1_totalTimeAsRunner=h3qe64hev_5jw0
stats_1_totalTags=h3qe64he5vz
stats_7_playTime=h3qe64hevvjwa_
stats_7_totalTimeAsRunner=h3qe64hey5__zy
stats_7_totalTags=h3qe64hewz
autoHideHud=h3qe-mmce73c9l
stats_8_runnerVictories=h3qe64hevy
stats_3_taggerVictories=h3qe64he5v
stats_global_taggerVictories=h3qe64hezvw
stats_10_playTime=h3qe64hewzwv_v
stats_10_runnerVictories=h3qe64heay
stats_10_totalTimeAsRunner=h3qe64hevyvz_d
stats_10_totalTags=h3qe64hez5d
stats_3_runnerVictories=h3qe64hezy
stats_10_taggerVictories=h3qe64heyy
stats_2_runnerVictories=h3qe64heyy
stats_9_playTime=h3qe64hevvvwv_
stats_9_totalTags=h3qe64heva0
stats_6_taggerVictories=h3qe64he__
stats_5_playTime=h3qe64hez_a5y
stats_5_totalTimeAsRunner=h3qe64he505_
stats_5_totalTags=h3qe64hez0
bljs=h3qe-mmceh2xl
eliminateOnDeath=h3qe-mmceh2xl
autoMode=h3qe-mmceh2xl
boost=h3qe-mmce73c9l
useRomhackCam=h3qe-mmceh2xl
hazardSurfaces=h3qe-mmce73c9l
stats_1_taggerVictories=h3qe64hev
stats_2_taggerVictories=h3qe64hezw
achievement_1=h3qe-mmceh2xl
achievement_3=h3qe-mmceh2xl
achievement_4=h3qe-mmceh2xl
achievement_5=h3qe-mmceh2xl
achievement_6=h3qe-mmceh2xl
achievement_8=h3qe-mmceh2xl
achievement_25=h3qe-mmceh2xl
achievement_16=h3qe-mmceh2xl
achievement_2=h3qe-mmceh2xl
stats_global_totalTournamentPoints=h3qe64he55d
playerTitle=h3qe64he.5
achievement_14=h3qe-mmceh2xl
stats_11_playTime=h3qe64hezy5jad
stats_11_totalTimeAsRunner=h3qe64he5zay5
stats_11_totalTags=h3qe64heaw
stats_5_taggerVictories=h3qe64he_
stats_9_taggerVictories=h3qe64he5d
achievement_29=h3qe-mmceh2xl
playerTrail=h3qe64heza
achievement_9=h3qe-mmceh2xl
stats_11_runnerVictories=h3qe64hej
achievement_27=h3qe-mmceh2xl
bind_1=h3qe64he0_
firstLaunch=h3qe-mmce73c9l
achievement_26=h3qe-mmceh2xl
changelogVer=byp_
activeTimers_9=h3qe64hev_ddpd
maxLives_9=h3qe64he5
tournamentPointSystem=h3qe64hed
maxLives_8=h3qe64he5
maxLives_5=h3qe64he5
stats_global_totalTournamentWins=h3qe64hey
achievement_22=h3qe-mmceh2xl
stats_5_runnerVictories=h3qe64hey
achievement_17=h3qe-mmceh2xl
achievement_18=h3qe-mmceh2xl
hidingTimer_7=h3qe64hewdd
theme=h3qe64he_
cannons=h3qe-mmce73c9l9ll
water=h3qe-mmce73c9l
