### ISSUE TITLE
Scripting error 11#

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#644]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/45809433-92d6-4b85-92ae-9ce1e474c5c2)

**Comment by Bear64DX** [comment]
This happened when loading up the "Royale gamemode". we also loaded it up w/ my W.I.P B3313 Tag Pack so idk if that has anything to do with it. Btw, for some reason in royale everyone isn't a tagger, even though everyone should be a tagger.

**Comment by EmeraldLoc** [comment]
Royale isn't in a working state so yea this is known.

**Comment by EmeraldLoc** [comment]
Fixed
