### ISSUE TITLE
Shell Recoil Degrees

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#645]
Make them like 45 instead of 80

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
Basically, shells use the same bonk system as slide, which feels very weird and a bit buggy

**Comment by EmeraldLoc** [comment]
The only thing that matters is does this appear in vanilla, I think it does but you can check if you want.

**Comment by TheMan6900** [comment]
pretty sure it doesnt, but ill check

**Comment by TheMan6900** [comment]
ok im pretty sure it actually does, but its very janky with the recoil so.

**Comment by EmeraldLoc** [comment]
Feels fine to me, and acts as it should so will keep.
