### ISSUE TITLE
The Hunt (shenanigans)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#647]
When you die, you don't lose a live like you're intended to. Instead, the game just takes a random amount of lives off of you (or it just makes you lose 2 lives, either way its still not intended.) I also found this weird glitch: 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/48f3d983-cac8-4138-96d1-1ecc5d86dd86)

**Comment by EmeraldLoc** [comment]
Are y'all still playing? Can I get a pass to join?

**Comment by TheMan6900** [comment]
we might play again

**Comment by EmeraldLoc** [comment]
> the game just takes a random amount of lives off

erm acktually, the game takes 2 lives away consistently. Anyways will fix that first bug.

> also found this weird glitch:

How did this occur, due to death by warp, or?

**Comment by Bear64DX** [comment]
Hey emerald, if ya want I can host again. Just DM on the Modsite when you're ready :)

**Comment by EmeraldLoc** [comment]
Nah think I got it fixed. You can just always send me the password, I'll probably pop in pretty often. Currently looking at the stages you sent me. Will close this for now.
