### ISSUE TITLE
Shell Recoil Enhancements

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#651]
So I had 2 main ideas for the Shell Recoil feature in 2.4. These ideas are:
- Making the knockback stronger. You can be going at a wall at like full speed and get knocked back by like 2ft or summ idk. It's incredibly weak.
- Make it so that you can only recoil if you're going fast enough

**Comment by EmeraldLoc** [comment]
I'll fix both of these problems by making it proportional.

**Comment by EmeraldLoc** [comment]
done
