### ISSUE TITLE
Blinking Win (but possible)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#652]
Winning maps on the voting screen would have a white blinking outline.

**Comment by Bear64DX** [comment]
And for custom themes, it could change based on the theme. If it's red it can still be white. But if it's like yellow or green which are very light colors, then it could be like, idk black or smth

**Comment by EmeraldLoc** [comment]
Probably wouldn't do a blinking win. Would rather make the theme buttons have more options (have a primary (what is confirm right now), regular (what currently is normal), and destructive (would be new) button styles). When the voting ends, the maps that lost would be themed with the destructive theme entry, and the winner would be themed with the primary.

**Comment by Bear64DX** [comment]
Hmm, that may actually work.

**Comment by EmeraldLoc** [comment]
Prefer what I said 2 weeks ago. When I get to it, that'll be what I do.
