### ISSUE TITLE
THIS IS LIKE THE FOURTH ODDBALL SCRIPT ERROR IVE POSTED

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#659]
When I died, the game decided to randomly throw this script error at me. I did lose my runner privileges though
![image](https://github.com/EmeraldLoc/tag/assets/171458695/f24d86ef-ab18-4aaf-9804-ba6c078fe202)

**Comment by EmeraldLoc** [comment]
Fixed (?)

**Comment by Bear64DX** [comment]
I just realized TM also made an error about this. Read that instead. Also I'm not sure if that's fixed
