### ISSUE TITLE
Oddball Leaderboard Rankings

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#665]
Display rankings near players name on the oddball leaderboard

**Comment by EmeraldLoc** [comment]
Why?

**Comment by TheMan6900** [comment]
Consistency

**Comment by EmeraldLoc** [comment]
OH, RANKINGS.... for some reason I thought you were saying nametag or smth idk lol

**Comment by EmeraldLoc** [comment]
Added
