### ISSUE TITLE
Weird 2.4 Menu Bug

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#666]
Okay so this was a doozie because it sometimes happens and it sometimes doesn't. Basically, boot up 2.4, go into the settings and DON'T MOVE AT ALL. Just press A in the menu without moving, and you might get a script error. This is because for some reason you don't always start in at the Start button, but rather a "nil value" according to the script errors in the vid. You can see this if you slow down the video until I open the menu, and you'll notice that it didn't put me on the start button. It sometimes happens and it sometimes doesn't. This happened to me on DX and I'm unsure if it does on Ex. It's hard to replicate because it sometimes happens and it sometimes doesn't. I don't know why it sometimes doesn't put you at the Start Button, but all I know is that it sometimes starts on a blank button.

https://github.com/EmeraldLoc/tag/assets/171458695/d7295aae-1669-4479-af91-1b9b1beb0e73

**Comment by EmeraldLoc** [comment]
Weird, will fix

**Comment by EmeraldLoc** [comment]
Certainly not gonna be an dx/ex issue.... how can you reproduce this?

**Comment by Bear64DX** [comment]
It's hard to explain, since it doesn't always work. Boot up 2.4, go to the Tag menu, and don't move at all. Then press A, and you get a script error. You'll also notice that it isn't on start when you boot up the menu (if this glitch happens)

**Comment by Bear64DX** [comment]
It's hard to reproduce since it just sometimes chooses not to work.

**Comment by EmeraldLoc** [comment]
Can't really reproduce, so can't fix it rn

**Comment by Bear64DX** [comment]
It may be 2.4 struggling when I add new stages. It def isn't B3313's fault since I think it happens w/o the B3313 pack (or just other addons)

**Comment by EmeraldLoc** [comment]
Has this occurred again? Have you found a more easier way to reproduce this?

**Comment by Bear64DX** [comment]
It just happens when I boot up 2.4. This constantly occurs. Load up a tag addon pack, and try the reproducing method again.

**Comment by EmeraldLoc** [comment]
I have b3313, every arena stage, etc.

> try the reproducing method again.

The video moves pretty quickly... it seems like you pause the game, hit up dpad, then hit A to enter the menu, hit A again, and get a script error.... is that correct?

**Comment by EmeraldLoc** [comment]
Wait, I got it, can successfully reprodcue

**Comment by Bear64DX** [comment]
Yes, that is correct. Sorry for the fast vid lol

**Comment by EmeraldLoc** [comment]
Fixed. You can really fix something fast if you can reproduce it lol.

**Comment by Bear64DX** [comment]
lol
