### ISSUE TITLE
Sardines Bug

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#668]
Was in TM's 2.3 server and when I was hiding I died at the right time and got sent to here? I don't think it's the same as the 2.4 one since you don't constantly die over and over again.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/f4f5ae93-5ec9-4cc4-ae98-44e2b97c2a01)

**Comment by EmeraldLoc** [comment]
Unsure of what it is without more information :/

**Comment by TheMan6900** [comment]
im pretty sure he timed hiding, at just the right time, that so he got placed on the death floor/plane

**Comment by Bear64DX** [comment]
Saus actually sent me an image. I'm on my phone rn so I can't send it ATM. But in the picture I was at the start of the map, but on my screen it dark. Also it's hard to give info for this bug because there weren't any script errors or anything like that.

**Comment by Bear64DX** [comment]
Back on my PC. This was the pic Saus sent me.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/556aa774-0838-42cb-a5b3-8f87cc94e092)

**Comment by EmeraldLoc** [comment]
> im pretty sure he timed hiding, at just the right time, that so he got placed on the death floor/plane

This wouldn't be it, since mario's position must be grounded before it sets a position.

Could saus tag you, or were you intangible? Honestly pretty clueless on what the problem could be here

**Comment by Bear64DX** [comment]
I asked him. He hasn't responded

**Comment by Bear64DX** [comment]
I assume that Saus couldn't tag me. When we test the new B3313 stages we can test this error and I'll try to reproduce it.

**Comment by Bear64DX** [comment]
Saus responded. He apparently couldn't tag me.
