### ISSUE TITLE
Double Jump Pvp Cancel

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#669]
Make Pvp knockback/bonks not cancelable but double jumps

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
your able to double jump within a small timing window after getting bonked

**Comment by TheMan6900** [comment]
not sure if it has do with the 0.2 - 0.1 delay

**Comment by EmeraldLoc** [comment]
If you're spamming that's a skill issue, for the latter that's intentional.

**Comment by TheMan6900** [comment]
this is not a chuckya throw
