### ISSUE TITLE
New setting - Hazard Damage

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#67]
This would be a setting for all gamemodes with lives (juggernaut, hunt, and deathmatch) which would allow hazards that deal damage to you, to take one of your lives away. for hunt however, on your last life hazards wouldnt deal damage to you.

**Comment by TheMan6900** [comment]
Oh yeah, If a player were to get killed by a stage hazard in juggernaut or deathmatch a message saying "Stage Hazard killed X" would appear.

**Comment by EmeraldLoc** [comment]
What exactly is the definition of hazard here? We talking terrain? Because that already happens there.

**Comment by TheMan6900** [comment]
Anything that can damage you that isnt terrain

**Comment by TheMan6900** [comment]
enemies, fire spitters, and etc

**Comment by EmeraldLoc** [comment]
Nah.
