### ISSUE TITLE
Make Vote Cancelling Have Text

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#672]
It just feels more convenient. At least make voting/canceling bindable

**Comment by EmeraldLoc** [comment]
I love getting contradicting issues. This feels like something really stupid to have bindable, I'll add a text instead. If I make it A, then you can't spam it, which just kinda sucks.

**Comment by TheMan6900** [comment]
> I love getting contradicting issues. This feels like something really stupid to have bindable, I'll add a text instead. If I make it A, then you can't spam it, which just kinda sucks.

whats wrong with spamming?

**Comment by EmeraldLoc** [comment]
What the heck am I doing with these labels, help. I love spamming a on the level I want to win, don't know why, but a LOT of people do this, including myself, just a tendency ppl have for some reason.

**Comment by Bear64DX** [comment]
I personally just like the B button. Spamming just makes the voting screen looks messy and I feel like it being bound to A just doesn't make sense. Sorry if I sound like "that guy", this is just what I personally think.
