### ISSUE TITLE
Placement Stat Coloring

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#675]
Have 1st, 2nd and 3rd (also maybe 4th) have there stats be colored by there respective ranking number color

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
ok so, if you were to get first place your stats (lets say, your total tags) would be colored yellow, and etc

**Comment by EmeraldLoc** [comment]
No, I'd just have your placement on the entry, like you've already made an issue on.
