### ISSUE TITLE
Modifier Desync(???)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#679]
(picture from Max_MARIO)
![image](https://github.com/EmeraldLoc/tag/assets/168046906/f512c5d3-f10f-4143-be0a-2c4556e1d92f)
![image](https://github.com/EmeraldLoc/tag/assets/168046906/004ee6bb-8a34-4423-97d4-0cb8714aae11)

For some reason, he (Max) has the "None" modifier while everyone else has the "Fly" Modifier

**Comment by EmeraldLoc** [comment]
CAn't really be fixed
