### ISSUE TITLE
scripting error 17#

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#680]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/0a2ab47d-58e5-4035-8004-9c8b5e8a9d23)

**Comment by EmeraldLoc** [comment]
What version of tag?

**Comment by TheMan6900** [comment]
2.4

**Comment by EmeraldLoc** [comment]
This should not happen? It's stating that gGlobalSyncTable must be nil, which is def not the case.... can you enter tmp and send what the line is so I can see if mine is the same?

**Comment by TheMan6900** [comment]
this is the chunk of the code

---@param m MarioState
local function mario_update(m)
    if levels[gGlobalSyncTable.selectedLevel].overrideWater ~= true
    and not gGlobalSyncTable.water then
        -- get rid of water
        for i = 1, 10 do
            set_environment_region(i, -10000)
        end
    else
        -- bring back water
        for i = 1, 10 do
            if waterRegions[i] ~= nil then
                set_environment_region(i, waterRegions[i])
            end
        end
    end

**Comment by EmeraldLoc** [comment]
Wow!

**Comment by EmeraldLoc** [comment]
Yea I know that much already, what's the exact line for you, line 946

**Comment by TheMan6900** [comment]
if levels[gGlobalSyncTable.selectedLevel].overrideWater ~= true

**Comment by EmeraldLoc** [comment]
Ok that makes a lot more sense

**Comment by EmeraldLoc** [comment]
Were you joining a lobby with a romhack or?

**Comment by TheMan6900** [comment]
no, it was just tag - b3313, and of course, tag 2.4

**Comment by EmeraldLoc** [comment]
Well then `levels` had to have been nil... very weird, probably a one off, will keep open, if it happens again, be sure to report here.

**Comment by EmeraldLoc** [comment]
Oh yea fixed this
