### ISSUE TITLE
Cannon Bug?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#682]
(Picture from Max_MARIO)

no cannon camera for some reason?

![image](https://github.com/EmeraldLoc/tag/assets/168046906/4b5476a0-abc6-4594-b772-59bc1fa387df)

**Comment by EmeraldLoc** [comment]
DId he enter the cannon with another player at the same time?

**Comment by TheMan6900** [comment]
it was just him

**Comment by EmeraldLoc** [comment]
Was someone else in the cannon before he entered? This seems like a coop bug.

**Comment by TheMan6900** [comment]
I was in the cannon before he entered

**Comment by TheMan6900** [comment]
but there was abouta 5 or so time span of cannon uses

**Comment by EmeraldLoc** [comment]
This very much so seems like a coop bug... will close for now.
