### ISSUE TITLE
 No cannon control

### ISSUE THREAD

**Issue by SausRelicsSSJ2** [EmeraldLoc/tag#683]
Whenever I enter a cannon in tag, instead of being able to control where I shoot, the cannon disappears and I can't shoot in any direction besides forwards. I thought this may be caused by the fact that I play keyboard, but now that I've tried it on a controller i have no clue what could cause this

**Comment by EmeraldLoc** [comment]
I've been unable to reproduce this bug... have you found a consistent way to reproduce this?
