### ISSUE TITLE
Addon Level Bhvs Not Disabled when a Romhack is on

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#684]
(Sorry if this isn't in the right repo. I assume it's a tag issue so I'm putting it here.)
So I'm sure we all know that star boxes get disabled when Tag is on. However in addon levels, when a romhack is on, it actually doesn't disable star boxes. I tested this with Star Road so I'm not sure if this applies to other hacks. Here's some images for you:
(UPDATE: I know that this can be fixed by removing Bhvs in the script.c file but this is still a bug and should be acknowledged.)

Here's how it looks in Vanilla. Perfectly normal
![image](https://github.com/EmeraldLoc/tag/assets/171458695/dac4ef88-4e10-4be7-b437-34f712270e52)

And here's how it looks in Star Road, this bug messed w/ the pipes in Ice Cold Crevasse (also new tag b3313 stage leak?????)
![image](https://github.com/EmeraldLoc/tag/assets/171458695/dce56bf2-790d-4254-83f0-f7fe2f084113)

**Comment by EmeraldLoc** [comment]
Yea this is just something that’s outdated now… vanilla levels will need to be changed a bit

**Comment by EmeraldLoc** [comment]
"fixed", however this is probably gonna break 1 or 2 vanilla levels, we shall see.

**Comment by Bear64DX** [comment]
> "fixed", however this is probably gonna break 1 or 2 vanilla levels, we shall see.

Wait what vanilla levels were even going to break anyway?
