### ISSUE TITLE
Help - How To Install

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#685]
A text (thing?) in the help menu (probably would have its own category), telling the player how to install the mod, (if they want to).

**Comment by EmeraldLoc** [comment]
If they know how to download any mod, they'll know how to download tag.

**Comment by TheMan6900** [comment]
sm64ex mods are almost never exclusive to github/coopdx wdym (discord is basically the onlyl place people get mods for this game)?

**Comment by TheMan6900** [comment]
I meant where you installed it

**Comment by EmeraldLoc** [comment]
The download location?

It just feels clunky having this as a section in the help menu. The majority of players know that the mod site exists.

**Comment by TheMan6900** [comment]
> The download location?
> 
> It just feels clunky having this as a section in the help menu. The majority of players know that the mod site exists.



> The download location?
> 
> It just feels clunky having this as a section in the help menu. The majority of players know that the mod site exists.

They do?
