### ISSUE TITLE
Scroll Bar Bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#691]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/fa2f4d21-532b-4c49-a8fc-f6335003e409)

the scroll bar can just go off the ui, it theres to many items

**Comment by EmeraldLoc** [comment]
Heh, yea... I suck at coding.

**Comment by TheMan6900** [comment]
> Heh, yea... I suck at coding.

You really do!

**Comment by TheMan6900** [comment]
You kinda forgot about this issue 💀

**Comment by EmeraldLoc** [comment]
I read through every issue yesterday, Ill fix each one when I get to them
