### ISSUE TITLE
More Animated Ui (2.5)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#693]
Just add more movement to the ui, instead of it just, snapping from one position to another

**Comment by Bear64DX** [comment]
Buttons could also flash just to show more life in the UI. Keep this thread open just in-case we think of HUD ideas.

**Comment by TheMan6900** [comment]
Alright

**Comment by EmeraldLoc** [comment]
Hm

**Comment by TheMan6900** [comment]
I also just think having a more lively animated Hud, fits tags incrediblely kinetic and fast paced gameplay

**Comment by TheMan6900** [comment]
Maybe for tourneys, if a player got points during a round. a counter showing there total points they, got for said round would show, and rapidly count down, adding to their point total.

**Comment by Bear64DX** [comment]
> Maybe for tourneys, if a player got points during a round. a counter showing there total points they, got for said round would show, and rapidly count down, adding to their point total.

Oh wait I actually really like this

**Comment by EmeraldLoc** [comment]
This issue is very broad, and generally includes things that would naturally be done overtime
