### ISSUE TITLE
Can't start levels w/ an afk friend

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#695]
For some reason, if your friend is afk (spectator), you can't start a level. When I mean start a level, I mean like freeplay mode. Auto Mode was on so I don't know what's causing this.

https://github.com/EmeraldLoc/tag/assets/171458695/2f0b5087-5172-4990-9307-5f6d659d0d3b

**Comment by EmeraldLoc** [comment]
An oversighr

**Comment by EmeraldLoc** [comment]
Fixed
