### ISSUE TITLE
Royale Counter Error

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#698]
Not only did it go into the negatives, but it also overlaps ability hud, (and other meters)

![image](https://github.com/EmeraldLoc/tag/assets/168046906/ff8d35ef-e625-4ddf-b61a-949d9b918d93)

**Comment by TheMan6900** [comment]
(also uh emerald, you might wanna, start grinding through issues right about soon)

**Comment by EmeraldLoc** [comment]
I’m aware of what’s happening. I will be grinding thru each of the bugs. I already know this. Royale’s is not finished.
