### ISSUE TITLE
Incorrect spawn pos for addon levels while unspectating

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#700]
I was messing around with my current levels I had in the B3313 pack, and I found a bug with Tag. I spectated and then unspectated so that the game warps me to a different level. I warped to one of my custom levels, however it wasn't my custom level. It was supposed to load area 4, however it loaded area 1 and it also spawned me over a pit, which is weird. This happens w/ other custom levels and I have the spawn locations set. So I'm pretty sure this is a Tag bug. EDIT: It happened again. When I unspectated, it not only didn't load the correct area but also not the correct spawn for that incorrect area (if that makes sense)
I'm not sure if I made an issue similar to this. I don't think I have since there's two different bugs for spawn positions. One for starting in the level (need to be set manually), and the unspectating one

https://github.com/EmeraldLoc/tag/assets/171458695/a584058e-3574-4b7e-b010-a44874e30c29

![image](https://github.com/EmeraldLoc/tag/assets/171458695/656dd3da-4120-4c49-88a2-98ae2977438d)

**Comment by EmeraldLoc** [comment]
Good catch!

**Comment by EmeraldLoc** [comment]
Fixed
