### ISSUE TITLE
Slight Pvp Blink

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#703]
A slight i-frame plays when getting pvped, or getting hit by enemies

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
https://github.com/EmeraldLoc/tag/assets/168046906/66d1930f-ca64-4029-aa2a-db6663b29281

**Comment by TheMan6900** [comment]
emerald?

**Comment by EmeraldLoc** [comment]
This slid under the radar. Yea idc about this lol, I aint adding 4 lines of code to fix it, that's just gonna look ugly

**Comment by TheMan6900** [comment]
> This slid under the radar. Yea idc about this lol, I aint adding 4 lines of code to fix it, that's just gonna look ugly

wdym look ugly?

**Comment by EmeraldLoc** [comment]
The code'll look messy and stupid.

Anyways redoing the I-frames method'll fix it anyways
