### ISSUE TITLE
Terminator Incog Doesn't work

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#707]
For some reason, the terminator (ShortKoopa) had a pop up saying "ShortKoopa terminated bla bla bla". Incog was on so idk what caused this. 

https://github.com/EmeraldLoc/tag/assets/171458695/c95e742e-1009-40e3-8f61-e0f03b90052f

**Comment by EmeraldLoc** [comment]
Yes this is an oversight

**Comment by EmeraldLoc** [comment]
I take what I said above back... this was probably a desync, if it happens again with incognito mode and terminator gamemode, report here.
