### ISSUE TITLE
Blasters and bombs i-frames

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#71]
Blasters shots and bombs are able to hit through i-frames.

**Comment by EmeraldLoc** [comment]
Didn’t you already make an issue on this

**Comment by TheMan6900** [comment]
You can still get hit by blaster shots and bombs even with i-frames, not you cant hit with i-frames on.

**Comment by EmeraldLoc** [comment]
??? I’m closing this, I believe both can be fixed with ease, as no thought was put into I frames during the construction of projectiles
