### ISSUE TITLE
Star Doors Dont Work?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#710]
https://github.com/EmeraldLoc/tag/assets/168046906/b42ff2d3-2928-4ae3-87fd-958c5b763bef
 (active game btw)

**Comment by EmeraldLoc** [comment]
Same thing as sm74

**Comment by TheMan6900** [comment]
why cant you just... make them work

**Comment by TheMan6900** [comment]
regardless of the save file star count?
