### ISSUE TITLE
New Modifer/Gamemode Selection 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#72]
I have no idea how to explain this so ill just make a text based image of what this would look like (this would kinda be like a slider)

Random < **Tag** > Freeze tag
No Bljs < **Friendly Fire** > Random

Gamemodes on the side would be smaller and little faded out.

**Comment by EmeraldLoc** [comment]
I see, I personally won’t add this, but if someone else does sure

**Comment by EmeraldLoc** [comment]
Probably wont add this even if someone else made it.
