### ISSUE TITLE
Radar Overlap

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#722]
If two or more radars overlapped, both radars (or more) radars would hug each other with the one futher away being more expanded from the circle 

![image](https://github.com/EmeraldLoc/tag/assets/168046906/ac800589-5382-41e2-90f2-0ae675cabeee)

**Comment by EmeraldLoc** [comment]
If someone else wants to add this, sure ig, its just really not necessary. If 2 radars overlap, who cares, head in that direction anyways.
