### ISSUE TITLE
New Modifier - Floor Is Lava

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#726]
Basically, this would choose peices of surface to make LAVA, if you touch the lava enough times you get eliminated

**Comment by EmeraldLoc** [comment]
*sigh *Did you really thumbs up your own message....

It's very unreasonable to assume a player to know what a certain floor type this. This simply isn't viable.

**Comment by TheMan6900** [comment]
> _sigh_ Did you really thumbs up your own message....

funny
