### ISSUE TITLE
Scripting error #20?

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#728]
Is this a duplicate? I joined on my alt (same pc w/ modified coopdx) and got this, I think I might have reported this already. It doesn't have to do w/ the update checker though
![image](https://github.com/EmeraldLoc/tag/assets/171458695/fade5a30-d9d6-4d65-a2df-ab82e5b8948d)

**Comment by EmeraldLoc** [comment]
Indeed a dupe, I closed the previous issue on this. Also can we not do the `scripting error #instert number here` thing, and instead give the filename and line to the script error, will make it a bit easier to organize all of it.

**Comment by Bear64DX** [comment]
> Indeed a dupe, I closed the previous issue on this. Also can we not do the `scripting error #instert number here` thing, and instead give the filename and line to the script error, will make it a bit easier to organize all of it.

I was just continuing the trend lol

**Comment by EmeraldLoc** [comment]
Think I fixed this again.
