### ISSUE TITLE
Tornado Shell Cancel

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#729]
Make tornados not cancel shells

**Comment by EmeraldLoc** [comment]
You mean make shells not cancel tornados?

**Comment by TheMan6900** [comment]
> You mean make shells not cancel tornados?

yeah, (also, when I mentioned I was "bug testing" It was just a 2.32 server, where I was testing out the bomb squash glitch)

**Comment by TheMan6900** [comment]
I dont get what made you think I was hosting 2.4

**Comment by EmeraldLoc** [comment]
Incept from the issue I closed

> My bad, for some reason I thought I only added that message after 2.32, oops.

Also this issue is not related to that, so please stay in the closed issue.
