### ISSUE TITLE
Failed Encryption?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#730]
Seemly after doing some bug testing, with an alt, I got a fail encryption error that deleted all my save data.
I dont really care about getting my stats back, just thought this should be bug reported.

**Comment by Bear64DX** [comment]
Heh, Coop Deluxe amirite?! Nah seriously, your save got wiped. You're either gonna have to use Ex or ask Emerald about a solution. He knows exactly how to fix this.

**Comment by EmeraldLoc** [comment]
So you were hosting 2.4 with an alt, from tmp, on an unreleased mod. Did I give permission?

Probably due to coopdx failing to load the keys… once v1 comes out, of this keeps happening, lmk. If you know how to compile coopdx (compile, not patch), then I can show you a solution, and you can contact me on the mod site.

**Comment by Bear64DX** [comment]
> So you were hosting 2.4 with an alt, from tmp, on an unreleased mod. Did I give permission?
> 
> Probably due to coopdx failing to load the keys… once v1 comes out, of this keeps happening, lmk. If you know how to compile coopdx (compile, not patch), then I can show you a solution, and you can contact me on the mod site.

WAIT I JUST REALZIED THAT. TM WHAT WERE YOU DOING?!

**Comment by Bear64DX** [comment]
Actually I think it might've been a 2.32 server actually

**Comment by TheMan6900** [comment]
> So you were hosting 2.4 with an alt, from tmp, on an unreleased mod. Did I give permission?
> 
> Probably due to coopdx failing to load the keys… once v1 comes out, of this keeps happening, lmk. If you know how to compile coopdx (compile, not patch), then I can show you a solution, and you can contact me on the mod site.

NO? IT WAS JUST A 2.4 SERVER??

**Comment by Bear64DX** [comment]
> > So you were hosting 2.4 with an alt, from tmp, on an unreleased mod. Did I give permission?
> > Probably due to coopdx failing to load the keys… once v1 comes out, of this keeps happening, lmk. If you know how to compile coopdx (compile, not patch), then I can show you a solution, and you can contact me on the mod site.
> 
> NO? IT WAS JUST A 2.4 SERVER??

WAIT YOU JUST ADMITTED TO HOSTING 2.4 EVEN THOUGH YOU TOLD ME IT WAS 2.32

**Comment by TheMan6900** [comment]
?????

**Comment by Bear64DX** [comment]
> ?????

You just said "NO, IT WAS A 2.4 SERVER"

**Comment by EmeraldLoc** [comment]
My bad, for some reason I thought I only added that message after 2.32, oops.

**Comment by TheMan6900** [comment]
Yep
