### ISSUE TITLE
Revert Assassins Hitstun

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#732]
Seriously, it's so short that there's literally no punishment for hitting the wrong target in 2.4.

**Comment by EmeraldLoc** [comment]
When you get stunlocked, your target can spam kick your body and get a free kill

**Comment by Bear64DX** [comment]
Oh yeah, I'm just saying this is a lot harder because of this hitstun being WAYY shorter

**Comment by EmeraldLoc** [comment]
5 seconds is pretty unenjoyable, I can try out 2 seconds.

**Comment by Bear64DX** [comment]
> 5 seconds is pretty unenjoyable, I can try out 2 seconds.

5 seconds is def too much. Do like 2 or 3

**Comment by TheMan6900** [comment]
isnt 2 the default already?

**Comment by Bear64DX** [comment]
I actually think it is. Do like 3 or 4

**Comment by TheMan6900** [comment]
2 is good already

**Comment by Bear64DX** [comment]
That's WAAAAY too short. There's no punishment with hitting people. At the very least like 3 or 4 seconds. The original hitstun time wasn't even bad at all. It was perfect.
