### ISSUE TITLE
Why aren't jzzle and TheMan in the dev repo?

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#734]
Just a quick question I had since jzzle has a github acc (jzz1e), and why TM isn't in there is beyond me. I don't really care what happens, I'm just curious. (Also srry if I should've made this a discussion page, I just prefer using issues instead)

**Comment by EmeraldLoc** [comment]
I did invite jzzle, he didn't accept it. I've not received a pull request from TheMan, nor do I know how much he was involved in LLD, so I haven't invited him.

**Comment by TheMan6900** [comment]
I kinda don't know how to make a pull request :skull: probably should actually learn that soon
