### ISSUE TITLE
Scripting Error (hard_surface_modifier.lua, line 10)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#735]
For some reason, clipping OOB (like w/ noclip) while you have the hard floors modifier on gives this script error.

![image](https://github.com/EmeraldLoc/tag/assets/171458695/52cefc26-dc77-4375-b19b-e3c12787e8a6)

**Comment by EmeraldLoc** [comment]
Already fixed I think, will double check

**Comment by EmeraldLoc** [comment]
Fixed
