### ISSUE TITLE
File Optimizations

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#736]
Feel like the file could be cut down in size, being improving code efficients and just removing unnecessary pieces of code

**Comment by Bear64DX** [comment]
I'm still wondering why there's "-- something" in the code. They're kinda like notes, and I'm not sure why they're there. Emerald, if you're reading this, could you answer this question?

**Comment by EmeraldLoc** [comment]
Removing a couple of lines of code will barely save you a kilobyte. The  ig storage hitters are the paintings.

those are comments. Comments allows me to tell what a certain piece of code is. If someone else looks at the code, comments are very helpful for learning the code base, and I’ve been sure to put in a lot of them.

**Comment by Bear64DX** [comment]
> Removing a couple of lines of code will barely save you a kilobyte. The big storage hitters are the paintings.
> 
> those are comments. Comments allows me to tell what a certain piece of code is. If someone else looks at the code, comments are very helpful for learning the code base, and I’ve been sure to put in a lot of them.

I know understand. Thank you!
