### ISSUE TITLE
New settings - Deathplane Damage

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#74]
Deathplane Damage, can be disabled or enabled, to allow damage on falling into a deathplane

Deathplane Damage Amount, can be toggled 3 damage amounts (1, 2, and 3), to deal a certain amount of damage to a player when falling into a deathplane. deathplane damage can not be equal or over the live amount. This setting can only be toggled,  if Deathplane Damage is enabled.

These settings would go to juggernaut, hunt, and deathmatch. this would also apply to quicksand.

**Comment by EmeraldLoc** [comment]
Oddly specific, not gonna add this.
