### ISSUE TITLE
UPDATE:

### ISSUE THREAD

**Issue by PolarBear32** [EmeraldLoc/tag#742]
So this isn't really an issue, but for some reason I have to create a new account because I lost my old one. I will need access to the Developer repo again. - Bear

**Comment by EmeraldLoc** [comment]
…. How?

**Comment by PolarBear32** [comment]
> …. How?

That's what I'm wondering too. I just got suspended after making an issue on the coopdx repo. idk man, I don't

**Comment by EmeraldLoc** [comment]
Your GitHub acc got suspended???

**Comment by PolarBear32** [comment]
> Your GitHub acc got suspended???

It did. I am not sure what even caused it. Last thing I remember doing is making an issue for Coop Deluxe and then I got struck. Thankfully my commits are still there so it's not the end of the world but maaan...

**Comment by EmeraldLoc** [comment]
Never seen that in my life, that’s rough. Will invite to repo later
