### ISSUE TITLE
New achievement - Termination of the Skys

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#743]
Objective: Win as the terminatior with the fly modifier, 10 times
Reward: Sky Hazard,  title

**Comment by PolarBear32** [comment]
Huh, I'm pretty sure I suggested a "Sky Hazard" title.

**Comment by TheMan6900** [comment]
Yeah, I was reworking it to this one

**Comment by PolarBear32** [comment]
I'm still not entirely sure how I feel about you using that title though.

**Comment by TheMan6900** [comment]
it just felt better for this achievement imo

**Comment by EmeraldLoc** [comment]
No
