### ISSUE TITLE
Player Introductions

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#746]
These would be chat messages that would appear next to players stats saying something based, off there stats,

1-10 total wins: a newbie has joinned
10-50: an amateur  has joinned
50-100: a novice has joinned
100-500: a pro has joinned
500-above: A GOD HAS ARIVED

There could be some extra stuff done with a system like this, might add more if I think of any.

**Comment by EmeraldLoc** [comment]
Titles do this job.
