### ISSUE TITLE
deathmatchlua.41

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#749]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/292a9fc9-8402-44b0-9d6f-ebd260e10573)

**Comment by TheMan6900** [comment]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/6f739bf6-82ee-4a19-af26-96f97e2adf95)

**Comment by TheMan6900** [comment]
emerald if your seeing this, please remove the saving decodes in the chat logs

**Comment by EmeraldLoc** [comment]
Ik

**Comment by EmeraldLoc** [comment]
This can't really be solved, as it seems to be coop denying to initialize that global variable... if it happens again then sure. For the second image, that's certainly a coop issue.
