### ISSUE TITLE
Held Bom-omb not following

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#75]
If you enter a state where marios hands are held out (open hands) the held bomb, wont follow your hand postion.

**Comment by EmeraldLoc** [comment]
Not encountering the same issues, does this happen with the vanilla moveset? If so, how can I reproduce it?

**Comment by TheMan6900** [comment]
This most often happens when twirling

**Comment by EmeraldLoc** [comment]
That also works fine... Have you tested it with the vanilla moveset?

**Comment by TheMan6900** [comment]
Yeah

**Comment by TheMan6900** [comment]
I just tested those actions with my thing cause it uses the same things for twirling as in the base game

**Comment by EmeraldLoc** [comment]
Can you send a video of this?

**Comment by TheMan6900** [comment]
dont know how.

**Comment by TheMan6900** [comment]
This could possible be a sharens details issue, seeing that this also happens with held arena items (but im pretty sure tag basically uses the same code as arena so)

**Comment by EmeraldLoc** [comment]
Then I can’t fix it. It’s currently the best it can be as of right now, so yea, I’ll leave this open for now

**Comment by TheMan6900** [comment]
Ok this is just a thing with sharens details, tested it like 10 times with vanillia, all times working fine.

**Comment by EmeraldLoc** [comment]
Can't do anything then, will close.
