### ISSUE TITLE
Hunt Repoll

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#753]
Just use the hunt repoll as a failsafe for every gamemode

**Comment by EmeraldLoc** [comment]
What gamemodes? It doesn't really work for any others. In tag, it uses elimination. Freeze tag just sets yourself as a tagger. Infection is the same as freeze tag. Hot potato uses elimination. Juggernaut uses elimination, assassins you can't die. Sardines should be removed. Deathmatch is elim based, Oddball uses repolling, and you can't die in royale.

**Comment by PolarBear32** [comment]
> Sardines should be removed.

Actually based?!
