### ISSUE TITLE
Character Select Support

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#755]
Add a menu option, if char select is on, saying "open character select" that would take you to the character select menu

**Comment by PolarBear32** [comment]
There's already a bind in the pause menu that takes you to the CS screen (if you map one). But that wouldn't actually work though because Tag's pause screen is custom. Unless you break the game but idk if thatd work

**Comment by EmeraldLoc** [comment]
Uh... does character select use a custom pause screen?

**Comment by TheMan6900** [comment]
you can add that pretty easily actually as you said

**Comment by EmeraldLoc** [comment]
Added
