### ISSUE TITLE
Mod breaks w/ Skip Intro Off (0 star save)

### ISSUE THREAD

**Issue by PolarBear32** [EmeraldLoc/tag#765]
I'm not exactly sure if this is intended or not. And this actually messes w/ matches. Upon testing the mod more I can tell that this doesn't break the mod. But this still feels like an oversight.
![image](https://github.com/EmeraldLoc/tag/assets/174159227/8d6bc3de-10e6-4e52-bccf-a389cd6e5ea2)

**Comment by EmeraldLoc** [comment]
Fixed
