### ISSUE TITLE
Make levels selectable for unsupported hacks

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#768]
pretty self explanatory, I dont know why they dont

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
You cant select levels, while solo

**Comment by EmeraldLoc** [comment]
You can?

**Comment by TheMan6900** [comment]
for unsupported hacks

**Comment by EmeraldLoc** [comment]
Unable to reproduce, your hack could have janked up warp nodes, what romhack is it?

**Comment by TheMan6900** [comment]
super trump 64
