### ISSUE TITLE
New setting - springs

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#770]
disables/enables springs and launch springs from levels, its just nice having a way to play these levels in a traditional way

**Comment by EmeraldLoc** [comment]
Oh yea no

**Comment by TheMan6900** [comment]
why reject this?

**Comment by EmeraldLoc** [comment]
Because levels are built around springs now, this is not a good idea to add, honestly the pipe option shouldn't exist either.

**Comment by TheMan6900** [comment]
Me and a lot of others like the pipe option.
