### ISSUE TITLE
Make Late Joinning not disable eliminations

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#774]
theres already a setting for that

**Comment by EmeraldLoc** [comment]
No, think about it.

If you have late joining on, but elimination on death on, then when you get eliminated, someone who joins late just gets to become a spectator, which doesn't really feel fair. Also, if I were to make it separate, it would also allow for some easy abuse to prevent being eliminated, thus it forces elimination on death to be off.
