### ISSUE TITLE
GS Pipe Issue (duplicate, but read the post)

### ISSUE THREAD

**Issue by PolarBear32** [EmeraldLoc/tag#778]
I know TM already made an issue on this, so you can mark this as a dupe. But I wanted to alarm you about this because it's kinda a tag and gs issue at the same time. So for some reason, the game will just throw this script error at you. It mainly happens w/ addon levels, which I have no idea why. Only reason I'm making this dupe issue is because this is very annoying in-game, and I thought I'd report the same issue, but just with more information. Feel free to close this issue and mark it as a duplicate, but it'd be cool if there was a way I could fix this in the gs mod.
![image](https://github.com/EmeraldLoc/tag/assets/174159227/575904ec-e3b9-4ec0-a0d8-570ea4f4c84b)

**Comment by EmeraldLoc** [comment]
I can't really fix it. It's a problem with green stars, and is not in any way related to Tag. If you want to get rid of it, you can create a empty behavior called bhvPipeSpawner, and that'll trick the mod into thinking that behavior exists.

**Comment by PolarBear32** [comment]
Thanks for the feedback. I will alert TM about this and try to fix it
