### ISSUE TITLE
New feature - End Tournament 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#779]
This would be located in the tournament catagory, which it would immediately end the tournament, with the person in the lead automatically being declared, won

**Comment by EmeraldLoc** [comment]
This can be abused, I wouldn't have the player win instantly.

**Comment by EmeraldLoc** [comment]
Well then Emerald, what would I do? What solution did I have on September 6th, what were you thinking? Emerald, do you not understand that if you want to end a tournament, no matter what you do it can easily be abused? Do you not think this? I'm not happy Emerald, I'm not happy.
