### ISSUE TITLE
Zero Life Spring

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#780]
Add a spring that bounces you out of the black hole

**Comment by EmeraldLoc** [comment]
@Bear64DX Can you add this for me real quick?

**Comment by Bear64DX** [comment]
Lemme grill rq

**Comment by Bear64DX** [comment]
Uhh I think I screwed something up because I literally don't see a spring 💀 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/900beb53-c80a-4781-8872-a8a3f5b3848c)

**Comment by Bear64DX** [comment]
Wait Im dumb 💀

**Comment by EmeraldLoc** [comment]
You're missing the corresponding `}`. Please get a better vscode theme where you can see red lines. I use one dark, but the default theme is perfectly fine.

**Comment by Bear64DX** [comment]
No it's not that, I can see the red lines. It's the fact that I'm not loading the correct version of tag. I can see red lines though (also red theme is peak tbh)

**Comment by Bear64DX** [comment]
alright NOW I'm grilling

**Comment by Bear64DX** [comment]
NO GAME PLEASE 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/9b15f048-f7ab-429f-a9e4-9c741db62a41)

**Comment by Bear64DX** [comment]
🔥 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/c34242c9-f7b9-40d5-ac7c-b4e324967ee4)

**Comment by EmeraldLoc** [comment]
EmeraldLockShroom!64DXRayz!

Any reasoning behind this wacko name?

**Comment by Bear64DX** [comment]
> EmeraldLockShroom!64DXRayz!
> 
> Any reasoning behind this wacko name?

Based name ngl

**Comment by Bear64DX** [comment]
Nah but seriously, me and my friend Saus were trying to think of the wackiest names that end in "Rayz!"
You should see his name lol (if he hasn't changed it)

**Comment by EmeraldLoc** [comment]
Thanks bear!

**Comment by Bear64DX** [comment]
> Thanks bear!

You're welcome!
