### ISSUE TITLE
Name Centering

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#783]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/d854703a-982b-480f-9f31-d1ca9d3aa85f)
does this look centered?

**Comment by EmeraldLoc** [comment]
Is that the entire screen? I don't see a voting begins on the left side.

**Comment by TheMan6900** [comment]
yeah that is the entire screen

**Comment by TheMan6900** [comment]
heres the whole screen 
![image](https://github.com/EmeraldLoc/tag/assets/168046906/718f434d-34e3-4cf3-8b9d-ca635b026ee4)
