### ISSUE TITLE
Owner Title!?!

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#799]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/0d51b5be-4cd1-483c-8e26-784164949e99)
![image](https://github.com/EmeraldLoc/tag/assets/168046906/0d51b5be-4cd1-483c-8e26-784164949e99)

**Comment by EmeraldLoc** [comment]
Did he just have that unlocked, or is he mimicking it?

**Comment by TheMan6900** [comment]
think he unlocked it

**Comment by TheMan6900** [comment]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/37f3536f-5f51-4673-81fe-2230d50e446a)

**Comment by TheMan6900** [comment]
https://github.com/EmeraldLoc/tag/assets/168046906/5e82fff8-5d3d-481b-96e5-376eac811419

**Comment by PolarBear32** [comment]
I don't remember LuigiBoy having Owner. Like I said, this is prob a visual bug

**Comment by TheMan6900** [comment]
glad it is just a visual glitch, could you imagine someone just casually having owner perms

**Comment by TheMan6900** [comment]
oh yeah
![image](https://github.com/EmeraldLoc/tag/assets/168046906/b7d1eae4-d023-4e58-8542-bac174f1925a)

**Comment by EmeraldLoc** [comment]
I keep trying to figure out the error. Some good things are that the actual permission stuff is absolutely rock solid, none of that'll be a problem. The only thing I can think of is on join, for some reason, the title is being set to another player's title, like yours, but I really don't know.

**Comment by EmeraldLoc** [comment]
If you ever figure out how to reproduce this, lmk

**Comment by EmeraldLoc** [comment]
Resolved :D
