### ISSUE TITLE
Soft bonk speed bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#807]
both boost and speed modifer

https://github.com/EmeraldLoc/tag/assets/168046906/d5b666f4-f469-4e5c-a31a-c688cc6f83e9

**Comment by PolarBear32** [comment]
SR 1.5 port leak?!??!?!?!?!?!/

**Comment by TheMan6900** [comment]
whoopsies 😆

**Comment by EmeraldLoc** [comment]
Fixed
