### ISSUE TITLE
Saus in the romhack credits.

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#816]
Saus has worked on Star Revenge 1.5, however he is nowhere to be seen in the romhack porter credits.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/131383a6-6744-41b8-88da-a20219613a41)

**Comment by EmeraldLoc** [comment]
Will update

**Comment by EmeraldLoc** [comment]
Love coding on a phone (it sucks) Done
