### ISSUE TITLE
New API: unwantedArenaBhvs (Addons)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#817]
Make it so that you can decide whether you want to remove a specific arena object from an addon level. This specific object could be a spring or a pair of pipes. Stages like Bitforts could really get an overhaul w/ the pipes (no one uses the pipes in the castle, plus they're hard to use)

**Comment by EmeraldLoc** [comment]
Can't you use unwantedBhv's?

**Comment by Bear64DX** [comment]
That works for addon levels? If so I'm dying to know how. But I thought you couldn't use those w/ pipes and springs because those are both customBhvs?

**Comment by EmeraldLoc** [comment]
Oh wait you can't, but you don't need to. Just delete the bhv on level init.

```

local function on_level_init()
        local o = obj_get_first_with_behavior_id(get_id_from_behavior_name("bhvArenaFlag"))
        
        while o ~= nil do
                obj_mark_for_deletion(o)
                o = obj_get_next_with_same_behavior_id(o)
        end
end
hook_event(HOOK_ON_LEVEL_INIT, on_level_init)
```

**Comment by Bear64DX** [comment]
Oh dang. So I just insert that code like I would with non slippery collision (after the g.Tag.add_level)? And how'd that work for a spring?

**Comment by EmeraldLoc** [comment]
You'd just delete the spring behavior.

```
local spring = obj_get_first_with_behavior_id(get_id_from_behavior_name("bhvArenaFlag"))
        
while spring ~= nil do
        obj_mark_for_deletion(spring)
        spring = obj_get_next_with_same_behavior_id(spring)
end
```

> after the g.Tag.add_level

I missed something in my first code example. No, you'd want it to be before the addedLevel check happened. You'd want to check `if gNetworkPlayers[0].currLevelNum == LEVEL_BITFORTS`, and if it is, then delete the bhvs.

**Comment by Bear64DX** [comment]
I think I understand it. If I need help I'll let you know

**Comment by EmeraldLoc** [comment]
Gonna close this
