### ISSUE TITLE
Hands Dont Spread Out When In Vertical Wind

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#818]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/8d6db3a7-c7c8-457b-a423-3a7b1844c8b9)
tag

base game
![image](https://github.com/EmeraldLoc/tag/assets/168046906/33179d6c-89b9-422c-bb2f-720c2f9f62f6)

**Comment by EmeraldLoc** [comment]
What stage is that?

**Comment by TheMan6900** [comment]
the port were working on, (not sure if bear revealed it to you yet, but if he hasent, I wanna keep it a secret :trollface:)

**Comment by EmeraldLoc** [comment]
Oh eureka, looks like a cool hack!

**Comment by TheMan6900** [comment]
ok nevermind, also, glad you like it

**Comment by EmeraldLoc** [comment]
Fixed
