### ISSUE TITLE
New API: overrideMusic

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#819]
Exactly what it sounds like. You could use this function to override certain music in a level. The reason why I am suggesting this is because sometimes hacks have better OSTs than the stage OST. For example, GS' Wing Cap theme is WAAAAY better than the Wing Cap stage. The function could look smth like this: `overrideMusic = "0E_Seq_GS_custom"`
It wouldn't matter if the music name overwrites other music names in certain hacks because the music would be pulled from the current hack.

**Comment by EmeraldLoc** [comment]
I’d want to make this include mp3 files as well, good idea.

**Comment by Bear64DX** [comment]
> I’d want to make this include mp3 files as well, good idea.

Oh even better

**Comment by EmeraldLoc** [comment]
On second thought, the romhacker put in music for a certain atmosphere, and I believe that should be respected.

**Comment by Bear64DX** [comment]
That's a really good point, but the thing is that some levels in hacks are silent, like in most of the Star Revenge hacks. It would be cool if there was a way to add music to them, but I digress.
