### ISSUE TITLE
SM74 Tag Pack Issue

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#82]
Tag packs (like tag - arena maps, tag - mcdonalds, and tag - bitfort) load twice for SM74 specifically

**Comment by EmeraldLoc** [comment]
I am unable to reproduce with v2.32 and sm74. Are there any other things you do to get this to happen?

**Comment by TheMan6900** [comment]
Im not sure what produces this problem, it may just be a random issue, since it often (not all the time) happens in my server

**Comment by EmeraldLoc** [comment]
Gonna close this cuz it seems random. If you find a reproducible way to get this bug, reopen this issue.
