### ISSUE TITLE
Can't disable wind? Am I tripping?

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#822]
So in one of my stages, I disabled the wind using `unwantedBhvs = { id_bhvWind }`, however the wind is still in the stage. Here are some screenshots of it.

The code mentions that it shouldn't be there
![image](https://github.com/EmeraldLoc/tag/assets/171458695/30b09e81-688e-4e8d-85e0-af600fdbd4bd)
The game says "Nah, I'd Win"
![image](https://github.com/EmeraldLoc/tag/assets/171458695/69fe895a-d5b2-4231-b258-c3547a5fbbac)

I might've just forgotten smth so if this is a false issue srry lol 

~~also horizontal wind toggle when~~

**Comment by Bear64DX** [comment]
Man I thought I was cooking w/ disabledBhvs
![image](https://github.com/EmeraldLoc/tag/assets/171458695/5446479a-93a2-4245-af63-a095dbeac6de)

**Comment by EmeraldLoc** [comment]
It’s also a surface type

**Comment by Bear64DX** [comment]
> It’s also a surface type

It's a what now

**Comment by EmeraldLoc** [comment]
You need to override the surface wind floor type.

**Comment by Bear64DX** [comment]
> You need to override the surface wind floor type.

Yea I figured out that overriding it w/ Default fixed it.
