### ISSUE TITLE
Make Overwritten Names Display In The Playlist

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#823]
Pretty self explanatory

**Comment by EmeraldLoc** [comment]
No it’s not. What are you talking about?

**Comment by Bear64DX** [comment]
For example, I renamed the level to "Factory of the Farmland", and while the level does show up as that in Tag, it's still "Farmland Factory" in the playerlist. 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/f1ffb73c-5f98-448d-a238-7afe0ffadb45)

**Comment by EmeraldLoc** [comment]
Oh yea I was thinking about this for a while. It simply isn’t viable to implement unfortunately. Need to make an issue on a function so I can replace the playerlist, so I can do this.
