### ISSUE TITLE
New API: Block API

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#825]
I've talked about this before but I thought it'd be nice to make an issue on this.
Having an API that allows you to place metal blocks that can't be destroyed (like in Shine Thief), would be very nice for certain levels.

**Comment by TheMan6900** [comment]
addbhvapi, already being added

**Comment by Bear64DX** [comment]
I mean I guess, but I haven't heard any news of it. Not even on the dev repo.

**Comment by EmeraldLoc** [comment]
The add behavior level entry shouldn't really exist, since a literal function that runs every frame if a level is selected exists in the api.... so.... This one makes more sense imo.

**Comment by TheMan6900** [comment]
> The add behavior level entry shouldn't really exist, since a literal function that runs every frame if a level is selected exists in the api.... so.... This one makes more sense imo.

fair

**Comment by TheMan6900** [comment]
this would honestly be a life saver for blocking off areas that make levels, obnoxiously huge

**Comment by Bear64DX** [comment]
Oh yeah. It's like the room system if it was good (joke, but nah seriously this would be fire since it could also block off tiny areas without breaking the entire level)

**Comment by TheMan6900** [comment]
Kinda hope this gets added in 2.41 so we can use it for our ports

**Comment by EmeraldLoc** [comment]
Added
