### ISSUE TITLE
Description Bug #4

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#832]
No S?
![image](https://github.com/EmeraldLoc/tag/assets/171458695/3e99a22e-95cf-4df7-868c-05d5624c8e4d)
![image](https://github.com/EmeraldLoc/tag/assets/171458695/ad7c2598-015c-4c13-ab01-31cf185f8c95)

**Comment by EmeraldLoc** [comment]
tag support romhack!

**Comment by EmeraldLoc** [comment]
fixed
