### ISSUE TITLE
New star road level - Creepy Metal Cap Cave

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#834]
Youd be spawned in the main area of the stage (the place where youd collect the red coins) with blocks, blocking that way to the slide

**Comment by Bear64DX** [comment]
PEAK

**Comment by TheMan6900** [comment]
Can I also cook this level emerald?

**Comment by EmeraldLoc** [comment]
sure

**Comment by TheMan6900** [comment]
added
