### ISSUE TITLE
Possible Gusty Grotto Reimplemtation

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#835]
What wed basically do is block off the wind gust area with the block api, thats really it.

**Comment by Bear64DX** [comment]
Oh, and this part of the map is blocked by the Vanish Cap, so that isn't a problem. But Gusty Garden is a rlly good stage tbh
![image](https://github.com/EmeraldLoc/tag/assets/171458695/4ebb138b-fc9d-4bab-96cb-01a4b0b220e5)

**Comment by EmeraldLoc** [comment]
Currently adding that section to the api, once I add it y'all can experiment with that.
