### ISSUE TITLE
Removing the dialogs entirely

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#836]
I mean, the current ones are "okay" but I'd rather just straight up have them gone. Also there's this weird bug I found where in Wiggler's Cosmic Showdown, you can't escape the dialog. Everytime you try to, you just get stuck.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/ab36a564-1fa5-459e-86a8-87589b68e61a)

https://github.com/EmeraldLoc/tag/assets/171458695/22ae9c77-e952-4438-95cc-0b7bb9e9835c

(EDIT: Bowser's Chilly Arena does work though. I'd still prefer having these gone if possible though)

**Comment by EmeraldLoc** [comment]
But I like the dialogs :(. They are pretty gimmicky, and do cause more problems then they solve (0), so I should probably remove it.

**Comment by TheMan6900** [comment]
Awww :(, Id rather just have them be fixed than be removed

**Comment by Bear64DX** [comment]
Sorry TM, but these things are just too broken and cause problems. On the bright side, it's not like anyone actually read the signs lol

**Comment by TheMan6900** [comment]
> Sorry TM, but these things are just too broken and cause problems. On the bright side, it's not like anyone actually read the signs lol

fair, lol

**Comment by TheMan6900** [comment]
there still kinda fun though

**Comment by Bear64DX** [comment]
I personally just don't wanna hear wiggler YAP every time I play WCS

**Comment by TheMan6900** [comment]
> I personally just don't wanna hear wiggler YAP every time I play WCS

lol

**Comment by EmeraldLoc** [comment]
R.I.P dialogs. You will be missed by 2 people.
