### ISSUE TITLE
Update Checker (But not depreciated)

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#838]
The same as the last update checker, but would not be depreciated

**Comment by Bear64DX** [comment]
If the update checker is deprecated, does that mean that the function was just changed like literally every other function? I think this could be re-implemented. But tbh I don't feel like waiting 2 seconds for the update checker to finish lol

**Comment by TheMan6900** [comment]
I just liked looking at the tag logo lol

**Comment by EmeraldLoc** [comment]
Wow, yea let me just undepredecate the update checker.
