### ISSUE TITLE
"Tag" Premade Theme

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#840]
Would be a mix of reds, and blues.

**Comment by EmeraldLoc** [comment]
So an America theme 🇺🇸🇺🇸🦅🦅🦅

**Comment by TheMan6900** [comment]
yes 💀

**Comment by EmeraldLoc** [comment]
I'd rather you make an issue with some images of a theme you've created, or just make a pr (the theme system is SUPER simple, look in `a-themes.lua`)
