### ISSUE TITLE
Frame Rate Slowly decreasing until the game crashes

### ISSUE THREAD

**Issue by PedroSV2012** [EmeraldLoc/tag#841]
why the game's frame rate dreceases when i host a game with this mod? why?

**Comment by EmeraldLoc** [comment]
What game mode were you on when this lag occurred?

**Comment by EmeraldLoc** [comment]
Was the game being hammered with script errors?

**Comment by TheMan6900** [comment]
pretty sure, this has happen to me before, pretty sure it can happen on any gamemode
