### ISSUE TITLE
Convert Sign Dialog To Tips

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#847]
Since some of them were kinda funny

**Comment by EmeraldLoc** [comment]
Most of them were.

**Comment by EmeraldLoc** [comment]
And you're in the dev repo, you can go ahead and add some yourself, it's in hud_utils.lua.

**Comment by TheMan6900** [comment]
oh alright

**Comment by TheMan6900** [comment]
Where is the sign dialog?
