### ISSUE TITLE
Hand Vote Indicator

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#85]
The menu hand (mario hand) pointing upwards to the map your hovering/selecting. Would basically be just a neat detail, but its probably not that hard to add, plus it would be slightly helpful.

**Comment by EmeraldLoc** [comment]
Eh, idk about this one, doesn't match the modern theme of the ui

**Comment by TheMan6900** [comment]
You could just simply use a ^ arrow

**Comment by EmeraldLoc** [comment]
Don't think I'm gonna add this. If the voting hud selection isn't clear, then make an issue on that instead.
