### ISSUE TITLE
Bosses get stuck.

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#850]
So with the dialog removal, I've noticed that boss just stay the way they are. This is sad because Wiggler's Cosmic Showdown is a lot interesting w/ Wiggler, but the fact that he doesn't do anything is sad. 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/1e333067-c52e-4a8a-840f-be5140858419)

**Comment by EmeraldLoc** [comment]
Don't think there's really a way to fix this... yea...
