### ISSUE TITLE
Deathplane Indicator

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#853]
This would indicate where a deathplane floor was placed, useful for both rh porters, and players

**Comment by TheMan6900** [comment]
could possibly look like this 

https://github.com/EmeraldLoc/tag/assets/168046906/872cd8bb-e932-44e8-84b3-62ba94f1dda0

**Comment by EmeraldLoc** [comment]
Don't think I could do a scroll effect like that, could look into it
