### ISSUE TITLE
Block (Now Barrier) Revamp

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#854]
Instead of just being blocks, theyd instead be barriers, similar in design to the death barriers, but instead of a skull texture, would be a X
texture.

**Comment by Bear64DX** [comment]
What if Barriers and Blocks were their own thing?

**Comment by TheMan6900** [comment]
barriers would be the same as blocks

**Comment by EmeraldLoc** [comment]
It’s blocks, not barriers. Models are being added, I still have to make them.

**Comment by Bear64DX** [comment]
Wait, for blocks? I thought you could just use the metal block model like in Shine Thief. That could be cool

**Comment by EmeraldLoc** [comment]
I’ll let the user select the model, default will be a custom one.
