### ISSUE TITLE
Bone Breaking Shenanigans

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#857]
So I was searching for a sardine and I stumbled across this Toad that looked all jacked up. Idk what could've caused this.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/af3695d3-94f9-4368-b218-f0c0d3beafd9)

**Comment by EmeraldLoc** [comment]
Coop bug

**Comment by Bear64DX** [comment]
gotta love joop
