### ISSUE TITLE
Scripting Error (main.lua, line 1192+1189)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#858]
I loaded up a custom level and I was greeted with this error. It only happens when I load that one specific level.
![image](https://github.com/EmeraldLoc/tag/assets/171458695/84f210ff-4a69-49ec-bbc1-8555435b1d54)

**Comment by EmeraldLoc** [comment]
Pipes appear to be configured wrong. What hack, does it exist or is it a hack you're porting?

**Comment by Bear64DX** [comment]
A hack I'm porting. We can see it for ourselves.

**Comment by Bear64DX** [comment]
Wait I think my code is wrong hold up

**Comment by EmeraldLoc** [comment]
It is, the pipe code doesn't fail.

**Comment by Bear64DX** [comment]
I fixed it!
