### ISSUE TITLE
Double Jump Hitstun

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#862]
Make it so that when you get hit, you can't double jump out of it. Juggernauts can easily get out of any attack when they double jump, which doesn't make it fun.

**Comment by EmeraldLoc** [comment]
What? That just makes it more balanced.

**Comment by Bear64DX** [comment]
Sure.....

**Comment by TheMan6900** [comment]
> What? That just makes it more balanced.
How?

**Comment by EmeraldLoc** [comment]
Otherwise it's much easier for the juggernaut to get farmed on the ground.

**Comment by TheMan6900** [comment]
Could just implement the revamped i-frames, that would fix the problem

**Comment by Bear64DX** [comment]
> Otherwise it's much easier for the juggernaut to get farmed on the ground.

Not really. 

> Could just implement the revamped i-frames, that would fix the problem

I agree. Plus, the juggernaut has more time to escape than you think it does. I think the reason why you think it doesn't have a lot of time is because you're used to old jugger. I've seen the i-frames before, I think the jugger would have a lot of time to escape. Plus, you could just make the jugger's i-frames a teeny tiny longer if its that bad.

**Comment by EmeraldLoc** [comment]
Hm

**Comment by Bear64DX** [comment]
(might wanna re-open this issue if you're not sure)

**Comment by TheMan6900** [comment]
neither is this
