### ISSUE TITLE
point bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#863]
![image](https://github.com/EmeraldLoc/tag/assets/168046906/904f26fd-c213-4fa9-867f-2d4270550129)
had 32 points total last game, and for some reason they carried over to the next?

**Comment by EmeraldLoc** [comment]
Good to see this is actually confirmed now

**Comment by EmeraldLoc** [comment]
I see, I have a race condition.... this is gonna be fun to fix

**Comment by EmeraldLoc** [comment]
Fixed
