### ISSUE TITLE
Revamped Sardine Hiding Screen

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#868]
Have it say, X is hiding, instead of just sardine is hiding, with the sardine in the top left.
![image](https://github.com/EmeraldLoc/tag/assets/168046906/596acbbe-8bc2-4ca4-b420-ee0b00885d4c)

**Comment by EmeraldLoc** [comment]
Eh, removing the gamemode anyways.

**Comment by TheMan6900** [comment]
oh alright

**Comment by Bear64DX** [comment]
> Eh, removing the gamemode anyways.

EMERALDBASEDDOWN
