### ISSUE TITLE
FAQ ingame

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#874]
Would be a QnA in the help section, would probably just be ripped from the QnA on the github/coopdx website

**Comment by Bear64DX** [comment]
> would probably just be ripped from the QnA on the github/coopdx website

Think it could be a lil more impressive than that lol

**Comment by TheMan6900** [comment]
> > would probably just be ripped from the QnA on the github/coopdx website
> 
> Think it could be a lil more impressive than that lol

def

**Comment by EmeraldLoc** [comment]
Me looking at this now, holy just go to the modding site if you're playing it go to the help section
