### ISSUE TITLE
SR 1.5 name in credits incorrect

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#876]
Name of star revenge 1.5 in credits should have a : instead of a -

**Comment by EmeraldLoc** [comment]
Free fix

**Comment by Bear64DX** [comment]
rip leaks 😭

**Comment by EmeraldLoc** [comment]
You thought

**Comment by Bear64DX** [comment]
I mean its a hype port so I dont blame you

**Comment by EmeraldLoc** [comment]
Btw, you can make issues in the development repo if it's dev repo related

**Comment by Bear64DX** [comment]
> Btw, you can make issues in the development repo if it's dev repo related

alr
