### ISSUE TITLE
Add a colon to "Found romhack"

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#877]
Would just make it look cleaner 
![image](https://github.com/user-attachments/assets/738a29fa-d709-4e40-be4f-ecc5e455f8ae)

**Comment by EmeraldLoc** [comment]
Need to redo the text entirely. Adding a comma there would look weird imo. Think i'd rather do something like "Set Romhack to Star Road"

**Comment by Bear64DX** [comment]
> Need to redo the text entirely. Adding a comma there would look weird imo. Think i'd rather do something like "Set Romhack to Star Road"

Fair, I think "Found romhack: Star Road" would look the best. But that's just me.

**Comment by EmeraldLoc** [comment]
Ah, that'd look nice. I thought you meant the "," character. Think I still prefer what I said above, will see if my opinion changes when I change the text.

**Comment by Bear64DX** [comment]
> Ah, that'd look nice. I thought you meant the "," character. Think I still prefer what I said above, will see if my opinion changes when I change the text.

Oh lol

**Comment by EmeraldLoc** [comment]
Changed to "Found Romhack: Star Road"
