### ISSUE TITLE
Add a !/,/: to "Completed Achievement"

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#880]
would look better
![image](https://github.com/user-attachments/assets/fb78ac56-ba21-4c83-8e93-4110bea68849)

**Comment by Bear64DX** [comment]
I'm not sure if the exclamation mark makes sense because it's not telling you that you did something. "Taggers Win" makes sense because it shows you the winners. I just don't think that makes much sense here tbh. Though, I do think a colon (:) would look good.

**Comment by TheMan6900** [comment]
> I'm not sure if the exclamation mark makes sense because it's not telling you that you did something. "Taggers Win" makes sense because it shows you the winners. I just don't think that makes much sense here tbh. Though, I do think a colon (:) would look good.

fair

**Comment by EmeraldLoc** [comment]
Looks fine as is
