### ISSUE TITLE
lava bouncing sound bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#885]
https://github.com/user-attachments/assets/f061f7cd-f020-4ad7-860a-71863cbdc5c9

**Comment by Flower35** [comment]
In sm64coopdx, this check always passes, and the sound plays on *every* update frame (restarts non-stop, the moment player starts bouncing off the lava):

https://github.com/EmeraldLoc/tag/blob/17cb0d9eb7144de9f0c29488e99284352454fc1d/act_lava_boost.lua#L6-L9

It seems the code later in this function is enough, although it does *not* play on the *first* contact with the lava floor:

https://github.com/EmeraldLoc/tag/blob/17cb0d9eb7144de9f0c29488e99284352454fc1d/act_lava_boost.lua#L19-L24

**Comment by EmeraldLoc** [comment]
I forgot to close this issue, I resolved it using another method.

> In sm64coopdx, this check always passes, and the sound plays on every update frame (restarts non-stop, the moment player starts bouncing off the lava)

Yea I had noticed this, I figured a simple solution that would keep it close to what it normally is in decomp is simply setting that flag when we check it. So I created a newline at line 8 and added `m.flags = m.flags | MARIO_MARIO_SOUND_PLAYED`, which resolved the issue.
