### ISSUE TITLE
New level - B2

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#889]
The bowser 2 arena with a deathplane where the lava is. the stage could tilt at random intervals.

**Comment by Bear64DX** [comment]
Generally good, but it'd be cool if the only way you could die was genuinely falling off the course. Like for example, if I'm at the bottom of the course when I die, I wouldn't wanna die because I'm still on the course. Great suggestion though!

**Comment by EmeraldLoc** [comment]
Man.. you really do have dementia. I tried this before, this had syncing issues.

**Comment by TheMan6900** [comment]
> Man.. you really do have dementia. I tried this before, this had syncing issues.

wait how did this have sinking issues?

**Comment by Bear64DX** [comment]
Wait, how does this level work in Shine Thief then?

**Comment by EmeraldLoc** [comment]
> > Man.. you really do have dementia. I tried this before, this had syncing issues.
> 
> wait how did this have sinking issues?

It’s been a while I don’t quite remember. I believe clipping was an issue.

> Wait, how does this level work in Shine Thief then?

That has bowser, this level would not. It’d use a custom system for the tilting of the platform

**Comment by Bear64DX** [comment]
> That has bowser, this level would not. It’d use a custom system for the tilting of the platform

Oh

**Comment by TheMan6900** [comment]
why not just, force bowser to be in the tag then?

**Comment by Bear64DX** [comment]
> why not just, force bowser to be in the tag then?

I mean not everyone wants Bowser in the arena

**Comment by TheMan6900** [comment]
No I mean like only for him to jump or something

**Comment by EmeraldLoc** [comment]
No. Bowser will not stay.

**Comment by EmeraldLoc** [comment]
Ill give this a go again and see what happens

**Comment by Bear64DX** [comment]
> No. Bowser will not stay.

He'd still be an enemy toggle right?

**Comment by EmeraldLoc** [comment]
Yea, just not in that level.

**Comment by Bear64DX** [comment]
Ah, okay
