### ISSUE TITLE
Crash with less than 4 levels

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#89]
If a your playing with a mod that has less than 3 levels in it (like, the underworld), or have less than 3 levels (rest being blacklisted). The game will straight up crash.

**Comment by EmeraldLoc** [comment]
Yea I was kinda procrastinating on this bug lol.

**Comment by TheMan6900** [comment]
note that this can happen with counts higher than below 3

**Comment by EmeraldLoc** [comment]
That's a crazy sentence, "higher than below 3".

I believe the crash will stop happening when you reach 4 levels. At 4 levels, it can select 3 levels for the vote screen, and not include the previous level. This also applies to blacklists and what not. If there's something else im missing to this bug, say so.

**Comment by TheMan6900** [comment]
nope you aint missing anything

**Comment by EmeraldLoc** [comment]
Fixed
