### ISSUE TITLE
Update Notification Sound Effect

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#890]
Maybe a ding sound effect

**Comment by EmeraldLoc** [comment]
We did this like 2 weeks ago, the updater's been removed, do you have dementia??!?!?!?

**Comment by TheMan6900** [comment]
> We did this like 2 weeks ago, the updater's been removed, do you have dementia??!?!?!?

Thought it was being readded

**Comment by EmeraldLoc** [comment]
It's no longer possible to. Lua no longer has any way to communicate with external files.

**Comment by TheMan6900** [comment]
oh

**Comment by TheMan6900** [comment]
you should make an issue on that in the coopdx repo tbh.

**Comment by EmeraldLoc** [comment]
It is not my problem to worry about why internet access was removed from Lua. Knowing the dev's, they most likely had some great discussions on it, and came to this conclusion with good reasoning. I have no good reason to combat the decision to remove `audio_stream_load_url`.

**Comment by TheMan6900** [comment]
fair
