### ISSUE TITLE
Weird Inconsistency 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#892]
heres the reset text for literally every setting with a reset.
![image](https://github.com/user-attachments/assets/02e27a74-a731-48e0-a5f1-14cd9d47117e)

and heres the enemies one
![image](https://github.com/user-attachments/assets/35d01c3d-62b1-4e03-a7c4-0798c30ebacc)

**Comment by EmeraldLoc** [comment]
Should rename all to reset to default

**Comment by EmeraldLoc** [comment]
Resolved
