### ISSUE TITLE
Make enemies save

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#894]
https://github.com/user-attachments/assets/052d4ea3-02ad-4595-8454-f6a806f369a5

**Comment by TheMan6900** [comment]
Huh?

**Comment by EmeraldLoc** [comment]
https://github.com/EmeraldLoc/tag/issues/272

**Comment by TheMan6900** [comment]
that should of been added, along with all the other blacklist saving stuff 💀
