### ISSUE TITLE
New Modifier - Walkable Slopes

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#9]
Pretty self-explanatory, makes every sloped surface walkable

**Comment by TheMan6900** [comment]
now thinking about this suggestion is a bit redundant, cause of the shells

**Comment by EmeraldLoc** [comment]
Except that only applies if you're on a shell. It's still a handy modifier, and will be added.

**Comment by EmeraldLoc** [comment]
Added
