### ISSUE TITLE
Spectators Can Still Break Boxes

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#900]
https://github.com/user-attachments/assets/3a3ff213-81b5-45b5-a953-b3d95144bf0a

**Comment by TheMan6900** [comment]
https://github.com/user-attachments/assets/d912fe31-4f67-4e71-801f-6b8e1181244f

**Comment by EmeraldLoc** [comment]
Not part of the interaction hook, so can't really fix this.
