### ISSUE TITLE
New achievement - Every man for themselves 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#902]
Objective: Win 50 or 100 (or even X number of tourneys) matches with friendly fire on.
Reward: Veteran

**Comment by Bear64DX** [comment]
Didn't emerald say he DIDN'T like friendly fire achievements, yet this is literally like the fourth one?

**Comment by TheMan6900** [comment]
> Didn't emerald say he DIDN'T like friendly fire achievements, yet this is literally like the fourth one?

Not necessarily, achievements that revolve around killing people.

**Comment by EmeraldLoc** [comment]
No
