### ISSUE TITLE
Cursor Support

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#91]
basically the exact same as mariohunt, this would allow you to use a mouse to interact with the settings.
this would mean that the slidebar would have to be scrollable/interactable so you could properly use this feature.

**Comment by EmeraldLoc** [comment]
I already tried doing this, it's really gimicky and doesn't actually matter that much, plus the sensitivity doesn't match your operating system's cursor. The implementation would take a ton of time for not that much reward.
