### ISSUE TITLE
Mess up level ordering for unsupported hacks

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#915]
levels 6, 7, 8, 9 and 10.

**Comment by EmeraldLoc** [comment]
? These are all fine?

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/5ceff3a9-22bb-4caa-b879-29fb53fef95c)

**Comment by TheMan6900** [comment]
(assuming you know the list of levels from this hack, seeing how you ported its remake 6.5)

**Comment by EmeraldLoc** [comment]
resolved

**Comment by TheMan6900** [comment]
this is STILL not resolved

**Comment by TheMan6900** [comment]
Still Not Fixed

**Comment by EmeraldLoc** [comment]
Can you show this? I went by course num so this should be spot on

**Comment by TheMan6900** [comment]
https://github.com/user-attachments/assets/fdd68e2f-eaaf-4eee-af78-00f58b7c935e

**Comment by EmeraldLoc** [comment]
Oops, fixed
