### ISSUE TITLE
Spring speed overflow?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#916]
https://github.com/user-attachments/assets/885a01cf-b1ae-4ca3-83e3-2808250f95da

**Comment by Bear64DX** [comment]
Gotta love how springs literally loop back around if you try to make them stronger. This bug is SERIOUSLY so annoying though.

**Comment by TheMan6900** [comment]
(oh yeah I should probably mention that Im working on a moonshine port right now so uh emerald, if your seeing this you might wanna join my server, same pass as always)

**Comment by Bear64DX** [comment]
(e just in case you forgor emerald)

**Comment by EmeraldLoc** [comment]
Fixed
