### ISSUE TITLE
New api - WalkableWater

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#917]
Would make water walkable.

**Comment by TheMan6900** [comment]
oh yeah, walkable water would still be walkable even if water was turned off

**Comment by EmeraldLoc** [comment]
What? If waters on, water will work as normal, otherwise, you’ll be able to walk on it.

**Comment by TheMan6900** [comment]
> What? If waters on, water will work as normal, otherwise, you’ll be able to walk on it.

youll walk on it, when its on or off

**Comment by EmeraldLoc** [comment]
Added
