### ISSUE TITLE
New Feature - Search

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#92]
This would be one of the main categories (like, tag, rewards, achievements, etc) would let you search up quite literally anything from the tag setting library.  Clicking on a searched setting would toggle it.

**Comment by EmeraldLoc** [comment]
It's impossible for lua to detect keys b eing typed in, so this is not possible to make.

**Comment by TheMan6900** [comment]
read the issue again.

**Comment by EmeraldLoc** [comment]
Yea. It's not possible to actually type something in, the only way to do that is via chat messages.

**Comment by TheMan6900** [comment]
oh, well nevermind
