### ISSUE TITLE
Chuckya Radar Issue

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#923]
![image](https://github.com/user-attachments/assets/62007cbe-98f0-414e-9898-127641771eae)

**Comment by EmeraldLoc** [comment]
Not really a bug, mario's position is just set to limbo, and only mario's gfx pos is updated.

**Comment by Bear64DX** [comment]
> Not really a bug, mario's position is just set to limbo, and only mario's gfx pos is updated.

Kinda like king bob-omb, where his actual pos doesn't move, but his gfx does?
