### ISSUE TITLE
Stage Switch Bug?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#924]
If you switch between stages, that share the same course and area id, yet with different spawns, the spawns wont update to there respective levels

https://github.com/user-attachments/assets/c3daa51d-eedd-4535-a905-db8de678d212

**Comment by TheMan6900** [comment]
Only seems to happen in mutiplayer

**Comment by TheMan6900** [comment]
another werid side effect of this glitch is that levels, some levels no matter if they have an override name appear with there nature name.

**Comment by EmeraldLoc** [comment]
This should be resolved now
