### ISSUE TITLE
Possibly Revert Bombs

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#925]
I feel like bombs kind of fell off in this update. It instead stuns you, which isn't even that fun. Plus, it's likely for YOU to also get stunned, due to you being able to hit yourself (pls fix). It'd be cool if it damaged you, which would make it good again. (also assassins hitstun wya????)

**Comment by EmeraldLoc** [comment]
> also assassins hitstun wya

Not viable, desyncs would be crazy

>  It'd be cool if it damaged you

?

> you're being able to hit yourself

Yea ik, pretty sure there's an issue on this.

> It instead stuns you

Once again, don't understand what you mean, it worked like arena bombs did, just physics changes, which I need to adjust.

**Comment by Bear64DX** [comment]
Ok, lemme clear things up. Bombs in 2.4 don't damage you, as in, they don't tag you/make you lose a life. When you get hit, you just get stunned, meaning the player doesn't get DAMAGED, they just get HIT/STUNNED

**Comment by EmeraldLoc** [comment]
Alr that's a bug, go ahead and make a separate issue on that :)

**Comment by Bear64DX** [comment]
Also, what exactly do you mean by "assassins desync"? Can't you just revert it to the normal hitstun?

**Comment by Bear64DX** [comment]
UPDATE: So for some reason, you CAN hit people. I coulda swore that I wasn't able to hit the person. Dang I must be tripping hard...
