### ISSUE TITLE
Flashy Textures

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#945]
https://github.com/user-attachments/assets/f0c92fe7-6543-42fd-a7e2-6d101750250c

**Comment by EmeraldLoc** [comment]
This is something called Z-Fighting. Move your deathplane up on the y by 1 unit.

**Comment by EmeraldLoc** [comment]
Also, no need to try to edit an issue, you can view the history of an issue.

**Comment by TheMan6900** [comment]
> Also, no need to try to edit an issue, you can view the history of an issue.

oh lol
