### ISSUE TITLE
D-pad Up, and Down Cant Be Binded 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#949]
Strange... (oh yeah thumb L and R cant be binded aswell)

**Comment by EmeraldLoc** [comment]
Don't know what you mean by thumb L and R, I can bind the regular L and R buttons fine. Thought I already closed this issue, guess not, anyways I forgot the reason for this is the user needs a way to cancel the binding, and that'd be the most intuitive way to.
