### ISSUE TITLE
Binding Option - Secondary Bind

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#950]
This would be a kinda failsafe binding that would apply to an ability, if that ability binding gets override by another (ei. juggernaut, and the mutiple ability, and probably some other cases). if a secondary bind was set to the same binding as the primary one, an error would display saying that the binding most be different from the primary, along with the game rejecting the binding.

**Comment by EmeraldLoc** [comment]
What? Just bind the button correctly

**Comment by TheMan6900** [comment]
wdym?

**Comment by TheMan6900** [comment]
> What? Just bind the button correctly

WDYM-

**Comment by TheMan6900** [comment]
this is actually relevant for me and a couple other people

![image](https://github.com/user-attachments/assets/da307ce7-884e-4605-b004-5aa666b59c40)

**Comment by EmeraldLoc** [comment]
Why are your binds the exact same thing? Set it to a different button?

Edit:

I should allow you to not bind a button to anything, because double jump generally doesn't need a bind.

Edit 2:

I forgot how that worked, nvm

**Comment by TheMan6900** [comment]
I actually prefer having double jump binded to X and other people do so

**Comment by TheMan6900** [comment]
and its really annoying having to rebind my buttons before a jugger match so I dont get screwed by the double jump + bomb combo

**Comment by TheMan6900** [comment]
so yeah having this would be really nice.

**Comment by EmeraldLoc** [comment]
> and its really annoying having to rebind my buttons before a jugger match so I dont get screwed by the double jump + bomb combo

yea so don't have your binds be the same, set double jump to a, or set bomb to y, its that simple.

**Comment by TheMan6900** [comment]
> yea so don't have your binds be the same, set double jump to a, or set bomb to y, its that simple.

You shouldnt have to have your binds be a specific way.

**Comment by EmeraldLoc** [comment]
What

Yes you do. Thats the dumbest thing I've heard. That's like saying if a game didn't allow you to bind jump, punch, and kick to the same bind, that's wrong. The game obviously isn't gonna let you do that, because that's stupid, and will suck to play with. This is what sm64coopdx does as well, every game does this, idk what you mean by this. No other game has a failsafe bind system because it's a features that shouldn't need to ever exist.

**Comment by TheMan6900** [comment]
bindings are for individual modifiers (expect for juggernaut), so theirs not that much need for them to be separate bindings.

**Comment by EmeraldLoc** [comment]
Ok. So does that change anything?

> You shouldnt have to have your binds be a specific way.

this is still dumb, sure binds can overlap but not all binds should

> yea so don't have your binds be the same, set double jump to a, or set bomb to y, its that simple.

this still stands
