### ISSUE TITLE
Personal Leaderboard

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#951]
This would be a leaderboard for gamemodes only for the player, that would document the best performances in a gamemode (most tags, most saves, etc)

**Comment by EmeraldLoc** [comment]
I think I’ve stated this before, I’d prefer having a full blown replay system. I’ll look into making a pr into coopdx for this.

**Comment by TheMan6900** [comment]
> I think I’ve stated this before, I’d prefer having a full blown replay system. I’ll look into making a pr into coopdx for this.

how would a replay system work, just curious?

**Comment by EmeraldLoc** [comment]
Every players position and action would be saved to storage, and you’d be able to scrub thru a round.

**Comment by TheMan6900** [comment]
interesting

**Comment by TheMan6900** [comment]
> I think I’ve stated this before, I’d prefer having a full blown replay system. I’ll look into making a pr into coopdx for this

How would positions and other mario stuff be saved into the I presume, sav.file

**Comment by EmeraldLoc** [comment]
This functionality is not possible yet, otherwise it'd just save it to the file?
