### ISSUE TITLE
Ping/Desync Checker

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#952]
This would basically just check if someones ping is about lets say 300-500, and if they were, than it would try resyncing them.

**Comment by EmeraldLoc** [comment]
Resync what? That's way too broad. Also, in order to get this data, I have to send more packets, which is the last thing I want to do if someone is having ping problems.

**Comment by TheMan6900** [comment]
Hear me out, what if when someones ping got too high, packets would stop being sent to them, and when no packets is being sent to a player, than the resyncing screen would show up, until they were resynced.

**Comment by EmeraldLoc** [comment]
You can't identify what got desynced easily, you need to send more packets to do that. This is a big hassle for a silly number that will only confirm the lag that you see. This would be better as a feature for sm64coopdx.
