### ISSUE TITLE
Themes Sometimes Duplicate When Saving

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#954]
Go into a pre-established custom theme, and go into one of the theme settings and just press save, then press save in the main theme setting panel and boom, a dupe. only happens sometimes for some reason

**Comment by EmeraldLoc** [comment]
Are you sure you aren't creating a new theme that's the same as your selected theme, hitting save, and it being the same?

**Comment by TheMan6900** [comment]
Not sure.

**Comment by TheMan6900** [comment]
Ok yeah this issue does exist

**Comment by EmeraldLoc** [comment]
Do you know a way to reproduce this?

**Comment by TheMan6900** [comment]
> Do you know a way to reproduce this?

The description 💀

**Comment by TheMan6900** [comment]
Ok so update, Im pretty sure what actually causes this is by pressing the theme name button, than saving

**Comment by EmeraldLoc** [comment]
> The description 💀

That's not a way to reproduce the bug, that's throwing your head against a wall and praying that something works lol.

> Ok so update, Im pretty sure what actually causes this is by pressing the theme name button, than saving

Ah, so trying to rename the theme?

**Comment by TheMan6900** [comment]
> > The description 💀
> 
> That's not a way to reproduce the bug, that's throwing your head against a wall and praying that something works lol.
> 
> > Ok so update, Im pretty sure what actually causes this is by pressing the theme name button, than saving
> 
> Ah, so trying to rename the theme?

Renaming or just simply pressing the name button and saving dupes the theme

**Comment by EmeraldLoc** [comment]
Unable to reproduce, can you send a video of you reproducing this bug?

**Comment by EmeraldLoc** [comment]
Closing due to being stale, if you encounter this again lmk, and send a video with it happening if possible.
