### ISSUE TITLE
Tons of_MACOSX directories in the Tag release

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#957]
I don't think this can be fixed, but I felt issuing it.

**Comment by EmeraldLoc** [comment]
Is it just the tag release or the git repo as well?

**Comment by Bear64DX** [comment]
The git repo seems fine.

**Comment by EmeraldLoc** [comment]
Ill try to remove them next ver, since im on macOS (i assume) all that junk gets created
