### ISSUE TITLE
Have more players yell at you 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#960]
would be funnier if everyone did
![image](https://github.com/user-attachments/assets/a1da40d1-418c-4cef-9780-e35faf880da2)

**Comment by Bear64DX** [comment]
It's telling *you* though. If it showed someone else, then it'd look like the game's screaming at them, even though you activated the message lol

**Comment by EmeraldLoc** [comment]
Yo bear can you write up more stuff for this message? Also yea that wouldn’t make sense.

**Comment by Bear64DX** [comment]
> Yo bear can you write up more stuff for this message? Also yea that wouldn’t make sense.

What file is it?
