### ISSUE TITLE
New API: Platform API

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#964]
It'd be like Shine Thief, where you could place platforms around the map. They'd have the Vanilla SM64 model and play like how they would in Shine Thief. You'd be able to adjust the size of the platform as well. It'd be good for blocking off areas that make you drop down rather than stretching out a block. Or it'd be good to make platforming levels easier, rather than, yet again, having to stretch out a block. It'd be super useful and come in extreme handy.
![image](https://github.com/user-attachments/assets/817874fb-a2b9-4b68-8ddb-9b54c4831df2)

**Comment by TheMan6900** [comment]
doesnt the block api, already do that 💀

**Comment by Bear64DX** [comment]
> doesnt the block api, already do that 💀

You'd have to stretch it out which would make it look ugly. I guess but tbh I think this works better in certain situations. Plus I feel like this would just work better for platforming rather than using blocks. (I said in the post that stretching it out would be ugly, did you read the entire thing?)

**Comment by TheMan6900** [comment]
This should honestly just be a variant of blocks.

**Comment by Bear64DX** [comment]
> This should honestly just be a variant of blocks.

Hmm, what do you mean?

**Comment by EmeraldLoc** [comment]
You'll be able to customize the model for the blocks, so this will be possible with that api.
