### ISSUE TITLE
A way to input hex codes for theme creation

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#971]
It'd be cool if you could put in hex codes for themes. I know you might've said this isn't possible, but I'm mainly making this issue to ask "why?" since you can input a theme name, but not a hex code. Answers are appreciated, no guarantees this can get added.

**Comment by EmeraldLoc** [comment]
Ye I can make it use chat like the naming system.

**Comment by Bear64DX** [comment]
Hasn't this been added?
