### ISSUE TITLE
Hide Your Stats Only To You While Joining

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#973]
Is it really necessary for the game to tell YOU what your stats are, good for other people to know but, yeah 
![image](https://github.com/user-attachments/assets/5c035965-0c7d-4890-9b93-3e5aa4b3be2c)

**Comment by Bear64DX** [comment]
Sometimes I like to see my stats and I think it's really convenient to see them upon joining rather than manually viewing them in the stats menu. If anything, I think it should be a toggleable option.

**Comment by TheMan6900** [comment]
> Sometimes I like to see my stats and I think it's really convenient to see them upon joining rather than manually viewing them in the stats menu. If anything, I think it should be a toggleable option.

pretty fair tbh

**Comment by TheMan6900** [comment]
actually I kinda changed my mind on this suggestion 💀
