### ISSUE TITLE
Cant Cancel Out Of The Theme Create Menu

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#974]
strange...

**Comment by EmeraldLoc** [comment]
Have you encountered this since? Do you know a way to reproduce this bug?

**Comment by TheMan6900** [comment]
https://github.com/user-attachments/assets/fbcdae2b-e0d2-4804-a37a-33c417c4c2c8

you should actually just make the "delete" button cancel instead

**Comment by EmeraldLoc** [comment]
Believe I resolved this? If it happens again lmk
