### ISSUE TITLE
New API: overrideAction

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#977]
You would be able to override the player's action when they enter a level. You could make them slidekick in, twirl in, ground pound in, etc. It would not only add character to levels, but it would also be cool depending on certain levels. Like imagine you add a factory level, you could make the player slidekick in as in if they're "breaking into the factory" (Note that if you choose the Slidekick action, the game will automatically lunge you forward).

**Comment by EmeraldLoc** [comment]
This is better suited for the `levelLoop` api entry.

**Comment by Bear64DX** [comment]
Wait what is the levelLoop api entry? Never heard of it.

**Comment by EmeraldLoc** [comment]
Taken from documentation

> A function that runs every frame when the level is in play.

**Comment by Bear64DX** [comment]
"a function that runs every frame when the level is in play"

I'm not a coder so I don't exactly know what the possibilities are with that lol

**Comment by EmeraldLoc** [comment]
It's just a function like

```
function example()
     djui_chat_message_create("Ran!")
end
```

And that'll run every frame. Pretty much allows for endless possibilities.

**Comment by Bear64DX** [comment]
Ooh

**Comment by TheMan6900** [comment]
is this how you do it emerald?
![image](https://github.com/user-attachments/assets/c33ccce4-91ce-46f0-8a64-63366fd4a3a5)

**Comment by EmeraldLoc** [comment]
No.... don't you see all the red lines? You need to wrap it in a function, like this

```
levelLoop = function()
        -- code contents here
end
```

Either way, to accomplish what you want, it'd be a lot more reasonable for me to create a `levelInit` entry, so I'll do that..

**Comment by Bear64DX** [comment]
nah teach me how to use levelInit, i needa see this so I can set a spawn action.

**Comment by EmeraldLoc** [comment]
It’s the exact same, but replace levelLoop with levelInit
