### ISSUE TITLE
Recovery API

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#978]
youd be able to override a deathplane in a level, making it a recovery plain, that would bubble you, and take you to your last position on the ground, the recovery plain could also have an adjustable height like a deathplane (also if you wanted mh has a thing thats exactly this in function, so if you wanna just yoink that from mh you can :trollface:)

**Comment by EmeraldLoc** [comment]
> f you wanna just yoink that from mh you can :trollface:

There is something called permission.

This wouldn't be for levels, this would be an option like MH has it. Deathplane api entries would be affected as well.

**Comment by TheMan6900** [comment]
> There is something called permission.

yeah that was kinda a joke 💀
