### ISSUE TITLE
Noteblocks

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#979]
These would functionally be springs... but they float

**Comment by EmeraldLoc** [comment]
ig

**Comment by Bear64DX** [comment]
Nah wait, hear me out. Instead of just having a noteblock API, just have a MOP api. "Tag isn't a level editor" they say, when it's becoming one 💀 (nah but in all seriousness itd be cool trust)

**Comment by EmeraldLoc** [comment]
Actually valid

**Comment by Bear64DX** [comment]
> Actually valid

Chat should I make an issue for this?!

**Comment by TheMan6900** [comment]
how would mops even be useful from a porting perspective, besides noteblocks

**Comment by Bear64DX** [comment]
> how would mops even be useful from a porting perspective, besides noteblocks

They add for level creativity, like how Springs and Pipes do. Plus it'd be fun to play on and use.

**Comment by TheMan6900** [comment]
> > how would mops even be useful from a porting perspective, besides noteblocks
> 
> They add for level creativity, like how Springs and Pipes do. Plus it'd be fun to play on and use.

actually kinda fair.

**Comment by EmeraldLoc** [comment]
See #980
