### ISSUE TITLE
New gamemode - Thieves 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#983]
Everyone would start out with a set amount of points (lets say 5, could adjusted within settings), in ordered to gain points, players would be able to steal points from other players, stripping them of there point and adding it to their own. With the person(s) with the least amount of points when the time runs out, being eliminated.

**Comment by EmeraldLoc** [comment]
Very similar to royal. I like this game more better than royal, and I think it’d be a better idea to make royal work like this game mode. It would bring more strategy then “everyone stay in the same area and pray”

**Comment by TheMan6900** [comment]
I think Royale should stay tbh, it's kinda fun gamemode like Royale where you can go crazy. though I do like this gamemode more than royale so I wouldnt really mind if royale got cut in favor of this.

**Comment by TheMan6900** [comment]
If anything royale should be revamped into the point threshold system that it was originally supposed to be (have to tag until you get the amount of tags needed, once you get the threshold your labeled as finished and are a spectator)

**Comment by Bear64DX** [comment]
midyale...

**Comment by Bear64DX** [comment]
> If anything royale should be revamped into the point threshold system that it was originally supposed to be (have to tag until you get the amount of tags needed, once you get the threshold your labeled as finished and are a spectator)

YES YES YES YES. YES. YES. THIS IS WHAT ROYALE NEEDS. THIS IS WHAT ROYALE SHOULD'VE BEEN. THE NEW ROYALE IS SO MID PLEASE PLEAAAA-

**Comment by EmeraldLoc** [comment]
Royale's been revamped to this gamemode
