### ISSUE TITLE
Xbox/PlayStation Controller Support

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#985]
Have controller related stuff (keybinds, ability indicator, etc) display with its actual controller button instead of the n64 (and the extra ones ig).

**Comment by EmeraldLoc** [comment]
Not possible.

**Comment by TheMan6900** [comment]
I feel like this would be a better issue for the coopdx repo tbh.

**Comment by EmeraldLoc** [comment]
I feel like you should just use your controller naturally tbh.

**Comment by TheMan6900** [comment]
> I feel like you should just use your controller naturally tbh.

wdym?

**Comment by EmeraldLoc** [comment]
Well, I mean what I said (in a less hostile way ofc, never take my messages as that). Joystick up/down come naturally, moving joystick to edit a setting makes sense, and since the first screen you're on is a hub, you have to hit A, so you know A navigates thru menu's like that.

**Comment by TheMan6900** [comment]
> Well, I mean what I said (in a less hostile way ofc, never take my messages as that). Joystick up/down come naturally, moving joystick to edit a setting makes sense, and since the first screen you're on is a hub, you have to hit A, so you know A navigates thru menu's like that.

interesting point, thats actually pretty smart design
