### ISSUE TITLE
Spring Error

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#986]
![image](https://github.com/user-attachments/assets/263f3abb-d12b-416e-bfae-053927230ea2)

**Comment by EmeraldLoc** [comment]
*a pipe error

Please ensure you have pipes configured properly. Can you send a ss of the level data here?

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/7548cdb9-2308-4454-848d-16fd0bd1c20f)

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/7ede7cf8-019c-48ca-bacb-5dfa59834047)
this is a spring

**Comment by EmeraldLoc** [comment]
The springs table is inside the pipes table.

**Comment by TheMan6900** [comment]
not sure if your still there there emerald, but you can join my lobby if your ready, the port is basically finished
