### ISSUE TITLE
Radars Dont Display In Deathmatch

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#991]
self explanatory

**Comment by EmeraldLoc** [comment]
What. They do. Are you sure you don't have the No Radar modifier on.

**Comment by TheMan6900** [comment]
![image](https://github.com/user-attachments/assets/5f44a3dc-3696-467b-bde2-d54fa3998ef8)
my clone is behind the barn

**Comment by TheMan6900** [comment]
more proof
![image](https://github.com/user-attachments/assets/63d8149c-fe1e-4abf-bc89-c8a367736762)

**Comment by EmeraldLoc** [comment]
Wrong repo, this only happens on the latest version. This also happens on every gamemode. Resolved
