### ISSUE TITLE
"Next Modifier" Text

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#992]
This would display the next rounds modifier, if the forced modifier is set to random.

**Comment by TheMan6900** [comment]
Theres an issue that does this 10x better already.

**Comment by EmeraldLoc** [comment]
Was gonna mention the vote change issue thing lol, lets go you caught something!

**Comment by TheMan6900** [comment]
> Was gonna mention the vote change issue thing lol, lets go you caught something!

🔥
