### ISSUE TITLE
New Api - RemoveInviswalls

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#993]
This would remove invisible walls from a level.

**Comment by TheMan6900** [comment]
(this would be useful for that one level in the sr5 port, which got scrapped)

**Comment by Bear64DX** [comment]
> (this would be useful for that one level in the sr5 port, which got scrapped)

???

**Comment by EmeraldLoc** [comment]
Not possible without rewriting collision. This is a fault of the level, not the game.
